In [42]:
# Setup, imports
import math
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)
from patsy import dmatrices
import statsmodels.api as sm 
import seaborn as sn
from scipy.stats import wilcoxon, pearsonr, mannwhitneyu
import scipy.stats as stats
from tableone import TableOne
from IPython.display import display

pd.set_option('display.max_rows', 200)
matplotlib.rcParams['figure.figsize'] = [40, 20]
import warnings
warnings.filterwarnings('ignore')

In [74]:
#organizing input dataframes for baseline, 3 months, 6 months followup

data = pd.read_excel('data_new_raw.xlsx')
colsBL = ['Age', 'Race', 'Indigenous', 'Gender Identity', 'Highschool Education', 'Post- Secondary Education', 'Employment', 'Household income before taxes',
            'Marital status', 'Living situation','Pack years','Alcohol use - average number of drinks/week', 'Substance Use Disorder', 'Depression',
          'Anxiety', 'Health Anxiety', 'Delay to Hospital', 'Personal Stressors', 'Menopause', 'Complicated Pregnancy', 'Stroke History', 'MI History',
          'CABG/Stent History', 'High cholesterol', 'Diabetes', 'Hypertension', 'BMI', 'HFrEF', 'STEMI', 'ESSI score']
colsOutcomesBL = ['HADS-A','HADS-D']
colsOutcomes3m = ['3M New Depression Diagnosis ', '3M New Anxiety Diagnosis ', '3M New Substance Use Disorder', '3M New Stroke', '3M New MI',
                  '3M New CABG/Stent', '3M Cardiac Rehab', '3M Hospitalized ', '3M HADS-A', '3M HADS-D', '3M SF-12 (Low)', '3M Cardiac Anxiety',
                  '3M MOS (Low Support)']
colsOutcomes6m = ['6M New Depression Diagnosis ', '6M New Anxiety Diagnosis', '6M New Substance Use Disorder', '6M New Stroke', '6M New MI',
                  '6M New CABG/Stent', '6M Cardiac Rehab', '6M Hospitalized ', '6M HADS-A', '6M HADS-D', '6M SF-12 (Low)', '6M Cardiac Anxiety',
                  '6M MOS (Low Support)']

cols3m = colsBL + colsOutcomesBL
cols6m = cols3m + colsOutcomes3m

dataBL = data[colsBL+colsOutcomesBL].copy().dropna(axis=0)
data3m = data[colsBL+colsOutcomesBL+colsOutcomes3m].copy().dropna(axis=0)
data6m = data[colsBL+colsOutcomesBL+colsOutcomes3m+colsOutcomes6m].copy().dropna(axis=0)

#defining conitnuous and categorical columns
colsCont = ['Age', 'Pack years', 'Alcohol use - average number of drinks/week','BMI']

colsCat  = colsBL.copy()
for item in colsCont:
    colsCat.remove(item)

cols3mCat = cols3m.copy()
for item in colsCont:
    cols3mCat.remove(item)
    
cols6mCat = cols6m.copy()
for item in colsCont:
    cols6mCat.remove(item)

# Computing significance tests

In [106]:
# computing table 1 stats and p values for each variable for each outcome

for outcome in colsOutcomesBL:
    print('Baseline, Outcome = ' + outcome)
    table = TableOne(dataBL, columns=colsBL, pval = True, 
                       groupby = [outcome], htest_name=True, smd=True)
    filename = outcome + "_baseline_table1.csv"
    #removing backslash from strings
    filename = filename.replace("/","-")
    table.to_csv(filename, index=False)
    
    display(table1BL)

Baseline, Outcome = HADS-A

                                                           Grouped by HADS-D
                                                                     Missing      Overall            0            1 P-Value               Test SMD (0,1)
n                                                                                     698          570          128
Age, mean (SD)                                                             0  67.0 (12.4)  67.3 (12.4)  65.7 (12.2)   0.202  Two Sample T-test    -0.125
Race, n (%)                                            0                   0   627 (89.8)   513 (90.0)   114 (89.1)   0.877        Chi-squared     0.031
                                                       1                        71 (10.2)    57 (10.0)    14 (10.9)
Indigenous, n (%)                                      0                   0   673 (96.4)   549 (96.3)   124 (96.9)   1.000     Fisher's exact     0.031
                                                       1                         25 (3.6)     21 (3.7)      4 (3.1)
Gender Identity, n (%)                                 0                   0   697 (99.9)   569 (99.8)  128 (100.0)   1.000     Fisher's exact       nan
                                                       1                          1 (0.1)      1 (0.2)
Highschool Education, n (%)                            0                   0   617 (88.4)   504 (88.4)   113 (88.3)   1.000        Chi-squared     0.004
                                                       1                        81 (11.6)    66 (11.6)    15 (11.7)
Post- Secondary Education, n (%)                       0                   0   391 (56.0)   323 (56.7)    68 (53.1)   0.528        Chi-squared     0.071
                                                       1                       307 (44.0)   247 (43.3)    60 (46.9)
Employment, n (%)                                      0                   0   611 (87.5)   508 (89.1)   103 (80.5)   0.011        Chi-squared     0.243
                                                       1                        87 (12.5)    62 (10.9)    25 (19.5)
Household income before taxes, n (%)                   0.0                 0   370 (53.0)   304 (53.3)    66 (51.6)   0.791        Chi-squared     0.035
                                                       1.0                     328 (47.0)   266 (46.7)    62 (48.4)
Marital status, n (%)                                  0                   0   351 (50.3)   297 (52.1)    54 (42.2)   0.054        Chi-squared     0.200
                                                       1                       347 (49.7)   273 (47.9)    74 (57.8)
Living situation, n (%)                                0                   0   684 (98.0)   560 (98.2)   124 (96.9)   0.302     Fisher's exact     0.089
                                                       1                         14 (2.0)     10 (1.8)      4 (3.1)
Pack years, mean (SD)                                                      0  26.7 (59.8)  25.4 (58.9)  32.4 (63.6)   0.257  Two Sample T-test     0.114
Alcohol use - average number of drinks/week, mean (SD)                     0    1.6 (3.6)    1.6 (3.6)    1.5 (3.7)   0.845  Two Sample T-test    -0.019
Substance Use Disorder, n (%)                          0                   0   685 (98.1)   562 (98.6)   123 (96.1)   0.071     Fisher's exact     0.156
                                                       1                         13 (1.9)      8 (1.4)      5 (3.9)
Depression, n (%)                                      0                   0   472 (67.6)   410 (71.9)    62 (48.4)  <0.001        Chi-squared     0.494
                                                       1                       226 (32.4)   160 (28.1)    66 (51.6)
Anxiety, n (%)                                         0                   0   492 (70.5)   415 (72.8)    77 (60.2)   0.006        Chi-squared     0.270
                                                       1                       206 (29.5)   155 (27.2)    51 (39.8)
Health Anxiety, n (%)                                  0                   0   430 (61.6)   373 (65.4)    57 (44.5)  <0.001        Chi-squared     0.430
                                                       1                       268 (38.4)   197 (34.6)    71 (55.5)
Delay to Hospital, n (%)                               0                   0   344 (49.3)   289 (50.7)    55 (43.0)   0.138        Chi-squared     0.155
                                                       1                       354 (50.7)   281 (49.3)    73 (57.0)
Personal Stressors, n (%)                              0                   0   377 (54.0)   333 (58.4)    44 (34.4)  <0.001        Chi-squared     0.497
                                                       1                       321 (46.0)   237 (41.6)    84 (65.6)
Menopause, n (%)                                       0                   0   149 (21.3)   114 (20.0)    35 (27.3)   0.087        Chi-squared     0.173
                                                       1                       549 (78.7)   456 (80.0)    93 (72.7)
Complicated Pregnancy, n (%)                           0                   0   516 (73.9)   418 (73.3)    98 (76.6)   0.522        Chi-squared     0.075
                                                       1                       182 (26.1)   152 (26.7)    30 (23.4)
Stroke History, n (%)                                  0                   0   634 (90.8)   519 (91.1)   115 (89.8)   0.796        Chi-squared     0.041
                                                       1                         64 (9.2)     51 (8.9)    13 (10.2)
MI History, n (%)                                      0                   0   572 (81.9)   472 (82.8)   100 (78.1)   0.264        Chi-squared     0.118
                                                       1                       126 (18.1)    98 (17.2)    28 (21.9)
CABG/Stent History, n (%)                              0                   0   589 (84.4)   480 (84.2)   109 (85.2)   0.895        Chi-squared     0.026
                                                       1                       109 (15.6)    90 (15.8)    19 (14.8)
High cholesterol, n (%)                                0                   0   301 (43.1)   254 (44.6)    47 (36.7)   0.128        Chi-squared     0.160
                                                       1                       397 (56.9)   316 (55.4)    81 (63.3)
Diabetes, n (%)                                        0                   0   504 (72.2)   415 (72.8)    89 (69.5)   0.523        Chi-squared     0.072
                                                       1                       194 (27.8)   155 (27.2)    39 (30.5)
Hypertension, n (%)                                    0                   0   265 (38.0)   216 (37.9)    49 (38.3)   1.000        Chi-squared     0.008
                                                       1                       433 (62.0)   354 (62.1)    79 (61.7)
BMI, mean (SD)                                                             0   28.7 (6.5)   28.7 (6.5)   28.8 (6.6)   0.919  Two Sample T-test     0.010
HFrEF, n (%)                                           0                   0   395 (56.6)   330 (57.9)    65 (50.8)   0.171        Chi-squared     0.143
                                                       1                       303 (43.4)   240 (42.1)    63 (49.2)
STEMI, n (%)                                           0                   0   384 (55.0)   321 (56.3)    63 (49.2)   0.174        Chi-squared     0.143
                                                       1                       314 (45.0)   249 (43.7)    65 (50.8)
ESSI score, n (%)                                      0                   0   483 (69.2)   423 (74.2)    60 (46.9)  <0.001        Chi-squared     0.583
                                                       1                       215 (30.8)   147 (25.8)    68 (53.1)

Baseline, Outcome = HADS-D

                                                           Grouped by HADS-D
                                                                     Missing      Overall            0            1 P-Value               Test SMD (0,1)
n                                                                                     698          570          128
Age, mean (SD)                                                             0  67.0 (12.4)  67.3 (12.4)  65.7 (12.2)   0.202  Two Sample T-test    -0.125
Race, n (%)                                            0                   0   627 (89.8)   513 (90.0)   114 (89.1)   0.877        Chi-squared     0.031
                                                       1                        71 (10.2)    57 (10.0)    14 (10.9)
Indigenous, n (%)                                      0                   0   673 (96.4)   549 (96.3)   124 (96.9)   1.000     Fisher's exact     0.031
                                                       1                         25 (3.6)     21 (3.7)      4 (3.1)
Gender Identity, n (%)                                 0                   0   697 (99.9)   569 (99.8)  128 (100.0)   1.000     Fisher's exact       nan
                                                       1                          1 (0.1)      1 (0.2)
Highschool Education, n (%)                            0                   0   617 (88.4)   504 (88.4)   113 (88.3)   1.000        Chi-squared     0.004
                                                       1                        81 (11.6)    66 (11.6)    15 (11.7)
Post- Secondary Education, n (%)                       0                   0   391 (56.0)   323 (56.7)    68 (53.1)   0.528        Chi-squared     0.071
                                                       1                       307 (44.0)   247 (43.3)    60 (46.9)
Employment, n (%)                                      0                   0   611 (87.5)   508 (89.1)   103 (80.5)   0.011        Chi-squared     0.243
                                                       1                        87 (12.5)    62 (10.9)    25 (19.5)
Household income before taxes, n (%)                   0.0                 0   370 (53.0)   304 (53.3)    66 (51.6)   0.791        Chi-squared     0.035
                                                       1.0                     328 (47.0)   266 (46.7)    62 (48.4)
Marital status, n (%)                                  0                   0   351 (50.3)   297 (52.1)    54 (42.2)   0.054        Chi-squared     0.200
                                                       1                       347 (49.7)   273 (47.9)    74 (57.8)
Living situation, n (%)                                0                   0   684 (98.0)   560 (98.2)   124 (96.9)   0.302     Fisher's exact     0.089
                                                       1                         14 (2.0)     10 (1.8)      4 (3.1)
Pack years, mean (SD)                                                      0  26.7 (59.8)  25.4 (58.9)  32.4 (63.6)   0.257  Two Sample T-test     0.114
Alcohol use - average number of drinks/week, mean (SD)                     0    1.6 (3.6)    1.6 (3.6)    1.5 (3.7)   0.845  Two Sample T-test    -0.019
Substance Use Disorder, n (%)                          0                   0   685 (98.1)   562 (98.6)   123 (96.1)   0.071     Fisher's exact     0.156
                                                       1                         13 (1.9)      8 (1.4)      5 (3.9)
Depression, n (%)                                      0                   0   472 (67.6)   410 (71.9)    62 (48.4)  <0.001        Chi-squared     0.494
                                                       1                       226 (32.4)   160 (28.1)    66 (51.6)
Anxiety, n (%)                                         0                   0   492 (70.5)   415 (72.8)    77 (60.2)   0.006        Chi-squared     0.270
                                                       1                       206 (29.5)   155 (27.2)    51 (39.8)
Health Anxiety, n (%)                                  0                   0   430 (61.6)   373 (65.4)    57 (44.5)  <0.001        Chi-squared     0.430
                                                       1                       268 (38.4)   197 (34.6)    71 (55.5)
Delay to Hospital, n (%)                               0                   0   344 (49.3)   289 (50.7)    55 (43.0)   0.138        Chi-squared     0.155
                                                       1                       354 (50.7)   281 (49.3)    73 (57.0)
Personal Stressors, n (%)                              0                   0   377 (54.0)   333 (58.4)    44 (34.4)  <0.001        Chi-squared     0.497
                                                       1                       321 (46.0)   237 (41.6)    84 (65.6)
Menopause, n (%)                                       0                   0   149 (21.3)   114 (20.0)    35 (27.3)   0.087        Chi-squared     0.173
                                                       1                       549 (78.7)   456 (80.0)    93 (72.7)
Complicated Pregnancy, n (%)                           0                   0   516 (73.9)   418 (73.3)    98 (76.6)   0.522        Chi-squared     0.075
                                                       1                       182 (26.1)   152 (26.7)    30 (23.4)
Stroke History, n (%)                                  0                   0   634 (90.8)   519 (91.1)   115 (89.8)   0.796        Chi-squared     0.041
                                                       1                         64 (9.2)     51 (8.9)    13 (10.2)
MI History, n (%)                                      0                   0   572 (81.9)   472 (82.8)   100 (78.1)   0.264        Chi-squared     0.118
                                                       1                       126 (18.1)    98 (17.2)    28 (21.9)
CABG/Stent History, n (%)                              0                   0   589 (84.4)   480 (84.2)   109 (85.2)   0.895        Chi-squared     0.026
                                                       1                       109 (15.6)    90 (15.8)    19 (14.8)
High cholesterol, n (%)                                0                   0   301 (43.1)   254 (44.6)    47 (36.7)   0.128        Chi-squared     0.160
                                                       1                       397 (56.9)   316 (55.4)    81 (63.3)
Diabetes, n (%)                                        0                   0   504 (72.2)   415 (72.8)    89 (69.5)   0.523        Chi-squared     0.072
                                                       1                       194 (27.8)   155 (27.2)    39 (30.5)
Hypertension, n (%)                                    0                   0   265 (38.0)   216 (37.9)    49 (38.3)   1.000        Chi-squared     0.008
                                                       1                       433 (62.0)   354 (62.1)    79 (61.7)
BMI, mean (SD)                                                             0   28.7 (6.5)   28.7 (6.5)   28.8 (6.6)   0.919  Two Sample T-test     0.010
HFrEF, n (%)                                           0                   0   395 (56.6)   330 (57.9)    65 (50.8)   0.171        Chi-squared     0.143
                                                       1                       303 (43.4)   240 (42.1)    63 (49.2)
STEMI, n (%)                                           0                   0   384 (55.0)   321 (56.3)    63 (49.2)   0.174        Chi-squared     0.143
                                                       1                       314 (45.0)   249 (43.7)    65 (50.8)
ESSI score, n (%)                                      0                   0   483 (69.2)   423 (74.2)    60 (46.9)  <0.001        Chi-squared     0.583
                                                       1                       215 (30.8)   147 (25.8)    68 (53.1)

In [108]:
for outcome in colsOutcomes3m:
    print('3 Months, Outcome = ' + outcome)
    table = TableOne(data3m, columns=cols3m, pval = True, 
                       groupby = [outcome], htest_name=True, smd=True)
    filename = outcome + "_3m_table1.csv"
    #removing backslash from strings
    filename = filename.replace("/","-")
    table.to_csv(filename, index=False)
    display(table)

3 Months, Outcome = 3M New Depression Diagnosis

                                                           Grouped by 3M New Depression Diagnosis
                                                                                           Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                           463          428           35
Age, mean (SD)                                                                                   0  67.4 (12.3)  67.4 (12.5)  66.6 (10.7)   0.651  Two Sample T-test        -0.075
Race, n (%)                                            0                                         0   426 (92.0)   393 (91.8)    33 (94.3)   1.000     Fisher's exact         0.097
                                                       1                                               37 (8.0)     35 (8.2)      2 (5.7)
Indigenous, n (%)                                      0                                         0   450 (97.2)   416 (97.2)    34 (97.1)   1.000     Fisher's exact         0.003
                                                       1                                               13 (2.8)     12 (2.8)      1 (2.9)
Gender Identity, n (%)                                 0                                         0   462 (99.8)   427 (99.8)   35 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                1 (0.2)      1 (0.2)
Highschool Education, n (%)                            0                                         0   422 (91.1)   393 (91.8)    29 (82.9)   0.111     Fisher's exact         0.272
                                                       1                                               41 (8.9)     35 (8.2)     6 (17.1)
Post- Secondary Education, n (%)                       0                                         0   277 (59.8)   257 (60.0)    20 (57.1)   0.875        Chi-squared         0.059
                                                       1                                             186 (40.2)   171 (40.0)    15 (42.9)
Employment, n (%)                                      0                                         0   411 (88.8)   383 (89.5)    28 (80.0)   0.096     Fisher's exact         0.266
                                                       1                                              52 (11.2)    45 (10.5)     7 (20.0)
Household income before taxes, n (%)                   0.0                                       0   254 (54.9)   240 (56.1)    14 (40.0)   0.097        Chi-squared         0.326
                                                       1.0                                           209 (45.1)   188 (43.9)    21 (60.0)
Marital status, n (%)                                  0                                         0   239 (51.6)   225 (52.6)    14 (40.0)   0.210        Chi-squared         0.254
                                                       1                                             224 (48.4)   203 (47.4)    21 (60.0)
Living situation, n (%)                                0                                         0   457 (98.7)   423 (98.8)    34 (97.1)   0.378     Fisher's exact         0.120
                                                       1                                                6 (1.3)      5 (1.2)      1 (2.9)
Pack years, mean (SD)                                                                            0  31.7 (71.0)  32.9 (73.5)  17.4 (21.2)   0.003  Two Sample T-test        -0.287
Alcohol use - average number of drinks/week, mean (SD)                                           0    1.6 (3.6)    1.7 (3.7)    1.0 (2.1)   0.062  Two Sample T-test        -0.251
Substance Use Disorder, n (%)                          0                                         0   458 (98.9)   424 (99.1)    34 (97.1)   0.326     Fisher's exact         0.141
                                                       1                                                5 (1.1)      4 (0.9)      1 (2.9)
Depression, n (%)                                      0                                         0   303 (65.4)   300 (70.1)      3 (8.6)  <0.001        Chi-squared         1.621
                                                       1                                             160 (34.6)   128 (29.9)    32 (91.4)
Anxiety, n (%)                                         0                                         0   317 (68.5)   308 (72.0)     9 (25.7)  <0.001        Chi-squared         1.044
                                                       1                                             146 (31.5)   120 (28.0)    26 (74.3)
Health Anxiety, n (%)                                  0                                         0   290 (62.6)   274 (64.0)    16 (45.7)   0.049        Chi-squared         0.374
                                                       1                                             173 (37.4)   154 (36.0)    19 (54.3)
Delay to Hospital, n (%)                               0                                         0   233 (50.3)   216 (50.5)    17 (48.6)   0.968        Chi-squared         0.038
                                                       1                                             230 (49.7)   212 (49.5)    18 (51.4)
Personal Stressors, n (%)                              0                                         0   240 (51.8)   228 (53.3)    12 (34.3)   0.047        Chi-squared         0.390
                                                       1                                             223 (48.2)   200 (46.7)    23 (65.7)
Menopause, n (%)                                       0                                         0    94 (20.3)    88 (20.6)     6 (17.1)   0.791        Chi-squared         0.087
                                                       1                                             369 (79.7)   340 (79.4)    29 (82.9)
Complicated Pregnancy, n (%)                           0                                         0   332 (71.7)   311 (72.7)    21 (60.0)   0.160        Chi-squared         0.270
                                                       1                                             131 (28.3)   117 (27.3)    14 (40.0)
Stroke History, n (%)                                  0                                         0   416 (89.8)   384 (89.7)    32 (91.4)   1.000     Fisher's exact         0.059
                                                       1                                              47 (10.2)    44 (10.3)      3 (8.6)
MI History, n (%)                                      0                                         0   378 (81.6)   350 (81.8)    28 (80.0)   0.973        Chi-squared         0.045
                                                       1                                              85 (18.4)    78 (18.2)     7 (20.0)
CABG/Stent History, n (%)                              0                                         0   389 (84.0)   360 (84.1)    29 (82.9)   1.000        Chi-squared         0.034
                                                       1                                              74 (16.0)    68 (15.9)     6 (17.1)
High cholesterol, n (%)                                0                                         0   190 (41.0)   178 (41.6)    12 (34.3)   0.506        Chi-squared         0.151
                                                       1                                             273 (59.0)   250 (58.4)    23 (65.7)
Diabetes, n (%)                                        0                                         0   341 (73.7)   312 (72.9)    29 (82.9)   0.277        Chi-squared         0.242
                                                       1                                             122 (26.3)   116 (27.1)     6 (17.1)
Hypertension, n (%)                                    0                                         0   184 (39.7)   171 (40.0)    13 (37.1)   0.883        Chi-squared         0.058
                                                       1                                             279 (60.3)   257 (60.0)    22 (62.9)
BMI, mean (SD)                                                                                   0   28.7 (6.5)   28.6 (6.3)   30.1 (8.2)   0.294  Two Sample T-test         0.207
HFrEF, n (%)                                           0                                         0   270 (58.3)   252 (58.9)    18 (51.4)   0.496        Chi-squared         0.150
                                                       1                                             193 (41.7)   176 (41.1)    17 (48.6)
STEMI, n (%)                                           0                                         0   254 (54.9)   233 (54.4)    21 (60.0)   0.646        Chi-squared         0.113
                                                       1                                             209 (45.1)   195 (45.6)    14 (40.0)
ESSI score, n (%)                                      0                                         0   319 (68.9)   301 (70.3)    18 (51.4)   0.033        Chi-squared         0.395
                                                       1                                             144 (31.1)   127 (29.7)    17 (48.6)
HADS-A, n (%)                                          0                                         0   307 (66.3)   291 (68.0)    16 (45.7)   0.013        Chi-squared         0.462
                                                       1                                             156 (33.7)   137 (32.0)    19 (54.3)
HADS-D, n (%)                                          0                                         0   376 (81.2)   354 (82.7)    22 (62.9)   0.008        Chi-squared         0.458
                                                       1                                              87 (18.8)    74 (17.3)    13 (37.1)

3 Months, Outcome = 3M New Anxiety Diagnosis

                                                           Grouped by 3M New Anxiety Diagnosis
                                                                                        Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                        463          425           38
Age, mean (SD)                                                                                0  67.4 (12.3)  67.4 (12.5)  67.0 (10.3)   0.806  Two Sample T-test        -0.038
Race, n (%)                                            0                                      0   426 (92.0)   391 (92.0)    35 (92.1)   1.000     Fisher's exact         0.004
                                                       1                                            37 (8.0)     34 (8.0)      3 (7.9)
Indigenous, n (%)                                      0                                      0   450 (97.2)   414 (97.4)    36 (94.7)   0.290     Fisher's exact         0.138
                                                       1                                            13 (2.8)     11 (2.6)      2 (5.3)
Gender Identity, n (%)                                 0                                      0   462 (99.8)   424 (99.8)   38 (100.0)   1.000     Fisher's exact           nan
                                                       1                                             1 (0.2)      1 (0.2)
Highschool Education, n (%)                            0                                      0   422 (91.1)   387 (91.1)    35 (92.1)   1.000     Fisher's exact         0.038
                                                       1                                            41 (8.9)     38 (8.9)      3 (7.9)
Post- Secondary Education, n (%)                       0                                      0   277 (59.8)   251 (59.1)    26 (68.4)   0.339        Chi-squared         0.196
                                                       1                                          186 (40.2)   174 (40.9)    12 (31.6)
Employment, n (%)                                      0                                      0   411 (88.8)   379 (89.2)    32 (84.2)   0.417     Fisher's exact         0.147
                                                       1                                           52 (11.2)    46 (10.8)     6 (15.8)
Household income before taxes, n (%)                   0.0                                    0   254 (54.9)   236 (55.5)    18 (47.4)   0.425        Chi-squared         0.164
                                                       1.0                                        209 (45.1)   189 (44.5)    20 (52.6)
Marital status, n (%)                                  0                                      0   239 (51.6)   222 (52.2)    17 (44.7)   0.474        Chi-squared         0.150
                                                       1                                          224 (48.4)   203 (47.8)    21 (55.3)
Living situation, n (%)                                0                                      0   457 (98.7)   420 (98.8)    37 (97.4)   0.404     Fisher's exact         0.107
                                                       1                                             6 (1.3)      5 (1.2)      1 (2.6)
Pack years, mean (SD)                                                                         0  31.7 (71.0)  31.7 (71.8)  32.1 (62.3)   0.967  Two Sample T-test         0.007
Alcohol use - average number of drinks/week, mean (SD)                                        0    1.6 (3.6)    1.7 (3.7)    1.3 (2.4)   0.425  Two Sample T-test        -0.112
Substance Use Disorder, n (%)                          0                                      0   458 (98.9)   421 (99.1)    37 (97.4)   0.350     Fisher's exact         0.128
                                                       1                                             5 (1.1)      4 (0.9)      1 (2.6)
Depression, n (%)                                      0                                      0   303 (65.4)   288 (67.8)    15 (39.5)   0.001        Chi-squared         0.592
                                                       1                                          160 (34.6)   137 (32.2)    23 (60.5)
Anxiety, n (%)                                         0                                      0   317 (68.5)   302 (71.1)    15 (39.5)  <0.001        Chi-squared         0.670
                                                       1                                          146 (31.5)   123 (28.9)    23 (60.5)
Health Anxiety, n (%)                                  0                                      0   290 (62.6)   266 (62.6)    24 (63.2)   1.000        Chi-squared         0.012
                                                       1                                          173 (37.4)   159 (37.4)    14 (36.8)
Delay to Hospital, n (%)                               0                                      0   233 (50.3)   215 (50.6)    18 (47.4)   0.833        Chi-squared         0.064
                                                       1                                          230 (49.7)   210 (49.4)    20 (52.6)
Personal Stressors, n (%)                              0                                      0   240 (51.8)   226 (53.2)    14 (36.8)   0.078        Chi-squared         0.333
                                                       1                                          223 (48.2)   199 (46.8)    24 (63.2)
Menopause, n (%)                                       0                                      0    94 (20.3)    88 (20.7)     6 (15.8)   0.609        Chi-squared         0.128
                                                       1                                          369 (79.7)   337 (79.3)    32 (84.2)
Complicated Pregnancy, n (%)                           0                                      0   332 (71.7)   307 (72.2)    25 (65.8)   0.511        Chi-squared         0.140
                                                       1                                          131 (28.3)   118 (27.8)    13 (34.2)
Stroke History, n (%)                                  0                                      0   416 (89.8)   383 (90.1)    33 (86.8)   0.571     Fisher's exact         0.103
                                                       1                                           47 (10.2)     42 (9.9)     5 (13.2)
MI History, n (%)                                      0                                      0   378 (81.6)   344 (80.9)    34 (89.5)   0.279        Chi-squared         0.242
                                                       1                                           85 (18.4)    81 (19.1)     4 (10.5)
CABG/Stent History, n (%)                              0                                      0   389 (84.0)   354 (83.3)    35 (92.1)   0.234        Chi-squared         0.271
                                                       1                                           74 (16.0)    71 (16.7)      3 (7.9)
High cholesterol, n (%)                                0                                      0   190 (41.0)   177 (41.6)    13 (34.2)   0.471        Chi-squared         0.154
                                                       1                                          273 (59.0)   248 (58.4)    25 (65.8)
Diabetes, n (%)                                        0                                      0   341 (73.7)   308 (72.5)    33 (86.8)   0.083        Chi-squared         0.363
                                                       1                                          122 (26.3)   117 (27.5)     5 (13.2)
Hypertension, n (%)                                    0                                      0   184 (39.7)   169 (39.8)    15 (39.5)   1.000        Chi-squared         0.006
                                                       1                                          279 (60.3)   256 (60.2)    23 (60.5)
BMI, mean (SD)                                                                                0   28.7 (6.5)   28.7 (6.4)   28.1 (6.9)   0.606  Two Sample T-test        -0.091
HFrEF, n (%)                                           0                                      0   270 (58.3)   248 (58.4)    22 (57.9)   1.000        Chi-squared         0.009
                                                       1                                          193 (41.7)   177 (41.6)    16 (42.1)
STEMI, n (%)                                           0                                      0   254 (54.9)   233 (54.8)    21 (55.3)   1.000        Chi-squared         0.009
                                                       1                                          209 (45.1)   192 (45.2)    17 (44.7)
ESSI score, n (%)                                      0                                      0   319 (68.9)   299 (70.4)    20 (52.6)   0.038        Chi-squared         0.370
                                                       1                                          144 (31.1)   126 (29.6)    18 (47.4)
HADS-A, n (%)                                          0                                      0   307 (66.3)   282 (66.4)    25 (65.8)   1.000        Chi-squared         0.012
                                                       1                                          156 (33.7)   143 (33.6)    13 (34.2)
HADS-D, n (%)                                          0                                      0   376 (81.2)   348 (81.9)    28 (73.7)   0.306        Chi-squared         0.198
                                                       1                                           87 (18.8)    77 (18.1)    10 (26.3)

3 Months, Outcome = 3M New Substance Use Disorder

                                                           Grouped by 3M New Substance Use Disorder
                                                                                            Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                            463          461            2
Age, mean (SD)                                                                                    0  67.4 (12.3)  67.4 (12.4)   73.0 (5.7)   0.389  Two Sample T-test         0.588
Race, n (%)                                            0                                          0   426 (92.0)   424 (92.0)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                37 (8.0)     37 (8.0)
Indigenous, n (%)                                      0                                          0   450 (97.2)   448 (97.2)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                13 (2.8)     13 (2.8)
Gender Identity, n (%)                                 0                                          0   462 (99.8)   460 (99.8)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                 1 (0.2)      1 (0.2)
Highschool Education, n (%)                            0                                          0   422 (91.1)   420 (91.1)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                41 (8.9)     41 (8.9)
Post- Secondary Education, n (%)                       0                                          0   277 (59.8)   276 (59.9)     1 (50.0)   1.000     Fisher's exact         0.199
                                                       1                                              186 (40.2)   185 (40.1)     1 (50.0)
Employment, n (%)                                      0                                          0   411 (88.8)   409 (88.7)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                               52 (11.2)    52 (11.3)
Household income before taxes, n (%)                   0.0                                        0   254 (54.9)   253 (54.9)     1 (50.0)   1.000     Fisher's exact         0.098
                                                       1.0                                            209 (45.1)   208 (45.1)     1 (50.0)
Marital status, n (%)                                  0                                          0   239 (51.6)   238 (51.6)     1 (50.0)   1.000     Fisher's exact         0.033
                                                       1                                              224 (48.4)   223 (48.4)     1 (50.0)
Living situation, n (%)                                0                                          0   457 (98.7)   455 (98.7)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                 6 (1.3)      6 (1.3)
Pack years, mean (SD)                                                                             0  31.7 (71.0)  31.7 (71.1)  30.0 (35.4)   0.957  Two Sample T-test        -0.030
Alcohol use - average number of drinks/week, mean (SD)                                            0    1.6 (3.6)    1.6 (3.6)    1.5 (2.1)   0.937  Two Sample T-test        -0.051
Substance Use Disorder, n (%)                          0                                          0   458 (98.9)   456 (98.9)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                 5 (1.1)      5 (1.1)
Depression, n (%)                                      0                                          0   303 (65.4)   303 (65.7)                0.119     Fisher's exact         1.958
                                                       1                                              160 (34.6)   158 (34.3)    2 (100.0)
Anxiety, n (%)                                         0                                          0   317 (68.5)   317 (68.8)                0.099     Fisher's exact         2.098
                                                       1                                              146 (31.5)   144 (31.2)    2 (100.0)
Health Anxiety, n (%)                                  0                                          0   290 (62.6)   288 (62.5)    2 (100.0)   0.531     Fisher's exact           nan
                                                       1                                              173 (37.4)   173 (37.5)
Delay to Hospital, n (%)                               0                                          0   233 (50.3)   233 (50.5)                0.246     Fisher's exact         1.430
                                                       1                                              230 (49.7)   228 (49.5)    2 (100.0)
Personal Stressors, n (%)                              0                                          0   240 (51.8)   239 (51.8)     1 (50.0)   1.000     Fisher's exact         0.037
                                                       1                                              223 (48.2)   222 (48.2)     1 (50.0)
Menopause, n (%)                                       0                                          0    94 (20.3)    94 (20.4)                1.000     Fisher's exact         0.716
                                                       1                                              369 (79.7)   367 (79.6)    2 (100.0)
Complicated Pregnancy, n (%)                           0                                          0   332 (71.7)   331 (71.8)     1 (50.0)   0.486     Fisher's exact         0.458
                                                       1                                              131 (28.3)   130 (28.2)     1 (50.0)
Stroke History, n (%)                                  0                                          0   416 (89.8)   415 (90.0)     1 (50.0)   0.193     Fisher's exact         0.971
                                                       1                                               47 (10.2)    46 (10.0)     1 (50.0)
MI History, n (%)                                      0                                          0   378 (81.6)   377 (81.8)     1 (50.0)   0.334     Fisher's exact         0.711
                                                       1                                               85 (18.4)    84 (18.2)     1 (50.0)
CABG/Stent History, n (%)                              0                                          0   389 (84.0)   388 (84.2)     1 (50.0)   0.294     Fisher's exact         0.780
                                                       1                                               74 (16.0)    73 (15.8)     1 (50.0)
High cholesterol, n (%)                                0                                          0   190 (41.0)   190 (41.2)                0.515     Fisher's exact         1.184
                                                       1                                              273 (59.0)   271 (58.8)    2 (100.0)
Diabetes, n (%)                                        0                                          0   341 (73.7)   339 (73.5)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                              122 (26.3)   122 (26.5)
Hypertension, n (%)                                    0                                          0   184 (39.7)   183 (39.7)     1 (50.0)   1.000     Fisher's exact         0.208
                                                       1                                              279 (60.3)   278 (60.3)     1 (50.0)
BMI, mean (SD)                                                                                    0   28.7 (6.5)   28.7 (6.5)   25.1 (4.5)   0.462  Two Sample T-test        -0.636
HFrEF, n (%)                                           0                                          0   270 (58.3)   269 (58.4)     1 (50.0)   1.000     Fisher's exact         0.168
                                                       1                                              193 (41.7)   192 (41.6)     1 (50.0)
STEMI, n (%)                                           0                                          0   254 (54.9)   253 (54.9)     1 (50.0)   1.000     Fisher's exact         0.098
                                                       1                                              209 (45.1)   208 (45.1)     1 (50.0)
ESSI score, n (%)                                      0                                          0   319 (68.9)   318 (69.0)     1 (50.0)   0.526     Fisher's exact         0.394
                                                       1                                              144 (31.1)   143 (31.0)     1 (50.0)
HADS-A, n (%)                                          0                                          0   307 (66.3)   306 (66.4)     1 (50.0)   1.000     Fisher's exact         0.337
                                                       1                                              156 (33.7)   155 (33.6)     1 (50.0)
HADS-D, n (%)                                          0                                          0   376 (81.2)   374 (81.1)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                               87 (18.8)    87 (18.9)

3 Months, Outcome = 3M New Stroke

                                                           Grouped by 3M New Stroke
                                                                            Missing      Overall          0.0         1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                            463          454           9
Age, mean (SD)                                                                    0  67.4 (12.3)  67.3 (12.4)  69.0 (9.0)   0.600  Two Sample T-test         0.153
Race, n (%)                                            0                          0   426 (92.0)   418 (92.1)    8 (88.9)   0.531     Fisher's exact         0.109
                                                       1                                37 (8.0)     36 (7.9)    1 (11.1)
Indigenous, n (%)                                      0                          0   450 (97.2)   441 (97.1)   9 (100.0)   1.000     Fisher's exact           nan
                                                       1                                13 (2.8)     13 (2.9)
Gender Identity, n (%)                                 0                          0   462 (99.8)   453 (99.8)   9 (100.0)   1.000     Fisher's exact           nan
                                                       1                                 1 (0.2)      1 (0.2)
Highschool Education, n (%)                            0                          0   422 (91.1)   413 (91.0)   9 (100.0)   1.000     Fisher's exact           nan
                                                       1                                41 (8.9)     41 (9.0)
Post- Secondary Education, n (%)                       0                          0   277 (59.8)   269 (59.3)    8 (88.9)   0.092     Fisher's exact         0.719
                                                       1                              186 (40.2)   185 (40.7)    1 (11.1)
Employment, n (%)                                      0                          0   411 (88.8)   402 (88.5)   9 (100.0)   0.606     Fisher's exact           nan
                                                       1                               52 (11.2)    52 (11.5)
Household income before taxes, n (%)                   0.0                        0   254 (54.9)   248 (54.6)    6 (66.7)   0.522     Fisher's exact         0.248
                                                       1.0                            209 (45.1)   206 (45.4)    3 (33.3)
Marital status, n (%)                                  0                          0   239 (51.6)   235 (51.8)    4 (44.4)   0.745     Fisher's exact         0.147
                                                       1                              224 (48.4)   219 (48.2)    5 (55.6)
Living situation, n (%)                                0                          0   457 (98.7)   448 (98.7)   9 (100.0)   1.000     Fisher's exact           nan
                                                       1                                 6 (1.3)      6 (1.3)
Pack years, mean (SD)                                                             0  31.7 (71.0)  32.2 (71.6)  6.6 (12.8)  <0.001  Two Sample T-test        -0.499
Alcohol use - average number of drinks/week, mean (SD)                            0    1.6 (3.6)    1.6 (3.6)   2.1 (2.7)   0.615  Two Sample T-test         0.149
Substance Use Disorder, n (%)                          0                          0   458 (98.9)   449 (98.9)   9 (100.0)   1.000     Fisher's exact           nan
                                                       1                                 5 (1.1)      5 (1.1)
Depression, n (%)                                      0                          0   303 (65.4)   295 (65.0)    8 (88.9)   0.173     Fisher's exact         0.592
                                                       1                              160 (34.6)   159 (35.0)    1 (11.1)
Anxiety, n (%)                                         0                          0   317 (68.5)   310 (68.3)    7 (77.8)   0.726     Fisher's exact         0.215
                                                       1                              146 (31.5)   144 (31.7)    2 (22.2)
Health Anxiety, n (%)                                  0                          0   290 (62.6)   282 (62.1)    8 (88.9)   0.163     Fisher's exact         0.655
                                                       1                              173 (37.4)   172 (37.9)    1 (11.1)
Delay to Hospital, n (%)                               0                          0   233 (50.3)   226 (49.8)    7 (77.8)   0.175     Fisher's exact         0.609
                                                       1                              230 (49.7)   228 (50.2)    2 (22.2)
Personal Stressors, n (%)                              0                          0   240 (51.8)   232 (51.1)    8 (88.9)   0.038     Fisher's exact         0.905
                                                       1                              223 (48.2)   222 (48.9)    1 (11.1)
Menopause, n (%)                                       0                          0    94 (20.3)    91 (20.0)    3 (33.3)   0.396     Fisher's exact         0.304
                                                       1                              369 (79.7)   363 (80.0)    6 (66.7)
Complicated Pregnancy, n (%)                           0                          0   332 (71.7)   325 (71.6)    7 (77.8)   1.000     Fisher's exact         0.143
                                                       1                              131 (28.3)   129 (28.4)    2 (22.2)
Stroke History, n (%)                                  0                          0   416 (89.8)   408 (89.9)    8 (88.9)   1.000     Fisher's exact         0.032
                                                       1                               47 (10.2)    46 (10.1)    1 (11.1)
MI History, n (%)                                      0                          0   378 (81.6)   371 (81.7)    7 (77.8)   0.673     Fisher's exact         0.098
                                                       1                               85 (18.4)    83 (18.3)    2 (22.2)
CABG/Stent History, n (%)                              0                          0   389 (84.0)   382 (84.1)    7 (77.8)   0.641     Fisher's exact         0.163
                                                       1                               74 (16.0)    72 (15.9)    2 (22.2)
High cholesterol, n (%)                                0                          0   190 (41.0)   188 (41.4)    2 (22.2)   0.319     Fisher's exact         0.421
                                                       1                              273 (59.0)   266 (58.6)    7 (77.8)
Diabetes, n (%)                                        0                          0   341 (73.7)   336 (74.0)    5 (55.6)   0.252     Fisher's exact         0.394
                                                       1                              122 (26.3)   118 (26.0)    4 (44.4)
Hypertension, n (%)                                    0                          0   184 (39.7)   180 (39.6)    4 (44.4)   0.746     Fisher's exact         0.097
                                                       1                              279 (60.3)   274 (60.4)    5 (55.6)
BMI, mean (SD)                                                                    0   28.7 (6.5)   28.7 (6.5)  27.5 (4.4)   0.455  Two Sample T-test        -0.212
HFrEF, n (%)                                           0                          0   270 (58.3)   262 (57.7)    8 (88.9)   0.087     Fisher's exact         0.753
                                                       1                              193 (41.7)   192 (42.3)    1 (11.1)
STEMI, n (%)                                           0                          0   254 (54.9)   248 (54.6)    6 (66.7)   0.522     Fisher's exact         0.248
                                                       1                              209 (45.1)   206 (45.4)    3 (33.3)
ESSI score, n (%)                                      0                          0   319 (68.9)   314 (69.2)    5 (55.6)   0.469     Fisher's exact         0.284
                                                       1                              144 (31.1)   140 (30.8)    4 (44.4)
HADS-A, n (%)                                          0                          0   307 (66.3)   300 (66.1)    7 (77.8)   0.724     Fisher's exact         0.263
                                                       1                              156 (33.7)   154 (33.9)    2 (22.2)
HADS-D, n (%)                                          0                          0   376 (81.2)   368 (81.1)    8 (88.9)   1.000     Fisher's exact         0.220
                                                       1                               87 (18.8)    86 (18.9)    1 (11.1)

3 Months, Outcome = 3M New MI

                                                           Grouped by 3M New MI
                                                                        Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                        463          450           13
Age, mean (SD)                                                                0  67.4 (12.3)  67.4 (12.3)  67.2 (13.5)   0.953  Two Sample T-test        -0.018
Race, n (%)                                            0                      0   426 (92.0)   417 (92.7)     9 (69.2)   0.015     Fisher's exact         0.625
                                                       1                            37 (8.0)     33 (7.3)     4 (30.8)
Indigenous, n (%)                                      0                      0   450 (97.2)   438 (97.3)    12 (92.3)   0.313     Fisher's exact         0.228
                                                       1                            13 (2.8)     12 (2.7)      1 (7.7)
Gender Identity, n (%)                                 0                      0   462 (99.8)   449 (99.8)   13 (100.0)   1.000     Fisher's exact           nan
                                                       1                             1 (0.2)      1 (0.2)
Highschool Education, n (%)                            0                      0   422 (91.1)   410 (91.1)    12 (92.3)   1.000     Fisher's exact         0.043
                                                       1                            41 (8.9)     40 (8.9)      1 (7.7)
Post- Secondary Education, n (%)                       0                      0   277 (59.8)   268 (59.6)     9 (69.2)   0.678        Chi-squared         0.203
                                                       1                          186 (40.2)   182 (40.4)     4 (30.8)
Employment, n (%)                                      0                      0   411 (88.8)   401 (89.1)    10 (76.9)   0.170     Fisher's exact         0.329
                                                       1                           52 (11.2)    49 (10.9)     3 (23.1)
Household income before taxes, n (%)                   0.0                    0   254 (54.9)   248 (55.1)     6 (46.2)   0.721        Chi-squared         0.180
                                                       1.0                        209 (45.1)   202 (44.9)     7 (53.8)
Marital status, n (%)                                  0                      0   239 (51.6)   233 (51.8)     6 (46.2)   0.906        Chi-squared         0.113
                                                       1                          224 (48.4)   217 (48.2)     7 (53.8)
Living situation, n (%)                                0                      0   457 (98.7)   444 (98.7)   13 (100.0)   1.000     Fisher's exact           nan
                                                       1                             6 (1.3)      6 (1.3)
Pack years, mean (SD)                                                         0  31.7 (71.0)  32.4 (71.9)   5.9 (11.6)  <0.001  Two Sample T-test        -0.515
Alcohol use - average number of drinks/week, mean (SD)                        0    1.6 (3.6)    1.7 (3.6)    0.5 (1.0)   0.002  Two Sample T-test        -0.430
Substance Use Disorder, n (%)                          0                      0   458 (98.9)   445 (98.9)   13 (100.0)   1.000     Fisher's exact           nan
                                                       1                             5 (1.1)      5 (1.1)
Depression, n (%)                                      0                      0   303 (65.4)   294 (65.3)     9 (69.2)   1.000     Fisher's exact         0.083
                                                       1                          160 (34.6)   156 (34.7)     4 (30.8)
Anxiety, n (%)                                         0                      0   317 (68.5)   312 (69.3)     5 (38.5)   0.030     Fisher's exact         0.651
                                                       1                          146 (31.5)   138 (30.7)     8 (61.5)
Health Anxiety, n (%)                                  0                      0   290 (62.6)   279 (62.0)    11 (84.6)   0.145     Fisher's exact         0.529
                                                       1                          173 (37.4)   171 (38.0)     2 (15.4)
Delay to Hospital, n (%)                               0                      0   233 (50.3)   228 (50.7)     5 (38.5)   0.558        Chi-squared         0.247
                                                       1                          230 (49.7)   222 (49.3)     8 (61.5)
Personal Stressors, n (%)                              0                      0   240 (51.8)   229 (50.9)    11 (84.6)   0.034        Chi-squared         0.774
                                                       1                          223 (48.2)   221 (49.1)     2 (15.4)
Menopause, n (%)                                       0                      0    94 (20.3)    90 (20.0)     4 (30.8)   0.310     Fisher's exact         0.249
                                                       1                          369 (79.7)   360 (80.0)     9 (69.2)
Complicated Pregnancy, n (%)                           0                      0   332 (71.7)   320 (71.1)    12 (92.3)   0.122     Fisher's exact         0.570
                                                       1                          131 (28.3)   130 (28.9)      1 (7.7)
Stroke History, n (%)                                  0                      0   416 (89.8)   405 (90.0)    11 (84.6)   0.631     Fisher's exact         0.162
                                                       1                           47 (10.2)    45 (10.0)     2 (15.4)
MI History, n (%)                                      0                      0   378 (81.6)   370 (82.2)     8 (61.5)   0.070     Fisher's exact         0.473
                                                       1                           85 (18.4)    80 (17.8)     5 (38.5)
CABG/Stent History, n (%)                              0                      0   389 (84.0)   381 (84.7)     8 (61.5)   0.041     Fisher's exact         0.540
                                                       1                           74 (16.0)    69 (15.3)     5 (38.5)
High cholesterol, n (%)                                0                      0   190 (41.0)   183 (40.7)     7 (53.8)   0.505        Chi-squared         0.266
                                                       1                          273 (59.0)   267 (59.3)     6 (46.2)
Diabetes, n (%)                                        0                      0   341 (73.7)   333 (74.0)     8 (61.5)   0.341     Fisher's exact         0.269
                                                       1                          122 (26.3)   117 (26.0)     5 (38.5)
Hypertension, n (%)                                    0                      0   184 (39.7)   178 (39.6)     6 (46.2)   0.848        Chi-squared         0.134
                                                       1                          279 (60.3)   272 (60.4)     7 (53.8)
BMI, mean (SD)                                                                0   28.7 (6.5)   28.6 (6.5)   30.0 (5.9)   0.428  Two Sample T-test         0.219
HFrEF, n (%)                                           0                      0   270 (58.3)   264 (58.7)     6 (46.2)   0.537        Chi-squared         0.253
                                                       1                          193 (41.7)   186 (41.3)     7 (53.8)
STEMI, n (%)                                           0                      0   254 (54.9)   244 (54.2)    10 (76.9)   0.181        Chi-squared         0.492
                                                       1                          209 (45.1)   206 (45.8)     3 (23.1)
ESSI score, n (%)                                      0                      0   319 (68.9)   309 (68.7)    10 (76.9)   0.763     Fisher's exact         0.186
                                                       1                          144 (31.1)   141 (31.3)     3 (23.1)
HADS-A, n (%)                                          0                      0   307 (66.3)   298 (66.2)     9 (69.2)   1.000     Fisher's exact         0.064
                                                       1                          156 (33.7)   152 (33.8)     4 (30.8)
HADS-D, n (%)                                          0                      0   376 (81.2)   364 (80.9)    12 (92.3)   0.478     Fisher's exact         0.340
                                                       1                           87 (18.8)    86 (19.1)      1 (7.7)

3 Months, Outcome = 3M New CABG/Stent

                                                           Grouped by 3M New CABG/Stent
                                                                                Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                463          424           39
Age, mean (SD)                                                                        0  67.4 (12.3)  67.3 (12.5)  68.2 (10.6)   0.629  Two Sample T-test         0.076
Race, n (%)                                            0                              0   426 (92.0)   394 (92.9)    32 (82.1)   0.027     Fisher's exact         0.333
                                                       1                                    37 (8.0)     30 (7.1)     7 (17.9)
Indigenous, n (%)                                      0                              0   450 (97.2)   412 (97.2)    38 (97.4)   1.000     Fisher's exact         0.016
                                                       1                                    13 (2.8)     12 (2.8)      1 (2.6)
Gender Identity, n (%)                                 0                              0   462 (99.8)   423 (99.8)   39 (100.0)   1.000     Fisher's exact           nan
                                                       1                                     1 (0.2)      1 (0.2)
Highschool Education, n (%)                            0                              0   422 (91.1)   392 (92.5)    30 (76.9)   0.004     Fisher's exact         0.442
                                                       1                                    41 (8.9)     32 (7.5)     9 (23.1)
Post- Secondary Education, n (%)                       0                              0   277 (59.8)   257 (60.6)    20 (51.3)   0.334        Chi-squared         0.189
                                                       1                                  186 (40.2)   167 (39.4)    19 (48.7)
Employment, n (%)                                      0                              0   411 (88.8)   376 (88.7)    35 (89.7)   1.000     Fisher's exact         0.034
                                                       1                                   52 (11.2)    48 (11.3)     4 (10.3)
Household income before taxes, n (%)                   0.0                            0   254 (54.9)   229 (54.0)    25 (64.1)   0.296        Chi-squared         0.206
                                                       1.0                                209 (45.1)   195 (46.0)    14 (35.9)
Marital status, n (%)                                  0                              0   239 (51.6)   223 (52.6)    16 (41.0)   0.224        Chi-squared         0.233
                                                       1                                  224 (48.4)   201 (47.4)    23 (59.0)
Living situation, n (%)                                0                              0   457 (98.7)   418 (98.6)   39 (100.0)   1.000     Fisher's exact           nan
                                                       1                                     6 (1.3)      6 (1.4)
Pack years, mean (SD)                                                                 0  31.7 (71.0)  33.7 (73.7)  10.2 (16.2)  <0.001  Two Sample T-test        -0.441
Alcohol use - average number of drinks/week, mean (SD)                                0    1.6 (3.6)    1.7 (3.7)    1.0 (2.5)   0.097  Two Sample T-test        -0.237
Substance Use Disorder, n (%)                          0                              0   458 (98.9)   419 (98.8)   39 (100.0)   1.000     Fisher's exact           nan
                                                       1                                     5 (1.1)      5 (1.2)
Depression, n (%)                                      0                              0   303 (65.4)   275 (64.9)    28 (71.8)   0.487        Chi-squared         0.150
                                                       1                                  160 (34.6)   149 (35.1)    11 (28.2)
Anxiety, n (%)                                         0                              0   317 (68.5)   294 (69.3)    23 (59.0)   0.249        Chi-squared         0.217
                                                       1                                  146 (31.5)   130 (30.7)    16 (41.0)
Health Anxiety, n (%)                                  0                              0   290 (62.6)   262 (61.8)    28 (71.8)   0.288        Chi-squared         0.214
                                                       1                                  173 (37.4)   162 (38.2)    11 (28.2)
Delay to Hospital, n (%)                               0                              0   233 (50.3)   221 (52.1)    12 (30.8)   0.017        Chi-squared         0.444
                                                       1                                  230 (49.7)   203 (47.9)    27 (69.2)
Personal Stressors, n (%)                              0                              0   240 (51.8)   219 (51.7)    21 (53.8)   0.924        Chi-squared         0.044
                                                       1                                  223 (48.2)   205 (48.3)    18 (46.2)
Menopause, n (%)                                       0                              0    94 (20.3)    88 (20.8)     6 (15.4)   0.555        Chi-squared         0.140
                                                       1                                  369 (79.7)   336 (79.2)    33 (84.6)
Complicated Pregnancy, n (%)                           0                              0   332 (71.7)   303 (71.5)    29 (74.4)   0.843        Chi-squared         0.065
                                                       1                                  131 (28.3)   121 (28.5)    10 (25.6)
Stroke History, n (%)                                  0                              0   416 (89.8)   382 (90.1)    34 (87.2)   0.577     Fisher's exact         0.092
                                                       1                                   47 (10.2)     42 (9.9)     5 (12.8)
MI History, n (%)                                      0                              0   378 (81.6)   348 (82.1)    30 (76.9)   0.562        Chi-squared         0.128
                                                       1                                   85 (18.4)    76 (17.9)     9 (23.1)
CABG/Stent History, n (%)                              0                              0   389 (84.0)   358 (84.4)    31 (79.5)   0.563        Chi-squared         0.129
                                                       1                                   74 (16.0)    66 (15.6)     8 (20.5)
High cholesterol, n (%)                                0                              0   190 (41.0)   176 (41.5)    14 (35.9)   0.609        Chi-squared         0.115
                                                       1                                  273 (59.0)   248 (58.5)    25 (64.1)
Diabetes, n (%)                                        0                              0   341 (73.7)   315 (74.3)    26 (66.7)   0.398        Chi-squared         0.168
                                                       1                                  122 (26.3)   109 (25.7)    13 (33.3)
Hypertension, n (%)                                    0                              0   184 (39.7)   172 (40.6)    12 (30.8)   0.305        Chi-squared         0.206
                                                       1                                  279 (60.3)   252 (59.4)    27 (69.2)
BMI, mean (SD)                                                                        0   28.7 (6.5)   28.6 (6.5)   29.4 (6.7)   0.460  Two Sample T-test         0.126
HFrEF, n (%)                                           0                              0   270 (58.3)   249 (58.7)    21 (53.8)   0.673        Chi-squared         0.099
                                                       1                                  193 (41.7)   175 (41.3)    18 (46.2)
STEMI, n (%)                                           0                              0   254 (54.9)   234 (55.2)    20 (51.3)   0.763        Chi-squared         0.078
                                                       1                                  209 (45.1)   190 (44.8)    19 (48.7)
ESSI score, n (%)                                      0                              0   319 (68.9)   293 (69.1)    26 (66.7)   0.893        Chi-squared         0.052
                                                       1                                  144 (31.1)   131 (30.9)    13 (33.3)
HADS-A, n (%)                                          0                              0   307 (66.3)   276 (65.1)    31 (79.5)   0.100        Chi-squared         0.326
                                                       1                                  156 (33.7)   148 (34.9)     8 (20.5)
HADS-D, n (%)                                          0                              0   376 (81.2)   347 (81.8)    29 (74.4)   0.352        Chi-squared         0.182
                                                       1                                   87 (18.8)    77 (18.2)    10 (25.6)

3 Months, Outcome = 3M Cardiac Rehab

                                                           Grouped by 3M Cardiac Rehab
                                                                               Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                               463          112          351
Age, mean (SD)                                                                       0  67.4 (12.3)  65.9 (11.0)  67.8 (12.7)   0.119  Two Sample T-test         0.164
Race, n (%)                                            0                             0   426 (92.0)   105 (93.8)   321 (91.5)   0.562        Chi-squared         0.088
                                                       1                                   37 (8.0)      7 (6.2)     30 (8.5)
Indigenous, n (%)                                      0                             0   450 (97.2)   110 (98.2)   340 (96.9)   0.743     Fisher's exact         0.087
                                                       1                                   13 (2.8)      2 (1.8)     11 (3.1)
Gender Identity, n (%)                                 0                             0   462 (99.8)   111 (99.1)  351 (100.0)   0.242     Fisher's exact           nan
                                                       1                                    1 (0.2)      1 (0.9)
Highschool Education, n (%)                            0                             0   422 (91.1)   108 (96.4)   314 (89.5)   0.038        Chi-squared         0.275
                                                       1                                   41 (8.9)      4 (3.6)    37 (10.5)
Post- Secondary Education, n (%)                       0                             0   277 (59.8)    79 (70.5)   198 (56.4)   0.011        Chi-squared         0.297
                                                       1                                 186 (40.2)    33 (29.5)   153 (43.6)
Employment, n (%)                                      0                             0   411 (88.8)   102 (91.1)   309 (88.0)   0.475        Chi-squared         0.099
                                                       1                                  52 (11.2)     10 (8.9)    42 (12.0)
Household income before taxes, n (%)                   0.0                           0   254 (54.9)    70 (62.5)   184 (52.4)   0.079        Chi-squared         0.205
                                                       1.0                               209 (45.1)    42 (37.5)   167 (47.6)
Marital status, n (%)                                  0                             0   239 (51.6)    65 (58.0)   174 (49.6)   0.147        Chi-squared         0.170
                                                       1                                 224 (48.4)    47 (42.0)   177 (50.4)
Living situation, n (%)                                0                             0   457 (98.7)   110 (98.2)   347 (98.9)   0.635     Fisher's exact         0.054
                                                       1                                    6 (1.3)      2 (1.8)      4 (1.1)
Pack years, mean (SD)                                                                0  31.7 (71.0)  43.7 (90.5)  27.9 (63.2)   0.087  Two Sample T-test        -0.203
Alcohol use - average number of drinks/week, mean (SD)                               0    1.6 (3.6)    2.4 (4.5)    1.4 (3.2)   0.043  Two Sample T-test        -0.241
Substance Use Disorder, n (%)                          0                             0   458 (98.9)   110 (98.2)   348 (99.1)   0.599     Fisher's exact         0.082
                                                       1                                    5 (1.1)      2 (1.8)      3 (0.9)
Depression, n (%)                                      0                             0   303 (65.4)    79 (70.5)   224 (63.8)   0.235        Chi-squared         0.143
                                                       1                                 160 (34.6)    33 (29.5)   127 (36.2)
Anxiety, n (%)                                         0                             0   317 (68.5)    85 (75.9)   232 (66.1)   0.068        Chi-squared         0.217
                                                       1                                 146 (31.5)    27 (24.1)   119 (33.9)
Health Anxiety, n (%)                                  0                             0   290 (62.6)    67 (59.8)   223 (63.5)   0.552        Chi-squared         0.076
                                                       1                                 173 (37.4)    45 (40.2)   128 (36.5)
Delay to Hospital, n (%)                               0                             0   233 (50.3)    65 (58.0)   168 (47.9)   0.077        Chi-squared         0.205
                                                       1                                 230 (49.7)    47 (42.0)   183 (52.1)
Personal Stressors, n (%)                              0                             0   240 (51.8)    52 (46.4)   188 (53.6)   0.228        Chi-squared         0.143
                                                       1                                 223 (48.2)    60 (53.6)   163 (46.4)
Menopause, n (%)                                       0                             0    94 (20.3)    20 (17.9)    74 (21.1)   0.546        Chi-squared         0.082
                                                       1                                 369 (79.7)    92 (82.1)   277 (78.9)
Complicated Pregnancy, n (%)                           0                             0   332 (71.7)    83 (74.1)   249 (70.9)   0.598        Chi-squared         0.071
                                                       1                                 131 (28.3)    29 (25.9)   102 (29.1)
Stroke History, n (%)                                  0                             0   416 (89.8)   102 (91.1)   314 (89.5)   0.755        Chi-squared         0.054
                                                       1                                  47 (10.2)     10 (8.9)    37 (10.5)
MI History, n (%)                                      0                             0   378 (81.6)    94 (83.9)   284 (80.9)   0.563        Chi-squared         0.079
                                                       1                                  85 (18.4)    18 (16.1)    67 (19.1)
CABG/Stent History, n (%)                              0                             0   389 (84.0)    96 (85.7)   293 (83.5)   0.678        Chi-squared         0.062
                                                       1                                  74 (16.0)    16 (14.3)    58 (16.5)
High cholesterol, n (%)                                0                             0   190 (41.0)    32 (28.6)   158 (45.0)   0.003        Chi-squared         0.346
                                                       1                                 273 (59.0)    80 (71.4)   193 (55.0)
Diabetes, n (%)                                        0                             0   341 (73.7)    80 (71.4)   261 (74.4)   0.624        Chi-squared         0.066
                                                       1                                 122 (26.3)    32 (28.6)    90 (25.6)
Hypertension, n (%)                                    0                             0   184 (39.7)    44 (39.3)   140 (39.9)   0.998        Chi-squared         0.012
                                                       1                                 279 (60.3)    68 (60.7)   211 (60.1)
BMI, mean (SD)                                                                       0   28.7 (6.5)   28.5 (6.1)   28.7 (6.6)   0.703  Two Sample T-test         0.041
HFrEF, n (%)                                           0                             0   270 (58.3)    54 (48.2)   216 (61.5)   0.017        Chi-squared         0.270
                                                       1                                 193 (41.7)    58 (51.8)   135 (38.5)
STEMI, n (%)                                           0                             0   254 (54.9)    50 (44.6)   204 (58.1)   0.017        Chi-squared         0.272
                                                       1                                 209 (45.1)    62 (55.4)   147 (41.9)
ESSI score, n (%)                                      0                             0   319 (68.9)    73 (65.2)   246 (70.1)   0.390        Chi-squared         0.105
                                                       1                                 144 (31.1)    39 (34.8)   105 (29.9)
HADS-A, n (%)                                          0                             0   307 (66.3)    75 (67.0)   232 (66.1)   0.957        Chi-squared         0.018
                                                       1                                 156 (33.7)    37 (33.0)   119 (33.9)
HADS-D, n (%)                                          0                             0   376 (81.2)    95 (84.8)   281 (80.1)   0.325        Chi-squared         0.125
                                                       1                                  87 (18.8)    17 (15.2)    70 (19.9)

3 Months, Outcome = 3M Hospitalized

                                                           Grouped by 3M Hospitalized
                                                                               Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                               463          399           64
Age, mean (SD)                                                                       0  67.4 (12.3)  67.5 (12.4)  66.8 (12.2)   0.693  Two Sample T-test        -0.053
Race, n (%)                                            0                             0   426 (92.0)   373 (93.5)    53 (82.8)   0.007        Chi-squared         0.335
                                                       1                                   37 (8.0)     26 (6.5)    11 (17.2)
Indigenous, n (%)                                      0                             0   450 (97.2)   388 (97.2)    62 (96.9)   0.698     Fisher's exact         0.022
                                                       1                                   13 (2.8)     11 (2.8)      2 (3.1)
Gender Identity, n (%)                                 0                             0   462 (99.8)   398 (99.7)   64 (100.0)   1.000     Fisher's exact           nan
                                                       1                                    1 (0.2)      1 (0.3)
Highschool Education, n (%)                            0                             0   422 (91.1)   367 (92.0)    55 (85.9)   0.179        Chi-squared         0.194
                                                       1                                   41 (8.9)     32 (8.0)     9 (14.1)
Post- Secondary Education, n (%)                       0                             0   277 (59.8)   237 (59.4)    40 (62.5)   0.740        Chi-squared         0.064
                                                       1                                 186 (40.2)   162 (40.6)    24 (37.5)
Employment, n (%)                                      0                             0   411 (88.8)   357 (89.5)    54 (84.4)   0.324        Chi-squared         0.152
                                                       1                                  52 (11.2)    42 (10.5)    10 (15.6)
Household income before taxes, n (%)                   0.0                           0   254 (54.9)   224 (56.1)    30 (46.9)   0.212        Chi-squared         0.186
                                                       1.0                               209 (45.1)   175 (43.9)    34 (53.1)
Marital status, n (%)                                  0                             0   239 (51.6)   210 (52.6)    29 (45.3)   0.341        Chi-squared         0.147
                                                       1                                 224 (48.4)   189 (47.4)    35 (54.7)
Living situation, n (%)                                0                             0   457 (98.7)   393 (98.5)   64 (100.0)   1.000     Fisher's exact           nan
                                                       1                                    6 (1.3)      6 (1.5)
Pack years, mean (SD)                                                                0  31.7 (71.0)  35.0 (75.6)  11.0 (17.7)  <0.001  Two Sample T-test        -0.437
Alcohol use - average number of drinks/week, mean (SD)                               0    1.6 (3.6)    1.6 (3.6)    2.0 (3.7)   0.405  Two Sample T-test         0.115
Substance Use Disorder, n (%)                          0                             0   458 (98.9)   395 (99.0)    63 (98.4)   0.526     Fisher's exact         0.050
                                                       1                                    5 (1.1)      4 (1.0)      1 (1.6)
Depression, n (%)                                      0                             0   303 (65.4)   257 (64.4)    46 (71.9)   0.306        Chi-squared         0.161
                                                       1                                 160 (34.6)   142 (35.6)    18 (28.1)
Anxiety, n (%)                                         0                             0   317 (68.5)   279 (69.9)    38 (59.4)   0.123        Chi-squared         0.222
                                                       1                                 146 (31.5)   120 (30.1)    26 (40.6)
Health Anxiety, n (%)                                  0                             0   290 (62.6)   250 (62.7)    40 (62.5)   1.000        Chi-squared         0.003
                                                       1                                 173 (37.4)   149 (37.3)    24 (37.5)
Delay to Hospital, n (%)                               0                             0   233 (50.3)   201 (50.4)    32 (50.0)   1.000        Chi-squared         0.008
                                                       1                                 230 (49.7)   198 (49.6)    32 (50.0)
Personal Stressors, n (%)                              0                             0   240 (51.8)   206 (51.6)    34 (53.1)   0.930        Chi-squared         0.030
                                                       1                                 223 (48.2)   193 (48.4)    30 (46.9)
Menopause, n (%)                                       0                             0    94 (20.3)    75 (18.8)    19 (29.7)   0.065        Chi-squared         0.256
                                                       1                                 369 (79.7)   324 (81.2)    45 (70.3)
Complicated Pregnancy, n (%)                           0                             0   332 (71.7)   290 (72.7)    42 (65.6)   0.311        Chi-squared         0.153
                                                       1                                 131 (28.3)   109 (27.3)    22 (34.4)
Stroke History, n (%)                                  0                             0   416 (89.8)   365 (91.5)    51 (79.7)   0.007        Chi-squared         0.341
                                                       1                                  47 (10.2)     34 (8.5)    13 (20.3)
MI History, n (%)                                      0                             0   378 (81.6)   327 (82.0)    51 (79.7)   0.794        Chi-squared         0.058
                                                       1                                  85 (18.4)    72 (18.0)    13 (20.3)
CABG/Stent History, n (%)                              0                             0   389 (84.0)   340 (85.2)    49 (76.6)   0.117        Chi-squared         0.221
                                                       1                                  74 (16.0)    59 (14.8)    15 (23.4)
High cholesterol, n (%)                                0                             0   190 (41.0)   165 (41.4)    25 (39.1)   0.834        Chi-squared         0.047
                                                       1                                 273 (59.0)   234 (58.6)    39 (60.9)
Diabetes, n (%)                                        0                             0   341 (73.7)   297 (74.4)    44 (68.8)   0.420        Chi-squared         0.126
                                                       1                                 122 (26.3)   102 (25.6)    20 (31.2)
Hypertension, n (%)                                    0                             0   184 (39.7)   167 (41.9)    17 (26.6)   0.029        Chi-squared         0.327
                                                       1                                 279 (60.3)   232 (58.1)    47 (73.4)
BMI, mean (SD)                                                                       0   28.7 (6.5)   28.6 (6.3)   29.3 (7.7)   0.458  Two Sample T-test         0.107
HFrEF, n (%)                                           0                             0   270 (58.3)   235 (58.9)    35 (54.7)   0.619        Chi-squared         0.085
                                                       1                                 193 (41.7)   164 (41.1)    29 (45.3)
STEMI, n (%)                                           0                             0   254 (54.9)   214 (53.6)    40 (62.5)   0.235        Chi-squared         0.180
                                                       1                                 209 (45.1)   185 (46.4)    24 (37.5)
ESSI score, n (%)                                      0                             0   319 (68.9)   273 (68.4)    46 (71.9)   0.683        Chi-squared         0.076
                                                       1                                 144 (31.1)   126 (31.6)    18 (28.1)
HADS-A, n (%)                                          0                             0   307 (66.3)   268 (67.2)    39 (60.9)   0.403        Chi-squared         0.130
                                                       1                                 156 (33.7)   131 (32.8)    25 (39.1)
HADS-D, n (%)                                          0                             0   376 (81.2)   327 (82.0)    49 (76.6)   0.394        Chi-squared         0.133
                                                       1                                  87 (18.8)    72 (18.0)    15 (23.4)

3 Months, Outcome = 3M HADS-A

                                                           Grouped by 3M HADS-A
                                                                        Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                        463          319          144
Age, mean (SD)                                                                0  67.4 (12.3)  68.9 (12.3)  64.0 (11.8)  <0.001  Two Sample T-test        -0.401
Race, n (%)                                            0                      0   426 (92.0)   296 (92.8)   130 (90.3)   0.461        Chi-squared         0.090
                                                       1                            37 (8.0)     23 (7.2)     14 (9.7)
Indigenous, n (%)                                      0                      0   450 (97.2)   312 (97.8)   138 (95.8)   0.238     Fisher's exact         0.113
                                                       1                            13 (2.8)      7 (2.2)      6 (4.2)
Gender Identity, n (%)                                 0                      0   462 (99.8)   318 (99.7)  144 (100.0)   1.000     Fisher's exact           nan
                                                       1                             1 (0.2)      1 (0.3)
Highschool Education, n (%)                            0                      0   422 (91.1)   289 (90.6)   133 (92.4)   0.658        Chi-squared         0.063
                                                       1                            41 (8.9)     30 (9.4)     11 (7.6)
Post- Secondary Education, n (%)                       0                      0   277 (59.8)   186 (58.3)    91 (63.2)   0.373        Chi-squared         0.100
                                                       1                          186 (40.2)   133 (41.7)    53 (36.8)
Employment, n (%)                                      0                      0   411 (88.8)   291 (91.2)   120 (83.3)   0.020        Chi-squared         0.238
                                                       1                           52 (11.2)     28 (8.8)    24 (16.7)
Household income before taxes, n (%)                   0.0                    0   254 (54.9)   180 (56.4)    74 (51.4)   0.364        Chi-squared         0.101
                                                       1.0                        209 (45.1)   139 (43.6)    70 (48.6)
Marital status, n (%)                                  0                      0   239 (51.6)   165 (51.7)    74 (51.4)   1.000        Chi-squared         0.007
                                                       1                          224 (48.4)   154 (48.3)    70 (48.6)
Living situation, n (%)                                0                      0   457 (98.7)   316 (99.1)   141 (97.9)   0.381     Fisher's exact         0.094
                                                       1                             6 (1.3)      3 (0.9)      3 (2.1)
Pack years, mean (SD)                                                         0  31.7 (71.0)  23.7 (61.7)  49.4 (85.8)   0.001  Two Sample T-test         0.344
Alcohol use - average number of drinks/week, mean (SD)                        0    1.6 (3.6)    1.6 (3.4)    1.7 (3.9)   0.825  Two Sample T-test         0.023
Substance Use Disorder, n (%)                          0                      0   458 (98.9)   317 (99.4)   141 (97.9)   0.177     Fisher's exact         0.126
                                                       1                             5 (1.1)      2 (0.6)      3 (2.1)
Depression, n (%)                                      0                      0   303 (65.4)   234 (73.4)    69 (47.9)  <0.001        Chi-squared         0.539
                                                       1                          160 (34.6)    85 (26.6)    75 (52.1)
Anxiety, n (%)                                         0                      0   317 (68.5)   244 (76.5)    73 (50.7)  <0.001        Chi-squared         0.556
                                                       1                          146 (31.5)    75 (23.5)    71 (49.3)
Health Anxiety, n (%)                                  0                      0   290 (62.6)   223 (69.9)    67 (46.5)  <0.001        Chi-squared         0.488
                                                       1                          173 (37.4)    96 (30.1)    77 (53.5)
Delay to Hospital, n (%)                               0                      0   233 (50.3)   157 (49.2)    76 (52.8)   0.542        Chi-squared         0.071
                                                       1                          230 (49.7)   162 (50.8)    68 (47.2)
Personal Stressors, n (%)                              0                      0   240 (51.8)   191 (59.9)    49 (34.0)  <0.001        Chi-squared         0.536
                                                       1                          223 (48.2)   128 (40.1)    95 (66.0)
Menopause, n (%)                                       0                      0    94 (20.3)    59 (18.5)    35 (24.3)   0.189        Chi-squared         0.142
                                                       1                          369 (79.7)   260 (81.5)   109 (75.7)
Complicated Pregnancy, n (%)                           0                      0   332 (71.7)   234 (73.4)    98 (68.1)   0.289        Chi-squared         0.117
                                                       1                          131 (28.3)    85 (26.6)    46 (31.9)
Stroke History, n (%)                                  0                      0   416 (89.8)   286 (89.7)   130 (90.3)   0.969        Chi-squared         0.021
                                                       1                           47 (10.2)    33 (10.3)     14 (9.7)
MI History, n (%)                                      0                      0   378 (81.6)   263 (82.4)   115 (79.9)   0.593        Chi-squared         0.066
                                                       1                           85 (18.4)    56 (17.6)    29 (20.1)
CABG/Stent History, n (%)                              0                      0   389 (84.0)   271 (85.0)   118 (81.9)   0.496        Chi-squared         0.081
                                                       1                           74 (16.0)    48 (15.0)    26 (18.1)
High cholesterol, n (%)                                0                      0   190 (41.0)   131 (41.1)    59 (41.0)   1.000        Chi-squared         0.002
                                                       1                          273 (59.0)   188 (58.9)    85 (59.0)
Diabetes, n (%)                                        0                      0   341 (73.7)   234 (73.4)   107 (74.3)   0.919        Chi-squared         0.022
                                                       1                          122 (26.3)    85 (26.6)    37 (25.7)
Hypertension, n (%)                                    0                      0   184 (39.7)   127 (39.8)    57 (39.6)   1.000        Chi-squared         0.005
                                                       1                          279 (60.3)   192 (60.2)    87 (60.4)
BMI, mean (SD)                                                                0   28.7 (6.5)   28.4 (6.4)   29.3 (6.6)   0.198  Two Sample T-test         0.130
HFrEF, n (%)                                           0                      0   270 (58.3)   191 (59.9)    79 (54.9)   0.362        Chi-squared         0.102
                                                       1                          193 (41.7)   128 (40.1)    65 (45.1)
STEMI, n (%)                                           0                      0   254 (54.9)   182 (57.1)    72 (50.0)   0.190        Chi-squared         0.142
                                                       1                          209 (45.1)   137 (42.9)    72 (50.0)
ESSI score, n (%)                                      0                      0   319 (68.9)   239 (74.9)    80 (55.6)  <0.001        Chi-squared         0.415
                                                       1                          144 (31.1)    80 (25.1)    64 (44.4)
HADS-A, n (%)                                          0                      0   307 (66.3)   248 (77.7)    59 (41.0)  <0.001        Chi-squared         0.807
                                                       1                          156 (33.7)    71 (22.3)    85 (59.0)
HADS-D, n (%)                                          0                      0   376 (81.2)   282 (88.4)    94 (65.3)  <0.001        Chi-squared         0.570
                                                       1                           87 (18.8)    37 (11.6)    50 (34.7)

3 Months, Outcome = 3M HADS-D

                                                           Grouped by 3M HADS-D
                                                                        Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                        463          384           79
Age, mean (SD)                                                                0  67.4 (12.3)  67.7 (12.5)  66.0 (11.7)   0.263  Two Sample T-test        -0.136
Race, n (%)                                            0                      0   426 (92.0)   355 (92.4)    71 (89.9)   0.589        Chi-squared         0.091
                                                       1                            37 (8.0)     29 (7.6)     8 (10.1)
Indigenous, n (%)                                      0                      0   450 (97.2)   374 (97.4)    76 (96.2)   0.472     Fisher's exact         0.068
                                                       1                            13 (2.8)     10 (2.6)      3 (3.8)
Gender Identity, n (%)                                 0                      0   462 (99.8)   383 (99.7)   79 (100.0)   1.000     Fisher's exact           nan
                                                       1                             1 (0.2)      1 (0.3)
Highschool Education, n (%)                            0                      0   422 (91.1)   354 (92.2)    68 (86.1)   0.128        Chi-squared         0.197
                                                       1                            41 (8.9)     30 (7.8)    11 (13.9)
Post- Secondary Education, n (%)                       0                      0   277 (59.8)   234 (60.9)    43 (54.4)   0.343        Chi-squared         0.132
                                                       1                          186 (40.2)   150 (39.1)    36 (45.6)
Employment, n (%)                                      0                      0   411 (88.8)   342 (89.1)    69 (87.3)   0.806        Chi-squared         0.053
                                                       1                           52 (11.2)    42 (10.9)    10 (12.7)
Household income before taxes, n (%)                   0.0                    0   254 (54.9)   216 (56.2)    38 (48.1)   0.230        Chi-squared         0.164
                                                       1.0                        209 (45.1)   168 (43.8)    41 (51.9)
Marital status, n (%)                                  0                      0   239 (51.6)   212 (55.2)    27 (34.2)   0.001        Chi-squared         0.433
                                                       1                          224 (48.4)   172 (44.8)    52 (65.8)
Living situation, n (%)                                0                      0   457 (98.7)   380 (99.0)    77 (97.5)   0.272     Fisher's exact         0.113
                                                       1                             6 (1.3)      4 (1.0)      2 (2.5)
Pack years, mean (SD)                                                         0  31.7 (71.0)  31.6 (74.2)  32.4 (53.2)   0.908  Two Sample T-test         0.013
Alcohol use - average number of drinks/week, mean (SD)                        0    1.6 (3.6)    1.8 (3.7)    1.1 (2.7)   0.087  Two Sample T-test        -0.191
Substance Use Disorder, n (%)                          0                      0   458 (98.9)   381 (99.2)    77 (97.5)   0.203     Fisher's exact         0.137
                                                       1                             5 (1.1)      3 (0.8)      2 (2.5)
Depression, n (%)                                      0                      0   303 (65.4)   277 (72.1)    26 (32.9)  <0.001        Chi-squared         0.854
                                                       1                          160 (34.6)   107 (27.9)    53 (67.1)
Anxiety, n (%)                                         0                      0   317 (68.5)   279 (72.7)    38 (48.1)  <0.001        Chi-squared         0.519
                                                       1                          146 (31.5)   105 (27.3)    41 (51.9)
Health Anxiety, n (%)                                  0                      0   290 (62.6)   250 (65.1)    40 (50.6)   0.022        Chi-squared         0.296
                                                       1                          173 (37.4)   134 (34.9)    39 (49.4)
Delay to Hospital, n (%)                               0                      0   233 (50.3)   197 (51.3)    36 (45.6)   0.421        Chi-squared         0.115
                                                       1                          230 (49.7)   187 (48.7)    43 (54.4)
Personal Stressors, n (%)                              0                      0   240 (51.8)   212 (55.2)    28 (35.4)   0.002        Chi-squared         0.405
                                                       1                          223 (48.2)   172 (44.8)    51 (64.6)
Menopause, n (%)                                       0                      0    94 (20.3)    73 (19.0)    21 (26.6)   0.171        Chi-squared         0.181
                                                       1                          369 (79.7)   311 (81.0)    58 (73.4)
Complicated Pregnancy, n (%)                           0                      0   332 (71.7)   281 (73.2)    51 (64.6)   0.158        Chi-squared         0.187
                                                       1                          131 (28.3)   103 (26.8)    28 (35.4)
Stroke History, n (%)                                  0                      0   416 (89.8)   345 (89.8)    71 (89.9)   1.000        Chi-squared         0.001
                                                       1                           47 (10.2)    39 (10.2)     8 (10.1)
MI History, n (%)                                      0                      0   378 (81.6)   316 (82.3)    62 (78.5)   0.524        Chi-squared         0.096
                                                       1                           85 (18.4)    68 (17.7)    17 (21.5)
CABG/Stent History, n (%)                              0                      0   389 (84.0)   325 (84.6)    64 (81.0)   0.528        Chi-squared         0.096
                                                       1                           74 (16.0)    59 (15.4)    15 (19.0)
High cholesterol, n (%)                                0                      0   190 (41.0)   164 (42.7)    26 (32.9)   0.137        Chi-squared         0.203
                                                       1                          273 (59.0)   220 (57.3)    53 (67.1)
Diabetes, n (%)                                        0                      0   341 (73.7)   287 (74.7)    54 (68.4)   0.302        Chi-squared         0.142
                                                       1                          122 (26.3)    97 (25.3)    25 (31.6)
Hypertension, n (%)                                    0                      0   184 (39.7)   152 (39.6)    32 (40.5)   0.979        Chi-squared         0.019
                                                       1                          279 (60.3)   232 (60.4)    47 (59.5)
BMI, mean (SD)                                                                0   28.7 (6.5)   28.4 (6.2)   29.9 (7.5)   0.110  Two Sample T-test         0.211
HFrEF, n (%)                                           0                      0   270 (58.3)   228 (59.4)    42 (53.2)   0.371        Chi-squared         0.125
                                                       1                          193 (41.7)   156 (40.6)    37 (46.8)
STEMI, n (%)                                           0                      0   254 (54.9)   212 (55.2)    42 (53.2)   0.835        Chi-squared         0.041
                                                       1                          209 (45.1)   172 (44.8)    37 (46.8)
ESSI score, n (%)                                      0                      0   319 (68.9)   286 (74.5)    33 (41.8)  <0.001        Chi-squared         0.703
                                                       1                          144 (31.1)    98 (25.5)    46 (58.2)
HADS-A, n (%)                                          0                      0   307 (66.3)   270 (70.3)    37 (46.8)  <0.001        Chi-squared         0.491
                                                       1                          156 (33.7)   114 (29.7)    42 (53.2)
HADS-D, n (%)                                          0                      0   376 (81.2)   339 (88.3)    37 (46.8)  <0.001        Chi-squared         0.987
                                                       1                           87 (18.8)    45 (11.7)    42 (53.2)

3 Months, Outcome = 3M SF-12 (Low)

                                                           Grouped by 3M SF-12 (Low)
                                                                             Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                             463          224          239
Age, mean (SD)                                                                     0  67.4 (12.3)  67.8 (12.4)  67.0 (12.3)   0.523  Two Sample T-test        -0.059
Race, n (%)                                            0                           0   426 (92.0)   215 (96.0)   211 (88.3)   0.004        Chi-squared         0.289
                                                       1                                 37 (8.0)      9 (4.0)    28 (11.7)
Indigenous, n (%)                                      0                           0   450 (97.2)   218 (97.3)   232 (97.1)   1.000        Chi-squared         0.015
                                                       1                                 13 (2.8)      6 (2.7)      7 (2.9)
Gender Identity, n (%)                                 0                           0   462 (99.8)  224 (100.0)   238 (99.6)   1.000     Fisher's exact           nan
                                                       1                                  1 (0.2)                   1 (0.4)
Highschool Education, n (%)                            0                           0   422 (91.1)   204 (91.1)   218 (91.2)   1.000        Chi-squared         0.005
                                                       1                                 41 (8.9)     20 (8.9)     21 (8.8)
Post- Secondary Education, n (%)                       0                           0   277 (59.8)   135 (60.3)   142 (59.4)   0.926        Chi-squared         0.017
                                                       1                               186 (40.2)    89 (39.7)    97 (40.6)
Employment, n (%)                                      0                           0   411 (88.8)   199 (88.8)   212 (88.7)   1.000        Chi-squared         0.004
                                                       1                                52 (11.2)    25 (11.2)    27 (11.3)
Household income before taxes, n (%)                   0.0                         0   254 (54.9)   128 (57.1)   126 (52.7)   0.388        Chi-squared         0.089
                                                       1.0                             209 (45.1)    96 (42.9)   113 (47.3)
Marital status, n (%)                                  0                           0   239 (51.6)   122 (54.5)   117 (49.0)   0.275        Chi-squared         0.110
                                                       1                               224 (48.4)   102 (45.5)   122 (51.0)
Living situation, n (%)                                0                           0   457 (98.7)   221 (98.7)   236 (98.7)   1.000     Fisher's exact         0.007
                                                       1                                  6 (1.3)      3 (1.3)      3 (1.3)
Pack years, mean (SD)                                                              0  31.7 (71.0)  46.4 (92.5)  17.9 (37.1)  <0.001  Two Sample T-test        -0.405
Alcohol use - average number of drinks/week, mean (SD)                             0    1.6 (3.6)    1.5 (3.3)    1.8 (3.8)   0.339  Two Sample T-test         0.089
Substance Use Disorder, n (%)                          0                           0   458 (98.9)   223 (99.6)   235 (98.3)   0.374     Fisher's exact         0.120
                                                       1                                  5 (1.1)      1 (0.4)      4 (1.7)
Depression, n (%)                                      0                           0   303 (65.4)   145 (64.7)   158 (66.1)   0.831        Chi-squared         0.029
                                                       1                               160 (34.6)    79 (35.3)    81 (33.9)
Anxiety, n (%)                                         0                           0   317 (68.5)   153 (68.3)   164 (68.6)   1.000        Chi-squared         0.007
                                                       1                               146 (31.5)    71 (31.7)    75 (31.4)
Health Anxiety, n (%)                                  0                           0   290 (62.6)   142 (63.4)   148 (61.9)   0.818        Chi-squared         0.030
                                                       1                               173 (37.4)    82 (36.6)    91 (38.1)
Delay to Hospital, n (%)                               0                           0   233 (50.3)   117 (52.2)   116 (48.5)   0.483        Chi-squared         0.074
                                                       1                               230 (49.7)   107 (47.8)   123 (51.5)
Personal Stressors, n (%)                              0                           0   240 (51.8)   123 (54.9)   117 (49.0)   0.234        Chi-squared         0.119
                                                       1                               223 (48.2)   101 (45.1)   122 (51.0)
Menopause, n (%)                                       0                           0    94 (20.3)    40 (17.9)    54 (22.6)   0.250        Chi-squared         0.118
                                                       1                               369 (79.7)   184 (82.1)   185 (77.4)
Complicated Pregnancy, n (%)                           0                           0   332 (71.7)   159 (71.0)   173 (72.4)   0.817        Chi-squared         0.031
                                                       1                               131 (28.3)    65 (29.0)    66 (27.6)
Stroke History, n (%)                                  0                           0   416 (89.8)   207 (92.4)   209 (87.4)   0.107        Chi-squared         0.165
                                                       1                                47 (10.2)     17 (7.6)    30 (12.6)
MI History, n (%)                                      0                           0   378 (81.6)   182 (81.2)   196 (82.0)   0.928        Chi-squared         0.020
                                                       1                                85 (18.4)    42 (18.8)    43 (18.0)
CABG/Stent History, n (%)                              0                           0   389 (84.0)   187 (83.5)   202 (84.5)   0.859        Chi-squared         0.028
                                                       1                                74 (16.0)    37 (16.5)    37 (15.5)
High cholesterol, n (%)                                0                           0   190 (41.0)   103 (46.0)    87 (36.4)   0.046        Chi-squared         0.196
                                                       1                               273 (59.0)   121 (54.0)   152 (63.6)
Diabetes, n (%)                                        0                           0   341 (73.7)   168 (75.0)   173 (72.4)   0.594        Chi-squared         0.059
                                                       1                               122 (26.3)    56 (25.0)    66 (27.6)
Hypertension, n (%)                                    0                           0   184 (39.7)    94 (42.0)    90 (37.7)   0.395        Chi-squared         0.088
                                                       1                               279 (60.3)   130 (58.0)   149 (62.3)
BMI, mean (SD)                                                                     0   28.7 (6.5)   28.3 (6.1)   29.0 (6.8)   0.279  Two Sample T-test         0.101
HFrEF, n (%)                                           0                           0   270 (58.3)   140 (62.5)   130 (54.4)   0.094        Chi-squared         0.165
                                                       1                               193 (41.7)    84 (37.5)   109 (45.6)
STEMI, n (%)                                           0                           0   254 (54.9)   139 (62.1)   115 (48.1)   0.004        Chi-squared         0.283
                                                       1                               209 (45.1)    85 (37.9)   124 (51.9)
ESSI score, n (%)                                      0                           0   319 (68.9)   163 (72.8)   156 (65.3)   0.101        Chi-squared         0.163
                                                       1                               144 (31.1)    61 (27.2)    83 (34.7)
HADS-A, n (%)                                          0                           0   307 (66.3)   163 (72.8)   144 (60.3)   0.006        Chi-squared         0.268
                                                       1                               156 (33.7)    61 (27.2)    95 (39.7)
HADS-D, n (%)                                          0                           0   376 (81.2)   197 (87.9)   179 (74.9)   0.001        Chi-squared         0.340
                                                       1                                87 (18.8)    27 (12.1)    60 (25.1)

3 Months, Outcome = 3M Cardiac Anxiety

                                                           Grouped by 3M Cardiac Anxiety
                                                                                 Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                 463          396           67
Age, mean (SD)                                                                         0  67.4 (12.3)  68.0 (12.1)  63.5 (12.9)   0.008  Two Sample T-test        -0.366
Race, n (%)                                            0                               0   426 (92.0)   367 (92.7)    59 (88.1)   0.296        Chi-squared         0.157
                                                       1                                     37 (8.0)     29 (7.3)     8 (11.9)
Indigenous, n (%)                                      0                               0   450 (97.2)   385 (97.2)    65 (97.0)   1.000     Fisher's exact         0.012
                                                       1                                     13 (2.8)     11 (2.8)      2 (3.0)
Gender Identity, n (%)                                 0                               0   462 (99.8)   395 (99.7)   67 (100.0)   1.000     Fisher's exact           nan
                                                       1                                      1 (0.2)      1 (0.3)
Highschool Education, n (%)                            0                               0   422 (91.1)   361 (91.2)    61 (91.0)   1.000        Chi-squared         0.004
                                                       1                                     41 (8.9)     35 (8.8)      6 (9.0)
Post- Secondary Education, n (%)                       0                               0   277 (59.8)   236 (59.6)    41 (61.2)   0.911        Chi-squared         0.033
                                                       1                                   186 (40.2)   160 (40.4)    26 (38.8)
Employment, n (%)                                      0                               0   411 (88.8)   352 (88.9)    59 (88.1)   1.000        Chi-squared         0.026
                                                       1                                    52 (11.2)    44 (11.1)     8 (11.9)
Household income before taxes, n (%)                   0.0                             0   254 (54.9)   222 (56.1)    32 (47.8)   0.259        Chi-squared         0.167
                                                       1.0                                 209 (45.1)   174 (43.9)    35 (52.2)
Marital status, n (%)                                  0                               0   239 (51.6)   203 (51.3)    36 (53.7)   0.809        Chi-squared         0.049
                                                       1                                   224 (48.4)   193 (48.7)    31 (46.3)
Living situation, n (%)                                0                               0   457 (98.7)   390 (98.5)   67 (100.0)   0.600     Fisher's exact           nan
                                                       1                                      6 (1.3)      6 (1.5)
Pack years, mean (SD)                                                                  0  31.7 (71.0)  32.7 (73.6)  25.7 (53.2)   0.350  Two Sample T-test        -0.109
Alcohol use - average number of drinks/week, mean (SD)                                 0    1.6 (3.6)    1.6 (3.6)    1.7 (3.6)   0.918  Two Sample T-test         0.014
Substance Use Disorder, n (%)                          0                               0   458 (98.9)   394 (99.5)    64 (95.5)   0.023     Fisher's exact         0.257
                                                       1                                      5 (1.1)      2 (0.5)      3 (4.5)
Depression, n (%)                                      0                               0   303 (65.4)   269 (67.9)    34 (50.7)   0.009        Chi-squared         0.355
                                                       1                                   160 (34.6)   127 (32.1)    33 (49.3)
Anxiety, n (%)                                         0                               0   317 (68.5)   277 (69.9)    40 (59.7)   0.127        Chi-squared         0.216
                                                       1                                   146 (31.5)   119 (30.1)    27 (40.3)
Health Anxiety, n (%)                                  0                               0   290 (62.6)   260 (65.7)    30 (44.8)   0.002        Chi-squared         0.429
                                                       1                                   173 (37.4)   136 (34.3)    37 (55.2)
Delay to Hospital, n (%)                               0                               0   233 (50.3)   203 (51.3)    30 (44.8)   0.395        Chi-squared         0.130
                                                       1                                   230 (49.7)   193 (48.7)    37 (55.2)
Personal Stressors, n (%)                              0                               0   240 (51.8)   209 (52.8)    31 (46.3)   0.393        Chi-squared         0.130
                                                       1                                   223 (48.2)   187 (47.2)    36 (53.7)
Menopause, n (%)                                       0                               0    94 (20.3)    71 (17.9)    23 (34.3)   0.003        Chi-squared         0.380
                                                       1                                   369 (79.7)   325 (82.1)    44 (65.7)
Complicated Pregnancy, n (%)                           0                               0   332 (71.7)   286 (72.2)    46 (68.7)   0.651        Chi-squared         0.078
                                                       1                                   131 (28.3)   110 (27.8)    21 (31.3)
Stroke History, n (%)                                  0                               0   416 (89.8)   355 (89.6)    61 (91.0)   0.895        Chi-squared         0.047
                                                       1                                    47 (10.2)    41 (10.4)      6 (9.0)
MI History, n (%)                                      0                               0   378 (81.6)   324 (81.8)    54 (80.6)   0.946        Chi-squared         0.031
                                                       1                                    85 (18.4)    72 (18.2)    13 (19.4)
CABG/Stent History, n (%)                              0                               0   389 (84.0)   334 (84.3)    55 (82.1)   0.775        Chi-squared         0.060
                                                       1                                    74 (16.0)    62 (15.7)    12 (17.9)
High cholesterol, n (%)                                0                               0   190 (41.0)   165 (41.7)    25 (37.3)   0.592        Chi-squared         0.089
                                                       1                                   273 (59.0)   231 (58.3)    42 (62.7)
Diabetes, n (%)                                        0                               0   341 (73.7)   293 (74.0)    48 (71.6)   0.800        Chi-squared         0.053
                                                       1                                   122 (26.3)   103 (26.0)    19 (28.4)
Hypertension, n (%)                                    0                               0   184 (39.7)   161 (40.7)    23 (34.3)   0.399        Chi-squared         0.131
                                                       1                                   279 (60.3)   235 (59.3)    44 (65.7)
BMI, mean (SD)                                                                         0   28.7 (6.5)   28.3 (6.3)   31.1 (7.2)   0.004  Two Sample T-test         0.415
HFrEF, n (%)                                           0                               0   270 (58.3)   233 (58.8)    37 (55.2)   0.674        Chi-squared         0.073
                                                       1                                   193 (41.7)   163 (41.2)    30 (44.8)
STEMI, n (%)                                           0                               0   254 (54.9)   219 (55.3)    35 (52.2)   0.739        Chi-squared         0.061
                                                       1                                   209 (45.1)   177 (44.7)    32 (47.8)
ESSI score, n (%)                                      0                               0   319 (68.9)   279 (70.5)    40 (59.7)   0.106        Chi-squared         0.227
                                                       1                                   144 (31.1)   117 (29.5)    27 (40.3)
HADS-A, n (%)                                          0                               0   307 (66.3)   271 (68.4)    36 (53.7)   0.027        Chi-squared         0.305
                                                       1                                   156 (33.7)   125 (31.6)    31 (46.3)
HADS-D, n (%)                                          0                               0   376 (81.2)   331 (83.6)    45 (67.2)   0.003        Chi-squared         0.388
                                                       1                                    87 (18.8)    65 (16.4)    22 (32.8)

3 Months, Outcome = 3M MOS (Low Support)

                                                           Grouped by 3M MOS (Low Support)
                                                                                   Missing      Overall          0.0           1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                   463          354           109
Age, mean (SD)                                                                           0  67.4 (12.3)  67.6 (12.5)   66.7 (11.7)   0.509  Two Sample T-test        -0.071
Race, n (%)                                            0                                 0   426 (92.0)   323 (91.2)    103 (94.5)   0.372        Chi-squared         0.127
                                                       1                                       37 (8.0)     31 (8.8)       6 (5.5)
Indigenous, n (%)                                      0                                 0   450 (97.2)   343 (96.9)    107 (98.2)   0.742     Fisher's exact         0.082
                                                       1                                       13 (2.8)     11 (3.1)       2 (1.8)
Gender Identity, n (%)                                 0                                 0   462 (99.8)   353 (99.7)   109 (100.0)   1.000     Fisher's exact           nan
                                                       1                                        1 (0.2)      1 (0.3)
Highschool Education, n (%)                            0                                 0   422 (91.1)   321 (90.7)    101 (92.7)   0.657        Chi-squared         0.072
                                                       1                                       41 (8.9)     33 (9.3)       8 (7.3)
Post- Secondary Education, n (%)                       0                                 0   277 (59.8)   218 (61.6)     59 (54.1)   0.202        Chi-squared         0.151
                                                       1                                     186 (40.2)   136 (38.4)     50 (45.9)
Employment, n (%)                                      0                                 0   411 (88.8)   319 (90.1)     92 (84.4)   0.140        Chi-squared         0.172
                                                       1                                      52 (11.2)     35 (9.9)     17 (15.6)
Household income before taxes, n (%)                   0.0                               0   254 (54.9)   210 (59.3)     44 (40.4)   0.001        Chi-squared         0.386
                                                       1.0                                   209 (45.1)   144 (40.7)     65 (59.6)
Marital status, n (%)                                  0                                 0   239 (51.6)   190 (53.7)     49 (45.0)   0.138        Chi-squared         0.175
                                                       1                                     224 (48.4)   164 (46.3)     60 (55.0)
Living situation, n (%)                                0                                 0   457 (98.7)   353 (99.7)    104 (95.4)   0.003     Fisher's exact         0.282
                                                       1                                        6 (1.3)      1 (0.3)       5 (4.6)
Pack years, mean (SD)                                                                    0  31.7 (71.0)  11.9 (17.8)  95.9 (122.8)  <0.001  Two Sample T-test         0.958
Alcohol use - average number of drinks/week, mean (SD)                                   0    1.6 (3.6)    1.7 (3.6)     1.6 (3.5)   0.773  Two Sample T-test        -0.031
Substance Use Disorder, n (%)                          0                                 0   458 (98.9)   349 (98.6)   109 (100.0)   0.596     Fisher's exact           nan
                                                       1                                        5 (1.1)      5 (1.4)
Depression, n (%)                                      0                                 0   303 (65.4)   235 (66.4)     68 (62.4)   0.514        Chi-squared         0.084
                                                       1                                     160 (34.6)   119 (33.6)     41 (37.6)
Anxiety, n (%)                                         0                                 0   317 (68.5)   239 (67.5)     78 (71.6)   0.498        Chi-squared         0.088
                                                       1                                     146 (31.5)   115 (32.5)     31 (28.4)
Health Anxiety, n (%)                                  0                                 0   290 (62.6)   233 (65.8)     57 (52.3)   0.015        Chi-squared         0.278
                                                       1                                     173 (37.4)   121 (34.2)     52 (47.7)
Delay to Hospital, n (%)                               0                                 0   233 (50.3)   168 (47.5)     65 (59.6)   0.035        Chi-squared         0.246
                                                       1                                     230 (49.7)   186 (52.5)     44 (40.4)
Personal Stressors, n (%)                              0                                 0   240 (51.8)   195 (55.1)     45 (41.3)   0.016        Chi-squared         0.279
                                                       1                                     223 (48.2)   159 (44.9)     64 (58.7)
Menopause, n (%)                                       0                                 0    94 (20.3)    72 (20.3)     22 (20.2)   1.000        Chi-squared         0.004
                                                       1                                     369 (79.7)   282 (79.7)     87 (79.8)
Complicated Pregnancy, n (%)                           0                                 0   332 (71.7)   258 (72.9)     74 (67.9)   0.373        Chi-squared         0.109
                                                       1                                     131 (28.3)    96 (27.1)     35 (32.1)
Stroke History, n (%)                                  0                                 0   416 (89.8)   317 (89.5)     99 (90.8)   0.838        Chi-squared         0.043
                                                       1                                      47 (10.2)    37 (10.5)      10 (9.2)
MI History, n (%)                                      0                                 0   378 (81.6)   284 (80.2)     94 (86.2)   0.202        Chi-squared         0.161
                                                       1                                      85 (18.4)    70 (19.8)     15 (13.8)
CABG/Stent History, n (%)                              0                                 0   389 (84.0)   294 (83.1)     95 (87.2)   0.383        Chi-squared         0.115
                                                       1                                      74 (16.0)    60 (16.9)     14 (12.8)
High cholesterol, n (%)                                0                                 0   190 (41.0)   148 (41.8)     42 (38.5)   0.619        Chi-squared         0.067
                                                       1                                     273 (59.0)   206 (58.2)     67 (61.5)
Diabetes, n (%)                                        0                                 0   341 (73.7)   261 (73.7)     80 (73.4)   1.000        Chi-squared         0.008
                                                       1                                     122 (26.3)    93 (26.3)     29 (26.6)
Hypertension, n (%)                                    0                                 0   184 (39.7)   148 (41.8)     36 (33.0)   0.127        Chi-squared         0.182
                                                       1                                     279 (60.3)   206 (58.2)     73 (67.0)
BMI, mean (SD)                                                                           0   28.7 (6.5)   28.8 (6.4)    28.4 (6.8)   0.646  Two Sample T-test        -0.051
HFrEF, n (%)                                           0                                 0   270 (58.3)   201 (56.8)     69 (63.3)   0.273        Chi-squared         0.133
                                                       1                                     193 (41.7)   153 (43.2)     40 (36.7)
STEMI, n (%)                                           0                                 0   254 (54.9)   201 (56.8)     53 (48.6)   0.166        Chi-squared         0.164
                                                       1                                     209 (45.1)   153 (43.2)     56 (51.4)
ESSI score, n (%)                                      0                                 0   319 (68.9)   273 (77.1)     46 (42.2)  <0.001        Chi-squared         0.762
                                                       1                                     144 (31.1)    81 (22.9)     63 (57.8)
HADS-A, n (%)                                          0                                 0   307 (66.3)   255 (72.0)     52 (47.7)  <0.001        Chi-squared         0.512
                                                       1                                     156 (33.7)    99 (28.0)     57 (52.3)
HADS-D, n (%)                                          0                                 0   376 (81.2)   302 (85.3)     74 (67.9)  <0.001        Chi-squared         0.420
                                                       1                                      87 (18.8)    52 (14.7)     35 (32.1)

In [109]:
for outcome in colsOutcomes6m:
    print('6 Months, Outcome = ' + outcome)
    table = TableOne(data = data6m, columns=cols6m, pval = True, categorical = cols6mCat,
                       groupby = [outcome], htest_name=True, smd=True)
    filename = outcome + "_6m_table1.csv"
    #removing backslash from strings
    filename = filename.replace("/","-")
    table.to_csv(filename, index=False)
    display(table)

6 Months, Outcome = 6M New Depression Diagnosis

                                                           Grouped by 6M New Depression Diagnosis
                                                                                           Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                           363          333           30
Age, mean (SD)                                                                                   0  67.7 (12.5)  67.5 (12.5)  69.6 (12.0)   0.364  Two Sample T-test         0.172
Race, n (%)                                            0                                         0   337 (92.8)   310 (93.1)    27 (90.0)   0.463     Fisher's exact         0.111
                                                       1                                               26 (7.2)     23 (6.9)     3 (10.0)
Indigenous, n (%)                                      0                                         0   352 (97.0)   324 (97.3)    28 (93.3)   0.228     Fisher's exact         0.188
                                                       1                                               11 (3.0)      9 (2.7)      2 (6.7)
Gender Identity, n (%)                                 0                                         0   362 (99.7)   332 (99.7)   30 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                                         0   330 (90.9)   305 (91.6)    25 (83.3)   0.173     Fisher's exact         0.251
                                                       1                                               33 (9.1)     28 (8.4)     5 (16.7)
Post- Secondary Education, n (%)                       0                                         0   221 (60.9)   204 (61.3)    17 (56.7)   0.765        Chi-squared         0.094
                                                       1                                             142 (39.1)   129 (38.7)    13 (43.3)
Employment, n (%)                                      0                                         0   329 (90.6)   302 (90.7)    27 (90.0)   0.752     Fisher's exact         0.023
                                                       1                                               34 (9.4)     31 (9.3)     3 (10.0)
Household income before taxes, n (%)                   0.0                                       0   203 (55.9)   187 (56.2)    16 (53.3)   0.915        Chi-squared         0.057
                                                       1.0                                           160 (44.1)   146 (43.8)    14 (46.7)
Marital status, n (%)                                  0                                         0   180 (49.6)   168 (50.5)    12 (40.0)   0.365        Chi-squared         0.211
                                                       1                                             183 (50.4)   165 (49.5)    18 (60.0)
Living situation, n (%)                                0                                         0   359 (98.9)   330 (99.1)    29 (96.7)   0.293     Fisher's exact         0.170
                                                       1                                                4 (1.1)      3 (0.9)      1 (3.3)
Pack years, mean (SD)                                                                            0  29.6 (65.4)  31.0 (68.0)  14.2 (17.4)   0.001  Two Sample T-test        -0.339
Alcohol use - average number of drinks/week, mean (SD)                                           0    1.6 (3.5)    1.6 (3.4)    1.9 (4.2)   0.720  Two Sample T-test         0.075
Substance Use Disorder, n (%)                          0                                         0   361 (99.4)   331 (99.4)   30 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                2 (0.6)      2 (0.6)
Depression, n (%)                                      0                                         0   236 (65.0)   230 (69.1)     6 (20.0)  <0.001        Chi-squared         1.135
                                                       1                                             127 (35.0)   103 (30.9)    24 (80.0)
Anxiety, n (%)                                         0                                         0   253 (69.7)   242 (72.7)    11 (36.7)  <0.001        Chi-squared         0.776
                                                       1                                             110 (30.3)    91 (27.3)    19 (63.3)
Health Anxiety, n (%)                                  0                                         0   231 (63.6)   216 (64.9)    15 (50.0)   0.155        Chi-squared         0.304
                                                       1                                             132 (36.4)   117 (35.1)    15 (50.0)
Delay to Hospital, n (%)                               0                                         0   182 (50.1)   168 (50.5)    14 (46.7)   0.836        Chi-squared         0.076
                                                       1                                             181 (49.9)   165 (49.5)    16 (53.3)
Personal Stressors, n (%)                              0                                         0   187 (51.5)   175 (52.6)    12 (40.0)   0.260        Chi-squared         0.254
                                                       1                                             176 (48.5)   158 (47.4)    18 (60.0)
Menopause, n (%)                                       0                                         0    76 (20.9)    71 (21.3)     5 (16.7)   0.714        Chi-squared         0.119
                                                       1                                             287 (79.1)   262 (78.7)    25 (83.3)
Complicated Pregnancy, n (%)                           0                                         0   264 (72.7)   242 (72.7)    22 (73.3)   1.000        Chi-squared         0.015
                                                       1                                              99 (27.3)    91 (27.3)     8 (26.7)
Stroke History, n (%)                                  0                                         0   325 (89.5)   300 (90.1)    25 (83.3)   0.224     Fisher's exact         0.200
                                                       1                                              38 (10.5)     33 (9.9)     5 (16.7)
MI History, n (%)                                      0                                         0   295 (81.3)   273 (82.0)    22 (73.3)   0.358        Chi-squared         0.209
                                                       1                                              68 (18.7)    60 (18.0)     8 (26.7)
CABG/Stent History, n (%)                              0                                         0   308 (84.8)   285 (85.6)    23 (76.7)   0.189     Fisher's exact         0.229
                                                       1                                              55 (15.2)    48 (14.4)     7 (23.3)
High cholesterol, n (%)                                0                                         0   149 (41.0)   138 (41.4)    11 (36.7)   0.752        Chi-squared         0.098
                                                       1                                             214 (59.0)   195 (58.6)    19 (63.3)
Diabetes, n (%)                                        0                                         0   267 (73.6)   245 (73.6)    22 (73.3)   1.000        Chi-squared         0.005
                                                       1                                              96 (26.4)    88 (26.4)     8 (26.7)
Hypertension, n (%)                                    0                                         0   143 (39.4)   131 (39.3)    12 (40.0)   1.000        Chi-squared         0.014
                                                       1                                             220 (60.6)   202 (60.7)    18 (60.0)
BMI, mean (SD)                                                                                   0   28.8 (6.5)   28.8 (6.5)   28.8 (6.8)   0.980  Two Sample T-test        -0.005
HFrEF, n (%)                                           0                                         0   210 (57.9)   191 (57.4)    19 (63.3)   0.659        Chi-squared         0.122
                                                       1                                             153 (42.1)   142 (42.6)    11 (36.7)
STEMI, n (%)                                           0                                         0   208 (57.3)   188 (56.5)    20 (66.7)   0.373        Chi-squared         0.211
                                                       1                                             155 (42.7)   145 (43.5)    10 (33.3)
ESSI score, n (%)                                      0                                         0   248 (68.3)   231 (69.4)    17 (56.7)   0.220        Chi-squared         0.265
                                                       1                                             115 (31.7)   102 (30.6)    13 (43.3)
HADS-A, n (%)                                          0                                         0   246 (67.8)   234 (70.3)    12 (40.0)   0.001        Chi-squared         0.639
                                                       1                                             117 (32.2)    99 (29.7)    18 (60.0)
HADS-D, n (%)                                          0                                         0   297 (81.8)   279 (83.8)    18 (60.0)   0.003        Chi-squared         0.549
                                                       1                                              66 (18.2)    54 (16.2)    12 (40.0)
3M New Depression Diagnosis , n (%)                    0.0                                       0   332 (91.5)   321 (96.4)    11 (36.7)  <0.001     Fisher's exact         1.635
                                                       1.0                                             31 (8.5)     12 (3.6)    19 (63.3)
3M New Anxiety Diagnosis , n (%)                       0.0                                       0   331 (91.2)   315 (94.6)    16 (53.3)  <0.001     Fisher's exact         1.065
                                                       1.0                                             32 (8.8)     18 (5.4)    14 (46.7)
3M New Substance Use Disorder, n (%)                   0.0                                       0   361 (99.4)   332 (99.7)    29 (96.7)   0.159     Fisher's exact         0.229
                                                       1.0                                              2 (0.6)      1 (0.3)      1 (3.3)
3M New Stroke, n (%)                                   0.0                                       0   356 (98.1)   326 (97.9)   30 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                              7 (1.9)      7 (2.1)
3M New MI, n (%)                                       0.0                                       0   353 (97.2)   324 (97.3)    29 (96.7)   0.583     Fisher's exact         0.037
                                                       1.0                                             10 (2.8)      9 (2.7)      1 (3.3)
3M New CABG/Stent, n (%)                               0.0                                       0   331 (91.2)   303 (91.0)    28 (93.3)   1.000     Fisher's exact         0.087
                                                       1.0                                             32 (8.8)     30 (9.0)      2 (6.7)
3M Cardiac Rehab, n (%)                                0.0                                       0    87 (24.0)    83 (24.9)     4 (13.3)   0.230        Chi-squared         0.298
                                                       1.0                                           276 (76.0)   250 (75.1)    26 (86.7)
3M Hospitalized , n (%)                                0.0                                       0   314 (86.5)   290 (87.1)    24 (80.0)   0.268     Fisher's exact         0.192
                                                       1.0                                            49 (13.5)    43 (12.9)     6 (20.0)
3M HADS-A, n (%)                                       0.0                                       0   251 (69.1)   238 (71.5)    13 (43.3)   0.003        Chi-squared         0.594
                                                       1.0                                           112 (30.9)    95 (28.5)    17 (56.7)
3M HADS-D, n (%)                                       0.0                                       0   300 (82.6)   282 (84.7)    18 (60.0)   0.002        Chi-squared         0.574
                                                       1.0                                            63 (17.4)    51 (15.3)    12 (40.0)
3M SF-12 (Low), n (%)                                  0.0                                       0   178 (49.0)   165 (49.5)    13 (43.3)   0.644        Chi-squared         0.125
                                                       1.0                                           185 (51.0)   168 (50.5)    17 (56.7)
3M Cardiac Anxiety, n (%)                              0.0                                       0   311 (85.7)   291 (87.4)    20 (66.7)   0.005     Fisher's exact         0.508
                                                       1.0                                            52 (14.3)    42 (12.6)    10 (33.3)
3M MOS (Low Support), n (%)                            0.0                                       0   281 (77.4)   257 (77.2)    24 (80.0)   0.900        Chi-squared         0.069
                                                       1.0                                            82 (22.6)    76 (22.8)     6 (20.0)

6 Months, Outcome = 6M New Anxiety Diagnosis

                                                           Grouped by 6M New Anxiety Diagnosis
                                                                                       Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                       363          329           34
Age, mean (SD)                                                                               0  67.7 (12.5)  67.9 (12.5)  66.1 (12.5)   0.442  Two Sample T-test        -0.140
Race, n (%)                                            0                                     0   337 (92.8)   308 (93.6)    29 (85.3)   0.083     Fisher's exact         0.274
                                                       1                                           26 (7.2)     21 (6.4)     5 (14.7)
Indigenous, n (%)                                      0                                     0   352 (97.0)   321 (97.6)    31 (91.2)   0.074     Fisher's exact         0.280
                                                       1                                           11 (3.0)      8 (2.4)      3 (8.8)
Gender Identity, n (%)                                 0                                     0   362 (99.7)   328 (99.7)   34 (100.0)   1.000     Fisher's exact           nan
                                                       1                                            1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                                     0   330 (90.9)   298 (90.6)    32 (94.1)   0.754     Fisher's exact         0.133
                                                       1                                           33 (9.1)     31 (9.4)      2 (5.9)
Post- Secondary Education, n (%)                       0                                     0   221 (60.9)   197 (59.9)    24 (70.6)   0.301        Chi-squared         0.226
                                                       1                                         142 (39.1)   132 (40.1)    10 (29.4)
Employment, n (%)                                      0                                     0   329 (90.6)   299 (90.9)    30 (88.2)   0.543     Fisher's exact         0.087
                                                       1                                           34 (9.4)     30 (9.1)     4 (11.8)
Household income before taxes, n (%)                   0.0                                   0   203 (55.9)   185 (56.2)    18 (52.9)   0.852        Chi-squared         0.066
                                                       1.0                                       160 (44.1)   144 (43.8)    16 (47.1)
Marital status, n (%)                                  0                                     0   180 (49.6)   164 (49.8)    16 (47.1)   0.897        Chi-squared         0.056
                                                       1                                         183 (50.4)   165 (50.2)    18 (52.9)
Living situation, n (%)                                0                                     0   359 (98.9)   326 (99.1)    33 (97.1)   0.326     Fisher's exact         0.148
                                                       1                                            4 (1.1)      3 (0.9)      1 (2.9)
Pack years, mean (SD)                                                                        0  29.6 (65.4)  30.1 (67.9)  24.1 (33.8)   0.386  Two Sample T-test        -0.112
Alcohol use - average number of drinks/week, mean (SD)                                       0    1.6 (3.5)    1.7 (3.5)    1.2 (3.5)   0.482  Two Sample T-test        -0.129
Substance Use Disorder, n (%)                          0                                     0   361 (99.4)   327 (99.4)   34 (100.0)   1.000     Fisher's exact           nan
                                                       1                                            2 (0.6)      2 (0.6)
Depression, n (%)                                      0                                     0   236 (65.0)   223 (67.8)    13 (38.2)   0.001        Chi-squared         0.620
                                                       1                                         127 (35.0)   106 (32.2)    21 (61.8)
Anxiety, n (%)                                         0                                     0   253 (69.7)   238 (72.3)    15 (44.1)   0.001        Chi-squared         0.597
                                                       1                                         110 (30.3)    91 (27.7)    19 (55.9)
Health Anxiety, n (%)                                  0                                     0   231 (63.6)   213 (64.7)    18 (52.9)   0.240        Chi-squared         0.242
                                                       1                                         132 (36.4)   116 (35.3)    16 (47.1)
Delay to Hospital, n (%)                               0                                     0   182 (50.1)   167 (50.8)    15 (44.1)   0.577        Chi-squared         0.133
                                                       1                                         181 (49.9)   162 (49.2)    19 (55.9)
Personal Stressors, n (%)                              0                                     0   187 (51.5)   179 (54.4)     8 (23.5)   0.001        Chi-squared         0.667
                                                       1                                         176 (48.5)   150 (45.6)    26 (76.5)
Menopause, n (%)                                       0                                     0    76 (20.9)    66 (20.1)    10 (29.4)   0.292        Chi-squared         0.218
                                                       1                                         287 (79.1)   263 (79.9)    24 (70.6)
Complicated Pregnancy, n (%)                           0                                     0   264 (72.7)   239 (72.6)    25 (73.5)   1.000        Chi-squared         0.020
                                                       1                                          99 (27.3)    90 (27.4)     9 (26.5)
Stroke History, n (%)                                  0                                     0   325 (89.5)   296 (90.0)    29 (85.3)   0.379     Fisher's exact         0.142
                                                       1                                          38 (10.5)    33 (10.0)     5 (14.7)
MI History, n (%)                                      0                                     0   295 (81.3)   267 (81.2)    28 (82.4)   1.000        Chi-squared         0.031
                                                       1                                          68 (18.7)    62 (18.8)     6 (17.6)
CABG/Stent History, n (%)                              0                                     0   308 (84.8)   279 (84.8)    29 (85.3)   1.000        Chi-squared         0.014
                                                       1                                          55 (15.2)    50 (15.2)     5 (14.7)
High cholesterol, n (%)                                0                                     0   149 (41.0)   137 (41.6)    12 (35.3)   0.594        Chi-squared         0.131
                                                       1                                         214 (59.0)   192 (58.4)    22 (64.7)
Diabetes, n (%)                                        0                                     0   267 (73.6)   240 (72.9)    27 (79.4)   0.542        Chi-squared         0.152
                                                       1                                          96 (26.4)    89 (27.1)     7 (20.6)
Hypertension, n (%)                                    0                                     0   143 (39.4)   127 (38.6)    16 (47.1)   0.437        Chi-squared         0.172
                                                       1                                         220 (60.6)   202 (61.4)    18 (52.9)
BMI, mean (SD)                                                                               0   28.8 (6.5)   28.7 (6.5)   29.4 (6.8)   0.582  Two Sample T-test         0.102
HFrEF, n (%)                                           0                                     0   210 (57.9)   190 (57.8)    20 (58.8)   1.000        Chi-squared         0.022
                                                       1                                         153 (42.1)   139 (42.2)    14 (41.2)
STEMI, n (%)                                           0                                     0   208 (57.3)   187 (56.8)    21 (61.8)   0.711        Chi-squared         0.100
                                                       1                                         155 (42.7)   142 (43.2)    13 (38.2)
ESSI score, n (%)                                      0                                     0   248 (68.3)   229 (69.6)    19 (55.9)   0.149        Chi-squared         0.287
                                                       1                                         115 (31.7)   100 (30.4)    15 (44.1)
HADS-A, n (%)                                          0                                     0   246 (67.8)   229 (69.6)    17 (50.0)   0.033        Chi-squared         0.408
                                                       1                                         117 (32.2)   100 (30.4)    17 (50.0)
HADS-D, n (%)                                          0                                     0   297 (81.8)   273 (83.0)    24 (70.6)   0.121        Chi-squared         0.297
                                                       1                                          66 (18.2)    56 (17.0)    10 (29.4)
3M New Depression Diagnosis , n (%)                    0.0                                   0   332 (91.5)   311 (94.5)    21 (61.8)  <0.001     Fisher's exact         0.864
                                                       1.0                                         31 (8.5)     18 (5.5)    13 (38.2)
3M New Anxiety Diagnosis , n (%)                       0.0                                   0   331 (91.2)   315 (95.7)    16 (47.1)  <0.001     Fisher's exact         1.279
                                                       1.0                                         32 (8.8)     14 (4.3)    18 (52.9)
3M New Substance Use Disorder, n (%)                   0.0                                   0   361 (99.4)   328 (99.7)    33 (97.1)   0.179     Fisher's exact         0.210
                                                       1.0                                          2 (0.6)      1 (0.3)      1 (2.9)
3M New Stroke, n (%)                                   0.0                                   0   356 (98.1)   322 (97.9)   34 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                          7 (1.9)      7 (2.1)
3M New MI, n (%)                                       0.0                                   0   353 (97.2)   321 (97.6)    32 (94.1)   0.239     Fisher's exact         0.174
                                                       1.0                                         10 (2.8)      8 (2.4)      2 (5.9)
3M New CABG/Stent, n (%)                               0.0                                   0   331 (91.2)   299 (90.9)    32 (94.1)   0.754     Fisher's exact         0.123
                                                       1.0                                         32 (8.8)     30 (9.1)      2 (5.9)
3M Cardiac Rehab, n (%)                                0.0                                   0    87 (24.0)    80 (24.3)     7 (20.6)   0.784        Chi-squared         0.089
                                                       1.0                                       276 (76.0)   249 (75.7)    27 (79.4)
3M Hospitalized , n (%)                                0.0                                   0   314 (86.5)   286 (86.9)    28 (82.4)   0.433     Fisher's exact         0.127
                                                       1.0                                        49 (13.5)    43 (13.1)     6 (17.6)
3M HADS-A, n (%)                                       0.0                                   0   251 (69.1)   236 (71.7)    15 (44.1)   0.002        Chi-squared         0.583
                                                       1.0                                       112 (30.9)    93 (28.3)    19 (55.9)
3M HADS-D, n (%)                                       0.0                                   0   300 (82.6)   275 (83.6)    25 (73.5)   0.216        Chi-squared         0.247
                                                       1.0                                        63 (17.4)    54 (16.4)     9 (26.5)
3M SF-12 (Low), n (%)                                  0.0                                   0   178 (49.0)   161 (48.9)    17 (50.0)   1.000        Chi-squared         0.021
                                                       1.0                                       185 (51.0)   168 (51.1)    17 (50.0)
3M Cardiac Anxiety, n (%)                              0.0                                   0   311 (85.7)   286 (86.9)    25 (73.5)   0.042     Fisher's exact         0.341
                                                       1.0                                        52 (14.3)    43 (13.1)     9 (26.5)
3M MOS (Low Support), n (%)                            0.0                                   0   281 (77.4)   254 (77.2)    27 (79.4)   0.938        Chi-squared         0.054
                                                       1.0                                        82 (22.6)    75 (22.8)     7 (20.6)

6 Months, Outcome = 6M New Substance Use Disorder

                                                           Grouped by 6M New Substance Use Disorder
                                                                                            Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                            363          361            2
Age, mean (SD)                                                                                    0  67.7 (12.5)  67.7 (12.5)   74.5 (3.5)   0.204  Two Sample T-test         0.744
Race, n (%)                                            0                                          0   337 (92.8)   335 (92.8)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                26 (7.2)     26 (7.2)
Indigenous, n (%)                                      0                                          0   352 (97.0)   350 (97.0)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                11 (3.0)     11 (3.0)
Gender Identity, n (%)                                 0                                          0   362 (99.7)   360 (99.7)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                 1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                                          0   330 (90.9)   329 (91.1)     1 (50.0)   0.174     Fisher's exact         1.011
                                                       1                                                33 (9.1)     32 (8.9)     1 (50.0)
Post- Secondary Education, n (%)                       0                                          0   221 (60.9)   221 (61.2)                0.152     Fisher's exact         1.777
                                                       1                                              142 (39.1)   140 (38.8)    2 (100.0)
Employment, n (%)                                      0                                          0   329 (90.6)   327 (90.6)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                34 (9.4)     34 (9.4)
Household income before taxes, n (%)                   0.0                                        0   203 (55.9)   203 (56.2)                0.194     Fisher's exact         1.603
                                                       1.0                                            160 (44.1)   158 (43.8)    2 (100.0)
Marital status, n (%)                                  0                                          0   180 (49.6)   179 (49.6)     1 (50.0)   1.000     Fisher's exact         0.008
                                                       1                                              183 (50.4)   182 (50.4)     1 (50.0)
Living situation, n (%)                                0                                          0   359 (98.9)   357 (98.9)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                 4 (1.1)      4 (1.1)
Pack years, mean (SD)                                                                             0  29.6 (65.4)  29.6 (65.6)  28.0 (38.2)   0.963  Two Sample T-test        -0.030
Alcohol use - average number of drinks/week, mean (SD)                                            0    1.6 (3.5)    1.6 (3.5)    0.0 (0.0)  <0.001  Two Sample T-test        -0.666
Substance Use Disorder, n (%)                          0                                          0   361 (99.4)   359 (99.4)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                                 2 (0.6)      2 (0.6)
Depression, n (%)                                      0                                          0   236 (65.0)   236 (65.4)                0.122     Fisher's exact         1.943
                                                       1                                              127 (35.0)   125 (34.6)    2 (100.0)
Anxiety, n (%)                                         0                                          0   253 (69.7)   252 (69.8)     1 (50.0)   0.515     Fisher's exact         0.413
                                                       1                                              110 (30.3)   109 (30.2)     1 (50.0)
Health Anxiety, n (%)                                  0                                          0   231 (63.6)   230 (63.7)     1 (50.0)   1.000     Fisher's exact         0.280
                                                       1                                              132 (36.4)   131 (36.3)     1 (50.0)
Delay to Hospital, n (%)                               0                                          0   182 (50.1)   181 (50.1)     1 (50.0)   1.000     Fisher's exact         0.003
                                                       1                                              181 (49.9)   180 (49.9)     1 (50.0)
Personal Stressors, n (%)                              0                                          0   187 (51.5)   186 (51.5)     1 (50.0)   1.000     Fisher's exact         0.030
                                                       1                                              176 (48.5)   175 (48.5)     1 (50.0)
Menopause, n (%)                                       0                                          0    76 (20.9)    76 (21.1)                1.000     Fisher's exact         0.730
                                                       1                                              287 (79.1)   285 (78.9)    2 (100.0)
Complicated Pregnancy, n (%)                           0                                          0   264 (72.7)   263 (72.9)     1 (50.0)   0.472     Fisher's exact         0.483
                                                       1                                               99 (27.3)    98 (27.1)     1 (50.0)
Stroke History, n (%)                                  0                                          0   325 (89.5)   324 (89.8)     1 (50.0)   0.199     Fisher's exact         0.961
                                                       1                                               38 (10.5)    37 (10.2)     1 (50.0)
MI History, n (%)                                      0                                          0   295 (81.3)   295 (81.7)                0.035     Fisher's exact         2.990
                                                       1                                               68 (18.7)    66 (18.3)    2 (100.0)
CABG/Stent History, n (%)                              0                                          0   308 (84.8)   307 (85.0)     1 (50.0)   0.280     Fisher's exact         0.807
                                                       1                                               55 (15.2)    54 (15.0)     1 (50.0)
High cholesterol, n (%)                                0                                          0   149 (41.0)   148 (41.0)     1 (50.0)   1.000     Fisher's exact         0.182
                                                       1                                              214 (59.0)   213 (59.0)     1 (50.0)
Diabetes, n (%)                                        0                                          0   267 (73.6)   265 (73.4)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                               96 (26.4)    96 (26.6)
Hypertension, n (%)                                    0                                          0   143 (39.4)   143 (39.6)                0.521     Fisher's exact         1.145
                                                       1                                              220 (60.6)   218 (60.4)    2 (100.0)
BMI, mean (SD)                                                                                    0   28.8 (6.5)   28.8 (6.5)   21.2 (1.1)   0.034  Two Sample T-test        -1.627
HFrEF, n (%)                                           0                                          0   210 (57.9)   209 (57.9)     1 (50.0)   1.000     Fisher's exact         0.159
                                                       1                                              153 (42.1)   152 (42.1)     1 (50.0)
STEMI, n (%)                                           0                                          0   208 (57.3)   207 (57.3)     1 (50.0)   1.000     Fisher's exact         0.148
                                                       1                                              155 (42.7)   154 (42.7)     1 (50.0)
ESSI score, n (%)                                      0                                          0   248 (68.3)   247 (68.4)     1 (50.0)   0.534     Fisher's exact         0.382
                                                       1                                              115 (31.7)   114 (31.6)     1 (50.0)
HADS-A, n (%)                                          0                                          0   246 (67.8)   245 (67.9)     1 (50.0)   0.541     Fisher's exact         0.369
                                                       1                                              117 (32.2)   116 (32.1)     1 (50.0)
HADS-D, n (%)                                          0                                          0   297 (81.8)   295 (81.7)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1                                               66 (18.2)    66 (18.3)
3M New Depression Diagnosis , n (%)                    0.0                                        0   332 (91.5)   332 (92.0)                0.007     Fisher's exact         4.785
                                                       1.0                                              31 (8.5)     29 (8.0)    2 (100.0)
3M New Anxiety Diagnosis , n (%)                       0.0                                        0   331 (91.2)   330 (91.4)     1 (50.0)   0.169     Fisher's exact         1.022
                                                       1.0                                              32 (8.8)     31 (8.6)     1 (50.0)
3M New Substance Use Disorder, n (%)                   0.0                                        0   361 (99.4)   360 (99.7)     1 (50.0)   0.011     Fisher's exact         1.399
                                                       1.0                                               2 (0.6)      1 (0.3)     1 (50.0)
3M New Stroke, n (%)                                   0.0                                        0   356 (98.1)   354 (98.1)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                               7 (1.9)      7 (1.9)
3M New MI, n (%)                                       0.0                                        0   353 (97.2)   351 (97.2)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                              10 (2.8)     10 (2.8)
3M New CABG/Stent, n (%)                               0.0                                        0   331 (91.2)   329 (91.1)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                              32 (8.8)     32 (8.9)
3M Cardiac Rehab, n (%)                                0.0                                        0    87 (24.0)    86 (23.8)     1 (50.0)   0.422     Fisher's exact         0.564
                                                       1.0                                            276 (76.0)   275 (76.2)     1 (50.0)
3M Hospitalized , n (%)                                0.0                                        0   314 (86.5)   312 (86.4)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                             49 (13.5)    49 (13.6)
3M HADS-A, n (%)                                       0.0                                        0   251 (69.1)   251 (69.5)                0.095     Fisher's exact         2.136
                                                       1.0                                            112 (30.9)   110 (30.5)    2 (100.0)
3M HADS-D, n (%)                                       0.0                                        0   300 (82.6)   299 (82.8)     1 (50.0)   0.317     Fisher's exact         0.741
                                                       1.0                                             63 (17.4)    62 (17.2)     1 (50.0)
3M SF-12 (Low), n (%)                                  0.0                                        0   178 (49.0)   177 (49.0)     1 (50.0)   1.000     Fisher's exact         0.019
                                                       1.0                                            185 (51.0)   184 (51.0)     1 (50.0)
3M Cardiac Anxiety, n (%)                              0.0                                        0   311 (85.7)   310 (85.9)     1 (50.0)   0.266     Fisher's exact         0.833
                                                       1.0                                             52 (14.3)    51 (14.1)     1 (50.0)
3M MOS (Low Support), n (%)                            0.0                                        0   281 (77.4)   279 (77.3)    2 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                             82 (22.6)    82 (22.7)

6 Months, Outcome = 6M New Stroke

                                                           Grouped by 6M New Stroke
                                                                            Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                            363          358            5
Age, mean (SD)                                                                    0  67.7 (12.5)  67.6 (12.5)  72.6 (10.5)   0.351  Two Sample T-test         0.431
Race, n (%)                                            0                          0   337 (92.8)   332 (92.7)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                                26 (7.2)     26 (7.3)
Indigenous, n (%)                                      0                          0   352 (97.0)   347 (96.9)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                                11 (3.0)     11 (3.1)
Gender Identity, n (%)                                 0                          0   362 (99.7)   357 (99.7)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                                 1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                          0   330 (90.9)   325 (90.8)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                                33 (9.1)     33 (9.2)
Post- Secondary Education, n (%)                       0                          0   221 (60.9)   216 (60.3)    5 (100.0)   0.161     Fisher's exact           nan
                                                       1                              142 (39.1)   142 (39.7)
Employment, n (%)                                      0                          0   329 (90.6)   324 (90.5)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                                34 (9.4)     34 (9.5)
Household income before taxes, n (%)                   0.0                        0   203 (55.9)   200 (55.9)     3 (60.0)   1.000     Fisher's exact         0.084
                                                       1.0                            160 (44.1)   158 (44.1)     2 (40.0)
Marital status, n (%)                                  0                          0   180 (49.6)   179 (50.0)     1 (20.0)   0.372     Fisher's exact         0.663
                                                       1                              183 (50.4)   179 (50.0)     4 (80.0)
Living situation, n (%)                                0                          0   359 (98.9)   354 (98.9)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                                 4 (1.1)      4 (1.1)
Pack years, mean (SD)                                                             0  29.6 (65.4)  30.0 (65.8)    2.4 (2.9)  <0.001  Two Sample T-test        -0.592
Alcohol use - average number of drinks/week, mean (SD)                            0    1.6 (3.5)    1.6 (3.5)    3.8 (2.5)   0.118  Two Sample T-test         0.732
Substance Use Disorder, n (%)                          0                          0   361 (99.4)   356 (99.4)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                                 2 (0.6)      2 (0.6)
Depression, n (%)                                      0                          0   236 (65.0)   232 (64.8)     4 (80.0)   0.661     Fisher's exact         0.345
                                                       1                              127 (35.0)   126 (35.2)     1 (20.0)
Anxiety, n (%)                                         0                          0   253 (69.7)   249 (69.6)     4 (80.0)   1.000     Fisher's exact         0.242
                                                       1                              110 (30.3)   109 (30.4)     1 (20.0)
Health Anxiety, n (%)                                  0                          0   231 (63.6)   226 (63.1)    5 (100.0)   0.163     Fisher's exact           nan
                                                       1                              132 (36.4)   132 (36.9)
Delay to Hospital, n (%)                               0                          0   182 (50.1)   178 (49.7)     4 (80.0)   0.372     Fisher's exact         0.669
                                                       1                              181 (49.9)   180 (50.3)     1 (20.0)
Personal Stressors, n (%)                              0                          0   187 (51.5)   182 (50.8)    5 (100.0)   0.061     Fisher's exact           nan
                                                       1                              176 (48.5)   176 (49.2)
Menopause, n (%)                                       0                          0    76 (20.9)    74 (20.7)     2 (40.0)   0.282     Fisher's exact         0.430
                                                       1                              287 (79.1)   284 (79.3)     3 (60.0)
Complicated Pregnancy, n (%)                           0                          0   264 (72.7)   259 (72.3)    5 (100.0)   0.329     Fisher's exact           nan
                                                       1                               99 (27.3)    99 (27.7)
Stroke History, n (%)                                  0                          0   325 (89.5)   320 (89.4)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1                               38 (10.5)    38 (10.6)
MI History, n (%)                                      0                          0   295 (81.3)   292 (81.6)     3 (60.0)   0.236     Fisher's exact         0.488
                                                       1                               68 (18.7)    66 (18.4)     2 (40.0)
CABG/Stent History, n (%)                              0                          0   308 (84.8)   304 (84.9)     4 (80.0)   0.562     Fisher's exact         0.130
                                                       1                               55 (15.2)    54 (15.1)     1 (20.0)
High cholesterol, n (%)                                0                          0   149 (41.0)   148 (41.3)     1 (20.0)   0.652     Fisher's exact         0.476
                                                       1                              214 (59.0)   210 (58.7)     4 (80.0)
Diabetes, n (%)                                        0                          0   267 (73.6)   263 (73.5)     4 (80.0)   1.000     Fisher's exact         0.155
                                                       1                               96 (26.4)    95 (26.5)     1 (20.0)
Hypertension, n (%)                                    0                          0   143 (39.4)   140 (39.1)     3 (60.0)   0.386     Fisher's exact         0.427
                                                       1                              220 (60.6)   218 (60.9)     2 (40.0)
BMI, mean (SD)                                                                    0   28.8 (6.5)   28.8 (6.6)   27.2 (4.6)   0.486  Two Sample T-test        -0.281
HFrEF, n (%)                                           0                          0   210 (57.9)   206 (57.5)     4 (80.0)   0.402     Fisher's exact         0.499
                                                       1                              153 (42.1)   152 (42.5)     1 (20.0)
STEMI, n (%)                                           0                          0   208 (57.3)   203 (56.7)    5 (100.0)   0.074     Fisher's exact           nan
                                                       1                              155 (42.7)   155 (43.3)
ESSI score, n (%)                                      0                          0   248 (68.3)   246 (68.7)     2 (40.0)   0.332     Fisher's exact         0.602
                                                       1                              115 (31.7)   112 (31.3)     3 (60.0)
HADS-A, n (%)                                          0                          0   246 (67.8)   242 (67.6)     4 (80.0)   1.000     Fisher's exact         0.285
                                                       1                              117 (32.2)   116 (32.4)     1 (20.0)
HADS-D, n (%)                                          0                          0   297 (81.8)   292 (81.6)    5 (100.0)   0.590     Fisher's exact           nan
                                                       1                               66 (18.2)    66 (18.4)
3M New Depression Diagnosis , n (%)                    0.0                        0   332 (91.5)   327 (91.3)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                              31 (8.5)     31 (8.7)
3M New Anxiety Diagnosis , n (%)                       0.0                        0   331 (91.2)   327 (91.3)     4 (80.0)   0.371     Fisher's exact         0.328
                                                       1.0                              32 (8.8)     31 (8.7)     1 (20.0)
3M New Substance Use Disorder, n (%)                   0.0                        0   361 (99.4)   356 (99.4)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                               2 (0.6)      2 (0.6)
3M New Stroke, n (%)                                   0.0                        0   356 (98.1)   356 (99.4)               <0.001     Fisher's exact        18.868
                                                       1.0                               7 (1.9)      2 (0.6)    5 (100.0)
3M New MI, n (%)                                       0.0                        0   353 (97.2)   349 (97.5)     4 (80.0)   0.131     Fisher's exact         0.576
                                                       1.0                              10 (2.8)      9 (2.5)     1 (20.0)
3M New CABG/Stent, n (%)                               0.0                        0   331 (91.2)   326 (91.1)    5 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                              32 (8.8)     32 (8.9)
3M Cardiac Rehab, n (%)                                0.0                        0    87 (24.0)    85 (23.7)     2 (40.0)   0.597     Fisher's exact         0.354
                                                       1.0                            276 (76.0)   273 (76.3)     3 (60.0)
3M Hospitalized , n (%)                                0.0                        0   314 (86.5)   312 (87.2)     2 (40.0)   0.019     Fisher's exact         1.124
                                                       1.0                             49 (13.5)    46 (12.8)     3 (60.0)
3M HADS-A, n (%)                                       0.0                        0   251 (69.1)   247 (69.0)     4 (80.0)   1.000     Fisher's exact         0.255
                                                       1.0                            112 (30.9)   111 (31.0)     1 (20.0)
3M HADS-D, n (%)                                       0.0                        0   300 (82.6)   296 (82.7)     4 (80.0)   1.000     Fisher's exact         0.069
                                                       1.0                             63 (17.4)    62 (17.3)     1 (20.0)
3M SF-12 (Low), n (%)                                  0.0                        0   178 (49.0)   176 (49.2)     2 (40.0)   1.000     Fisher's exact         0.185
                                                       1.0                            185 (51.0)   182 (50.8)     3 (60.0)
3M Cardiac Anxiety, n (%)                              0.0                        0   311 (85.7)   307 (85.8)     4 (80.0)   0.541     Fisher's exact         0.153
                                                       1.0                             52 (14.3)    51 (14.2)     1 (20.0)
3M MOS (Low Support), n (%)                            0.0                        0   281 (77.4)   276 (77.1)    5 (100.0)   0.592     Fisher's exact           nan
                                                       1.0                             82 (22.6)    82 (22.9)

6 Months, Outcome = 6M New MI

                                                           Grouped by 6M New MI
                                                                        Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                        363          357            6
Age, mean (SD)                                                                0  67.7 (12.5)  67.7 (12.5)  67.2 (15.3)   0.935  Two Sample T-test        -0.039
Race, n (%)                                            0                      0   337 (92.8)   332 (93.0)     5 (83.3)   0.362     Fisher's exact         0.303
                                                       1                            26 (7.2)     25 (7.0)     1 (16.7)
Indigenous, n (%)                                      0                      0   352 (97.0)   347 (97.2)     5 (83.3)   0.170     Fisher's exact         0.481
                                                       1                            11 (3.0)     10 (2.8)     1 (16.7)
Gender Identity, n (%)                                 0                      0   362 (99.7)   356 (99.7)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1                             1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                      0   330 (90.9)   325 (91.0)     5 (83.3)   0.438     Fisher's exact         0.232
                                                       1                            33 (9.1)     32 (9.0)     1 (16.7)
Post- Secondary Education, n (%)                       0                      0   221 (60.9)   216 (60.5)     5 (83.3)   0.410     Fisher's exact         0.525
                                                       1                          142 (39.1)   141 (39.5)     1 (16.7)
Employment, n (%)                                      0                      0   329 (90.6)   323 (90.5)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1                            34 (9.4)     34 (9.5)
Household income before taxes, n (%)                   0.0                    0   203 (55.9)   201 (56.3)     2 (33.3)   0.412     Fisher's exact         0.475
                                                       1.0                        160 (44.1)   156 (43.7)     4 (66.7)
Marital status, n (%)                                  0                      0   180 (49.6)   179 (50.1)     1 (16.7)   0.215     Fisher's exact         0.759
                                                       1                          183 (50.4)   178 (49.9)     5 (83.3)
Living situation, n (%)                                0                      0   359 (98.9)   353 (98.9)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1                             4 (1.1)      4 (1.1)
Pack years, mean (SD)                                                         0  29.6 (65.4)  29.9 (65.9)  10.5 (12.8)   0.011  Two Sample T-test        -0.409
Alcohol use - average number of drinks/week, mean (SD)                        0    1.6 (3.5)    1.6 (3.5)    1.8 (3.3)   0.879  Two Sample T-test         0.064
Substance Use Disorder, n (%)                          0                      0   361 (99.4)   355 (99.4)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1                             2 (0.6)      2 (0.6)
Depression, n (%)                                      0                      0   236 (65.0)   232 (65.0)     4 (66.7)   1.000     Fisher's exact         0.035
                                                       1                          127 (35.0)   125 (35.0)     2 (33.3)
Anxiety, n (%)                                         0                      0   253 (69.7)   249 (69.7)     4 (66.7)   1.000     Fisher's exact         0.066
                                                       1                          110 (30.3)   108 (30.3)     2 (33.3)
Health Anxiety, n (%)                                  0                      0   231 (63.6)   225 (63.0)    6 (100.0)   0.090     Fisher's exact           nan
                                                       1                          132 (36.4)   132 (37.0)
Delay to Hospital, n (%)                               0                      0   182 (50.1)   178 (49.9)     4 (66.7)   0.685     Fisher's exact         0.346
                                                       1                          181 (49.9)   179 (50.1)     2 (33.3)
Personal Stressors, n (%)                              0                      0   187 (51.5)   183 (51.3)     4 (66.7)   0.686     Fisher's exact         0.317
                                                       1                          176 (48.5)   174 (48.7)     2 (33.3)
Menopause, n (%)                                       0                      0    76 (20.9)    74 (20.7)     2 (33.3)   0.609     Fisher's exact         0.287
                                                       1                          287 (79.1)   283 (79.3)     4 (66.7)
Complicated Pregnancy, n (%)                           0                      0   264 (72.7)   260 (72.8)     4 (66.7)   0.666     Fisher's exact         0.134
                                                       1                           99 (27.3)    97 (27.2)     2 (33.3)
Stroke History, n (%)                                  0                      0   325 (89.5)   322 (90.2)     3 (50.0)   0.017     Fisher's exact         0.977
                                                       1                           38 (10.5)     35 (9.8)     3 (50.0)
MI History, n (%)                                      0                      0   295 (81.3)   291 (81.5)     4 (66.7)   0.313     Fisher's exact         0.344
                                                       1                           68 (18.7)    66 (18.5)     2 (33.3)
CABG/Stent History, n (%)                              0                      0   308 (84.8)   303 (84.9)     5 (83.3)   1.000     Fisher's exact         0.042
                                                       1                           55 (15.2)    54 (15.1)     1 (16.7)
High cholesterol, n (%)                                0                      0   149 (41.0)   147 (41.2)     2 (33.3)   1.000     Fisher's exact         0.163
                                                       1                          214 (59.0)   210 (58.8)     4 (66.7)
Diabetes, n (%)                                        0                      0   267 (73.6)   261 (73.1)    6 (100.0)   0.347     Fisher's exact           nan
                                                       1                           96 (26.4)    96 (26.9)
Hypertension, n (%)                                    0                      0   143 (39.4)   141 (39.5)     2 (33.3)   1.000     Fisher's exact         0.128
                                                       1                          220 (60.6)   216 (60.5)     4 (66.7)
BMI, mean (SD)                                                                0   28.8 (6.5)   28.8 (6.6)   27.2 (5.0)   0.469  Two Sample T-test        -0.277
HFrEF, n (%)                                           0                      0   210 (57.9)   206 (57.7)     4 (66.7)   1.000     Fisher's exact         0.186
                                                       1                          153 (42.1)   151 (42.3)     2 (33.3)
STEMI, n (%)                                           0                      0   208 (57.3)   204 (57.1)     4 (66.7)   1.000     Fisher's exact         0.197
                                                       1                          155 (42.7)   153 (42.9)     2 (33.3)
ESSI score, n (%)                                      0                      0   248 (68.3)   244 (68.3)     4 (66.7)   1.000     Fisher's exact         0.036
                                                       1                          115 (31.7)   113 (31.7)     2 (33.3)
HADS-A, n (%)                                          0                      0   246 (67.8)   242 (67.8)     4 (66.7)   1.000     Fisher's exact         0.024
                                                       1                          117 (32.2)   115 (32.2)     2 (33.3)
HADS-D, n (%)                                          0                      0   297 (81.8)   292 (81.8)     5 (83.3)   1.000     Fisher's exact         0.041
                                                       1                           66 (18.2)    65 (18.2)     1 (16.7)
3M New Depression Diagnosis , n (%)                    0.0                    0   332 (91.5)   327 (91.6)     5 (83.3)   0.417     Fisher's exact         0.252
                                                       1.0                          31 (8.5)     30 (8.4)     1 (16.7)
3M New Anxiety Diagnosis , n (%)                       0.0                    0   331 (91.2)   325 (91.0)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                          32 (8.8)     32 (9.0)
3M New Substance Use Disorder, n (%)                   0.0                    0   361 (99.4)   355 (99.4)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                           2 (0.6)      2 (0.6)
3M New Stroke, n (%)                                   0.0                    0   356 (98.1)   350 (98.0)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                           7 (1.9)      7 (2.0)
3M New MI, n (%)                                       0.0                    0   353 (97.2)   347 (97.2)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                          10 (2.8)     10 (2.8)
3M New CABG/Stent, n (%)                               0.0                    0   331 (91.2)   325 (91.0)    6 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                          32 (8.8)     32 (9.0)
3M Cardiac Rehab, n (%)                                0.0                    0    87 (24.0)    85 (23.8)     2 (33.3)   0.633     Fisher's exact         0.212
                                                       1.0                        276 (76.0)   272 (76.2)     4 (66.7)
3M Hospitalized , n (%)                                0.0                    0   314 (86.5)   310 (86.8)     4 (66.7)   0.188     Fisher's exact         0.492
                                                       1.0                         49 (13.5)    47 (13.2)     2 (33.3)
3M HADS-A, n (%)                                       0.0                    0   251 (69.1)   246 (68.9)     5 (83.3)   0.671     Fisher's exact         0.343
                                                       1.0                        112 (30.9)   111 (31.1)     1 (16.7)
3M HADS-D, n (%)                                       0.0                    0   300 (82.6)   296 (82.9)     4 (66.7)   0.279     Fisher's exact         0.381
                                                       1.0                         63 (17.4)    61 (17.1)     2 (33.3)
3M SF-12 (Low), n (%)                                  0.0                    0   178 (49.0)   175 (49.0)     3 (50.0)   1.000     Fisher's exact         0.020
                                                       1.0                        185 (51.0)   182 (51.0)     3 (50.0)
3M Cardiac Anxiety, n (%)                              0.0                    0   311 (85.7)   305 (85.4)    6 (100.0)   0.600     Fisher's exact           nan
                                                       1.0                         52 (14.3)    52 (14.6)
3M MOS (Low Support), n (%)                            0.0                    0   281 (77.4)   277 (77.6)     4 (66.7)   0.621     Fisher's exact         0.245
                                                       1.0                         82 (22.6)    80 (22.4)     2 (33.3)

6 Months, Outcome = 6M New CABG/Stent

                                                           Grouped by 6M New CABG/Stent
                                                                                Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                363          347           16
Age, mean (SD)                                                                        0  67.7 (12.5)  67.8 (12.7)   65.8 (7.8)   0.350  Two Sample T-test        -0.188
Race, n (%)                                            0                              0   337 (92.8)   322 (92.8)    15 (93.8)   1.000     Fisher's exact         0.038
                                                       1                                    26 (7.2)     25 (7.2)      1 (6.2)
Indigenous, n (%)                                      0                              0   352 (97.0)   336 (96.8)   16 (100.0)   1.000     Fisher's exact           nan
                                                       1                                    11 (3.0)     11 (3.2)
Gender Identity, n (%)                                 0                              0   362 (99.7)   346 (99.7)   16 (100.0)   1.000     Fisher's exact           nan
                                                       1                                     1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                              0   330 (90.9)   315 (90.8)    15 (93.8)   1.000     Fisher's exact         0.111
                                                       1                                    33 (9.1)     32 (9.2)      1 (6.2)
Post- Secondary Education, n (%)                       0                              0   221 (60.9)   208 (59.9)    13 (81.2)   0.148        Chi-squared         0.481
                                                       1                                  142 (39.1)   139 (40.1)     3 (18.8)
Employment, n (%)                                      0                              0   329 (90.6)   313 (90.2)   16 (100.0)   0.381     Fisher's exact           nan
                                                       1                                    34 (9.4)     34 (9.8)
Household income before taxes, n (%)                   0.0                            0   203 (55.9)   194 (55.9)     9 (56.2)   1.000        Chi-squared         0.007
                                                       1.0                                160 (44.1)   153 (44.1)     7 (43.8)
Marital status, n (%)                                  0                              0   180 (49.6)   174 (50.1)     6 (37.5)   0.463        Chi-squared         0.257
                                                       1                                  183 (50.4)   173 (49.9)    10 (62.5)
Living situation, n (%)                                0                              0   359 (98.9)   343 (98.8)   16 (100.0)   1.000     Fisher's exact           nan
                                                       1                                     4 (1.1)      4 (1.2)
Pack years, mean (SD)                                                                 0  29.6 (65.4)  30.3 (66.8)  14.7 (15.8)   0.005  Two Sample T-test        -0.321
Alcohol use - average number of drinks/week, mean (SD)                                0    1.6 (3.5)    1.6 (3.4)    2.6 (5.2)   0.457  Two Sample T-test         0.228
Substance Use Disorder, n (%)                          0                              0   361 (99.4)   345 (99.4)   16 (100.0)   1.000     Fisher's exact           nan
                                                       1                                     2 (0.6)      2 (0.6)
Depression, n (%)                                      0                              0   236 (65.0)   227 (65.4)     9 (56.2)   0.629        Chi-squared         0.189
                                                       1                                  127 (35.0)   120 (34.6)     7 (43.8)
Anxiety, n (%)                                         0                              0   253 (69.7)   246 (70.9)     7 (43.8)   0.027     Fisher's exact         0.571
                                                       1                                  110 (30.3)   101 (29.1)     9 (56.2)
Health Anxiety, n (%)                                  0                              0   231 (63.6)   221 (63.7)    10 (62.5)   1.000        Chi-squared         0.025
                                                       1                                  132 (36.4)   126 (36.3)     6 (37.5)
Delay to Hospital, n (%)                               0                              0   182 (50.1)   180 (51.9)     2 (12.5)   0.005        Chi-squared         0.929
                                                       1                                  181 (49.9)   167 (48.1)    14 (87.5)
Personal Stressors, n (%)                              0                              0   187 (51.5)   178 (51.3)     9 (56.2)   0.895        Chi-squared         0.099
                                                       1                                  176 (48.5)   169 (48.7)     7 (43.8)
Menopause, n (%)                                       0                              0    76 (20.9)    74 (21.3)     2 (12.5)   0.539     Fisher's exact         0.237
                                                       1                                  287 (79.1)   273 (78.7)    14 (87.5)
Complicated Pregnancy, n (%)                           0                              0   264 (72.7)   250 (72.0)    14 (87.5)   0.253     Fisher's exact         0.392
                                                       1                                   99 (27.3)    97 (28.0)     2 (12.5)
Stroke History, n (%)                                  0                              0   325 (89.5)   311 (89.6)    14 (87.5)   0.679     Fisher's exact         0.067
                                                       1                                   38 (10.5)    36 (10.4)     2 (12.5)
MI History, n (%)                                      0                              0   295 (81.3)   281 (81.0)    14 (87.5)   0.746     Fisher's exact         0.180
                                                       1                                   68 (18.7)    66 (19.0)     2 (12.5)
CABG/Stent History, n (%)                              0                              0   308 (84.8)   297 (85.6)    11 (68.8)   0.077     Fisher's exact         0.410
                                                       1                                   55 (15.2)    50 (14.4)     5 (31.2)
High cholesterol, n (%)                                0                              0   149 (41.0)   144 (41.5)     5 (31.2)   0.579        Chi-squared         0.214
                                                       1                                  214 (59.0)   203 (58.5)    11 (68.8)
Diabetes, n (%)                                        0                              0   267 (73.6)   254 (73.2)    13 (81.2)   0.575     Fisher's exact         0.193
                                                       1                                   96 (26.4)    93 (26.8)     3 (18.8)
Hypertension, n (%)                                    0                              0   143 (39.4)   141 (40.6)     2 (12.5)   0.047        Chi-squared         0.672
                                                       1                                  220 (60.6)   206 (59.4)    14 (87.5)
BMI, mean (SD)                                                                        0   28.8 (6.5)   28.7 (6.6)   30.7 (5.3)   0.170  Two Sample T-test         0.329
HFrEF, n (%)                                           0                              0   210 (57.9)   199 (57.3)    11 (68.8)   0.520        Chi-squared         0.238
                                                       1                                  153 (42.1)   148 (42.7)     5 (31.2)
STEMI, n (%)                                           0                              0   208 (57.3)   198 (57.1)    10 (62.5)   0.864        Chi-squared         0.111
                                                       1                                  155 (42.7)   149 (42.9)     6 (37.5)
ESSI score, n (%)                                      0                              0   248 (68.3)   234 (67.4)    14 (87.5)   0.158        Chi-squared         0.495
                                                       1                                  115 (31.7)   113 (32.6)     2 (12.5)
HADS-A, n (%)                                          0                              0   246 (67.8)   238 (68.6)     8 (50.0)   0.200        Chi-squared         0.385
                                                       1                                  117 (32.2)   109 (31.4)     8 (50.0)
HADS-D, n (%)                                          0                              0   297 (81.8)   286 (82.4)    11 (68.8)   0.183     Fisher's exact         0.322
                                                       1                                   66 (18.2)    61 (17.6)     5 (31.2)
3M New Depression Diagnosis , n (%)                    0.0                            0   332 (91.5)   320 (92.2)    12 (75.0)   0.038     Fisher's exact         0.478
                                                       1.0                                  31 (8.5)     27 (7.8)     4 (25.0)
3M New Anxiety Diagnosis , n (%)                       0.0                            0   331 (91.2)   318 (91.6)    13 (81.2)   0.158     Fisher's exact         0.307
                                                       1.0                                  32 (8.8)     29 (8.4)     3 (18.8)
3M New Substance Use Disorder, n (%)                   0.0                            0   361 (99.4)   346 (99.7)    15 (93.8)   0.086     Fisher's exact         0.340
                                                       1.0                                   2 (0.6)      1 (0.3)      1 (6.2)
3M New Stroke, n (%)                                   0.0                            0   356 (98.1)   340 (98.0)   16 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                   7 (1.9)      7 (2.0)
3M New MI, n (%)                                       0.0                            0   353 (97.2)   338 (97.4)    15 (93.8)   0.367     Fisher's exact         0.179
                                                       1.0                                  10 (2.8)      9 (2.6)      1 (6.2)
3M New CABG/Stent, n (%)                               0.0                            0   331 (91.2)   319 (91.9)    12 (75.0)   0.043     Fisher's exact         0.468
                                                       1.0                                  32 (8.8)     28 (8.1)     4 (25.0)
3M Cardiac Rehab, n (%)                                0.0                            0    87 (24.0)    84 (24.2)     3 (18.8)   0.771     Fisher's exact         0.133
                                                       1.0                                276 (76.0)   263 (75.8)    13 (81.2)
3M Hospitalized , n (%)                                0.0                            0   314 (86.5)   303 (87.3)    11 (68.8)   0.050     Fisher's exact         0.460
                                                       1.0                                 49 (13.5)    44 (12.7)     5 (31.2)
3M HADS-A, n (%)                                       0.0                            0   251 (69.1)   242 (69.7)     9 (56.2)   0.274     Fisher's exact         0.282
                                                       1.0                                112 (30.9)   105 (30.3)     7 (43.8)
3M HADS-D, n (%)                                       0.0                            0   300 (82.6)   285 (82.1)    15 (93.8)   0.325     Fisher's exact         0.363
                                                       1.0                                 63 (17.4)    62 (17.9)      1 (6.2)
3M SF-12 (Low), n (%)                                  0.0                            0   178 (49.0)   171 (49.3)     7 (43.8)   0.860        Chi-squared         0.111
                                                       1.0                                185 (51.0)   176 (50.7)     9 (56.2)
3M Cardiac Anxiety, n (%)                              0.0                            0   311 (85.7)   300 (86.5)    11 (68.8)   0.063     Fisher's exact         0.435
                                                       1.0                                 52 (14.3)    47 (13.5)     5 (31.2)
3M MOS (Low Support), n (%)                            0.0                            0   281 (77.4)   266 (76.7)    15 (93.8)   0.135     Fisher's exact         0.496
                                                       1.0                                 82 (22.6)    81 (23.3)      1 (6.2)

6 Months, Outcome = 6M Cardiac Rehab

                                                           Grouped by 6M Cardiac Rehab
                                                                               Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                               363          103          260
Age, mean (SD)                                                                       0  67.7 (12.5)  66.3 (11.5)  68.2 (12.8)   0.177  Two Sample T-test         0.154
Race, n (%)                                            0                             0   337 (92.8)    96 (93.2)   241 (92.7)   1.000        Chi-squared         0.020
                                                       1                                   26 (7.2)      7 (6.8)     19 (7.3)
Indigenous, n (%)                                      0                             0   352 (97.0)   101 (98.1)   251 (96.5)   0.735     Fisher's exact         0.094
                                                       1                                   11 (3.0)      2 (1.9)      9 (3.5)
Gender Identity, n (%)                                 0                             0   362 (99.7)   102 (99.0)  260 (100.0)   0.284     Fisher's exact           nan
                                                       1                                    1 (0.3)      1 (1.0)
Highschool Education, n (%)                            0                             0   330 (90.9)    98 (95.1)   232 (89.2)   0.118        Chi-squared         0.222
                                                       1                                   33 (9.1)      5 (4.9)    28 (10.8)
Post- Secondary Education, n (%)                       0                             0   221 (60.9)    72 (69.9)   149 (57.3)   0.036        Chi-squared         0.264
                                                       1                                 142 (39.1)    31 (30.1)   111 (42.7)
Employment, n (%)                                      0                             0   329 (90.6)    94 (91.3)   235 (90.4)   0.953        Chi-squared         0.030
                                                       1                                   34 (9.4)      9 (8.7)     25 (9.6)
Household income before taxes, n (%)                   0.0                           0   203 (55.9)    68 (66.0)   135 (51.9)   0.020        Chi-squared         0.290
                                                       1.0                               160 (44.1)    35 (34.0)   125 (48.1)
Marital status, n (%)                                  0                             0   180 (49.6)    61 (59.2)   119 (45.8)   0.028        Chi-squared         0.272
                                                       1                                 183 (50.4)    42 (40.8)   141 (54.2)
Living situation, n (%)                                0                             0   359 (98.9)  103 (100.0)   256 (98.5)   0.581     Fisher's exact           nan
                                                       1                                    4 (1.1)                   4 (1.5)
Pack years, mean (SD)                                                                0  29.6 (65.4)  33.2 (75.7)  28.1 (61.0)   0.542  Two Sample T-test        -0.074
Alcohol use - average number of drinks/week, mean (SD)                               0    1.6 (3.5)    2.0 (3.4)    1.5 (3.5)   0.152  Two Sample T-test        -0.167
Substance Use Disorder, n (%)                          0                             0   361 (99.4)   102 (99.0)   259 (99.6)   0.488     Fisher's exact         0.072
                                                       1                                    2 (0.6)      1 (1.0)      1 (0.4)
Depression, n (%)                                      0                             0   236 (65.0)    74 (71.8)   162 (62.3)   0.111        Chi-squared         0.204
                                                       1                                 127 (35.0)    29 (28.2)    98 (37.7)
Anxiety, n (%)                                         0                             0   253 (69.7)    79 (76.7)   174 (66.9)   0.089        Chi-squared         0.219
                                                       1                                 110 (30.3)    24 (23.3)    86 (33.1)
Health Anxiety, n (%)                                  0                             0   231 (63.6)    63 (61.2)   168 (64.6)   0.621        Chi-squared         0.071
                                                       1                                 132 (36.4)    40 (38.8)    92 (35.4)
Delay to Hospital, n (%)                               0                             0   182 (50.1)    51 (49.5)   131 (50.4)   0.974        Chi-squared         0.017
                                                       1                                 181 (49.9)    52 (50.5)   129 (49.6)
Personal Stressors, n (%)                              0                             0   187 (51.5)    43 (41.7)   144 (55.4)   0.026        Chi-squared         0.275
                                                       1                                 176 (48.5)    60 (58.3)   116 (44.6)
Menopause, n (%)                                       0                             0    76 (20.9)    23 (22.3)    53 (20.4)   0.789        Chi-squared         0.047
                                                       1                                 287 (79.1)    80 (77.7)   207 (79.6)
Complicated Pregnancy, n (%)                           0                             0   264 (72.7)    81 (78.6)   183 (70.4)   0.144        Chi-squared         0.190
                                                       1                                  99 (27.3)    22 (21.4)    77 (29.6)
Stroke History, n (%)                                  0                             0   325 (89.5)    94 (91.3)   231 (88.8)   0.626        Chi-squared         0.081
                                                       1                                  38 (10.5)      9 (8.7)    29 (11.2)
MI History, n (%)                                      0                             0   295 (81.3)    84 (81.6)   211 (81.2)   1.000        Chi-squared         0.010
                                                       1                                  68 (18.7)    19 (18.4)    49 (18.8)
CABG/Stent History, n (%)                              0                             0   308 (84.8)    88 (85.4)   220 (84.6)   0.973        Chi-squared         0.023
                                                       1                                  55 (15.2)    15 (14.6)    40 (15.4)
High cholesterol, n (%)                                0                             0   149 (41.0)    34 (33.0)   115 (44.2)   0.066        Chi-squared         0.232
                                                       1                                 214 (59.0)    69 (67.0)   145 (55.8)
Diabetes, n (%)                                        0                             0   267 (73.6)    75 (72.8)   192 (73.8)   0.945        Chi-squared         0.023
                                                       1                                  96 (26.4)    28 (27.2)    68 (26.2)
Hypertension, n (%)                                    0                             0   143 (39.4)    39 (37.9)   104 (40.0)   0.798        Chi-squared         0.044
                                                       1                                 220 (60.6)    64 (62.1)   156 (60.0)
BMI, mean (SD)                                                                       0   28.8 (6.5)   29.1 (5.9)   28.7 (6.8)   0.521  Two Sample T-test        -0.073
HFrEF, n (%)                                           0                             0   210 (57.9)    49 (47.6)   161 (61.9)   0.017        Chi-squared         0.291
                                                       1                                 153 (42.1)    54 (52.4)    99 (38.1)
STEMI, n (%)                                           0                             0   208 (57.3)    45 (43.7)   163 (62.7)   0.001        Chi-squared         0.388
                                                       1                                 155 (42.7)    58 (56.3)    97 (37.3)
ESSI score, n (%)                                      0                             0   248 (68.3)    69 (67.0)   179 (68.8)   0.828        Chi-squared         0.040
                                                       1                                 115 (31.7)    34 (33.0)    81 (31.2)
HADS-A, n (%)                                          0                             0   246 (67.8)    75 (72.8)   171 (65.8)   0.242        Chi-squared         0.153
                                                       1                                 117 (32.2)    28 (27.2)    89 (34.2)
HADS-D, n (%)                                          0                             0   297 (81.8)    86 (83.5)   211 (81.2)   0.711        Chi-squared         0.061
                                                       1                                  66 (18.2)    17 (16.5)    49 (18.8)
3M New Depression Diagnosis , n (%)                    0.0                           0   332 (91.5)    95 (92.2)   237 (91.2)   0.902        Chi-squared         0.039
                                                       1.0                                 31 (8.5)      8 (7.8)     23 (8.8)
3M New Anxiety Diagnosis , n (%)                       0.0                           0   331 (91.2)    91 (88.3)   240 (92.3)   0.320        Chi-squared         0.134
                                                       1.0                                 32 (8.8)    12 (11.7)     20 (7.7)
3M New Substance Use Disorder, n (%)                   0.0                           0   361 (99.4)   101 (98.1)  260 (100.0)   0.080     Fisher's exact           nan
                                                       1.0                                  2 (0.6)      2 (1.9)
3M New Stroke, n (%)                                   0.0                           0   356 (98.1)   100 (97.1)   256 (98.5)   0.410     Fisher's exact         0.093
                                                       1.0                                  7 (1.9)      3 (2.9)      4 (1.5)
3M New MI, n (%)                                       0.0                           0   353 (97.2)   100 (97.1)   253 (97.3)   1.000     Fisher's exact         0.013
                                                       1.0                                 10 (2.8)      3 (2.9)      7 (2.7)
3M New CABG/Stent, n (%)                               0.0                           0   331 (91.2)    92 (89.3)   239 (91.9)   0.560        Chi-squared         0.089
                                                       1.0                                 32 (8.8)    11 (10.7)     21 (8.1)
3M Cardiac Rehab, n (%)                                0.0                           0    87 (24.0)    65 (63.1)     22 (8.5)  <0.001        Chi-squared         1.387
                                                       1.0                               276 (76.0)    38 (36.9)   238 (91.5)
3M Hospitalized , n (%)                                0.0                           0   314 (86.5)    90 (87.4)   224 (86.2)   0.891        Chi-squared         0.036
                                                       1.0                                49 (13.5)    13 (12.6)    36 (13.8)
3M HADS-A, n (%)                                       0.0                           0   251 (69.1)    78 (75.7)   173 (66.5)   0.113        Chi-squared         0.204
                                                       1.0                               112 (30.9)    25 (24.3)    87 (33.5)
3M HADS-D, n (%)                                       0.0                           0   300 (82.6)    89 (86.4)   211 (81.2)   0.299        Chi-squared         0.143
                                                       1.0                                63 (17.4)    14 (13.6)    49 (18.8)
3M SF-12 (Low), n (%)                                  0.0                           0   178 (49.0)    50 (48.5)   128 (49.2)   0.999        Chi-squared         0.014
                                                       1.0                               185 (51.0)    53 (51.5)   132 (50.8)
3M Cardiac Anxiety, n (%)                              0.0                           0   311 (85.7)    90 (87.4)   221 (85.0)   0.677        Chi-squared         0.069
                                                       1.0                                52 (14.3)    13 (12.6)    39 (15.0)
3M MOS (Low Support), n (%)                            0.0                           0   281 (77.4)    77 (74.8)   204 (78.5)   0.534        Chi-squared         0.088
                                                       1.0                                82 (22.6)    26 (25.2)    56 (21.5)

6 Months, Outcome = 6M Hospitalized

                                                           Grouped by 6M Hospitalized
                                                                               Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                               363          318           45
Age, mean (SD)                                                                       0  67.7 (12.5)  67.7 (12.4)  67.9 (13.0)   0.916  Two Sample T-test         0.017
Race, n (%)                                            0                             0   337 (92.8)   298 (93.7)    39 (86.7)   0.114     Fisher's exact         0.238
                                                       1                                   26 (7.2)     20 (6.3)     6 (13.3)
Indigenous, n (%)                                      0                             0   352 (97.0)   309 (97.2)    43 (95.6)   0.633     Fisher's exact         0.086
                                                       1                                   11 (3.0)      9 (2.8)      2 (4.4)
Gender Identity, n (%)                                 0                             0   362 (99.7)   317 (99.7)   45 (100.0)   1.000     Fisher's exact           nan
                                                       1                                    1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                             0   330 (90.9)   288 (90.6)    42 (93.3)   0.782     Fisher's exact         0.102
                                                       1                                   33 (9.1)     30 (9.4)      3 (6.7)
Post- Secondary Education, n (%)                       0                             0   221 (60.9)   194 (61.0)    27 (60.0)   1.000        Chi-squared         0.021
                                                       1                                 142 (39.1)   124 (39.0)    18 (40.0)
Employment, n (%)                                      0                             0   329 (90.6)   289 (90.9)    40 (88.9)   0.592     Fisher's exact         0.066
                                                       1                                   34 (9.4)     29 (9.1)     5 (11.1)
Household income before taxes, n (%)                   0.0                           0   203 (55.9)   177 (55.7)    26 (57.8)   0.914        Chi-squared         0.043
                                                       1.0                               160 (44.1)   141 (44.3)    19 (42.2)
Marital status, n (%)                                  0                             0   180 (49.6)   164 (51.6)    16 (35.6)   0.064        Chi-squared         0.327
                                                       1                                 183 (50.4)   154 (48.4)    29 (64.4)
Living situation, n (%)                                0                             0   359 (98.9)   315 (99.1)    44 (97.8)   0.412     Fisher's exact         0.103
                                                       1                                    4 (1.1)      3 (0.9)      1 (2.2)
Pack years, mean (SD)                                                                0  29.6 (65.4)  31.9 (69.3)  13.5 (17.6)  <0.001  Two Sample T-test        -0.364
Alcohol use - average number of drinks/week, mean (SD)                               0    1.6 (3.5)    1.5 (3.4)    2.2 (3.8)   0.282  Two Sample T-test         0.180
Substance Use Disorder, n (%)                          0                             0   361 (99.4)   317 (99.7)    44 (97.8)   0.233     Fisher's exact         0.171
                                                       1                                    2 (0.6)      1 (0.3)      1 (2.2)
Depression, n (%)                                      0                             0   236 (65.0)   208 (65.4)    28 (62.2)   0.801        Chi-squared         0.066
                                                       1                                 127 (35.0)   110 (34.6)    17 (37.8)
Anxiety, n (%)                                         0                             0   253 (69.7)   226 (71.1)    27 (60.0)   0.181        Chi-squared         0.235
                                                       1                                 110 (30.3)    92 (28.9)    18 (40.0)
Health Anxiety, n (%)                                  0                             0   231 (63.6)   200 (62.9)    31 (68.9)   0.537        Chi-squared         0.127
                                                       1                                 132 (36.4)   118 (37.1)    14 (31.1)
Delay to Hospital, n (%)                               0                             0   182 (50.1)   160 (50.3)    22 (48.9)   0.984        Chi-squared         0.029
                                                       1                                 181 (49.9)   158 (49.7)    23 (51.1)
Personal Stressors, n (%)                              0                             0   187 (51.5)   167 (52.5)    20 (44.4)   0.393        Chi-squared         0.162
                                                       1                                 176 (48.5)   151 (47.5)    25 (55.6)
Menopause, n (%)                                       0                             0    76 (20.9)    61 (19.2)    15 (33.3)   0.047        Chi-squared         0.326
                                                       1                                 287 (79.1)   257 (80.8)    30 (66.7)
Complicated Pregnancy, n (%)                           0                             0   264 (72.7)   233 (73.3)    31 (68.9)   0.661        Chi-squared         0.097
                                                       1                                  99 (27.3)    85 (26.7)    14 (31.1)
Stroke History, n (%)                                  0                             0   325 (89.5)   291 (91.5)    34 (75.6)   0.003     Fisher's exact         0.440
                                                       1                                  38 (10.5)     27 (8.5)    11 (24.4)
MI History, n (%)                                      0                             0   295 (81.3)   265 (83.3)    30 (66.7)   0.013        Chi-squared         0.392
                                                       1                                  68 (18.7)    53 (16.7)    15 (33.3)
CABG/Stent History, n (%)                              0                             0   308 (84.8)   274 (86.2)    34 (75.6)   0.102        Chi-squared         0.272
                                                       1                                  55 (15.2)    44 (13.8)    11 (24.4)
High cholesterol, n (%)                                0                             0   149 (41.0)   136 (42.8)    13 (28.9)   0.108        Chi-squared         0.293
                                                       1                                 214 (59.0)   182 (57.2)    32 (71.1)
Diabetes, n (%)                                        0                             0   267 (73.6)   235 (73.9)    32 (71.1)   0.829        Chi-squared         0.062
                                                       1                                  96 (26.4)    83 (26.1)    13 (28.9)
Hypertension, n (%)                                    0                             0   143 (39.4)   129 (40.6)    14 (31.1)   0.293        Chi-squared         0.198
                                                       1                                 220 (60.6)   189 (59.4)    31 (68.9)
BMI, mean (SD)                                                                       0   28.8 (6.5)   28.8 (6.5)   29.0 (7.3)   0.868  Two Sample T-test         0.028
HFrEF, n (%)                                           0                             0   210 (57.9)   189 (59.4)    21 (46.7)   0.144        Chi-squared         0.258
                                                       1                                 153 (42.1)   129 (40.6)    24 (53.3)
STEMI, n (%)                                           0                             0   208 (57.3)   180 (56.6)    28 (62.2)   0.581        Chi-squared         0.115
                                                       1                                 155 (42.7)   138 (43.4)    17 (37.8)
ESSI score, n (%)                                      0                             0   248 (68.3)   219 (68.9)    29 (64.4)   0.670        Chi-squared         0.094
                                                       1                                 115 (31.7)    99 (31.1)    16 (35.6)
HADS-A, n (%)                                          0                             0   246 (67.8)   219 (68.9)    27 (60.0)   0.307        Chi-squared         0.186
                                                       1                                 117 (32.2)    99 (31.1)    18 (40.0)
HADS-D, n (%)                                          0                             0   297 (81.8)   261 (82.1)    36 (80.0)   0.895        Chi-squared         0.053
                                                       1                                  66 (18.2)    57 (17.9)     9 (20.0)
3M New Depression Diagnosis , n (%)                    0.0                           0   332 (91.5)   292 (91.8)    40 (88.9)   0.566     Fisher's exact         0.100
                                                       1.0                                 31 (8.5)     26 (8.2)     5 (11.1)
3M New Anxiety Diagnosis , n (%)                       0.0                           0   331 (91.2)   289 (90.9)    42 (93.3)   0.781     Fisher's exact         0.091
                                                       1.0                                 32 (8.8)     29 (9.1)      3 (6.7)
3M New Substance Use Disorder, n (%)                   0.0                           0   361 (99.4)   317 (99.7)    44 (97.8)   0.233     Fisher's exact         0.171
                                                       1.0                                  2 (0.6)      1 (0.3)      1 (2.2)
3M New Stroke, n (%)                                   0.0                           0   356 (98.1)   314 (98.7)    42 (93.3)   0.044     Fisher's exact         0.280
                                                       1.0                                  7 (1.9)      4 (1.3)      3 (6.7)
3M New MI, n (%)                                       0.0                           0   353 (97.2)   310 (97.5)    43 (95.6)   0.358     Fisher's exact         0.105
                                                       1.0                                 10 (2.8)      8 (2.5)      2 (4.4)
3M New CABG/Stent, n (%)                               0.0                           0   331 (91.2)   291 (91.5)    40 (88.9)   0.573     Fisher's exact         0.088
                                                       1.0                                 32 (8.8)     27 (8.5)     5 (11.1)
3M Cardiac Rehab, n (%)                                0.0                           0    87 (24.0)    80 (25.2)     7 (15.6)   0.220        Chi-squared         0.240
                                                       1.0                               276 (76.0)   238 (74.8)    38 (84.4)
3M Hospitalized , n (%)                                0.0                           0   314 (86.5)   285 (89.6)    29 (64.4)  <0.001        Chi-squared         0.627
                                                       1.0                                49 (13.5)    33 (10.4)    16 (35.6)
3M HADS-A, n (%)                                       0.0                           0   251 (69.1)   220 (69.2)    31 (68.9)   1.000        Chi-squared         0.006
                                                       1.0                               112 (30.9)    98 (30.8)    14 (31.1)
3M HADS-D, n (%)                                       0.0                           0   300 (82.6)   265 (83.3)    35 (77.8)   0.477        Chi-squared         0.141
                                                       1.0                                63 (17.4)    53 (16.7)    10 (22.2)
3M SF-12 (Low), n (%)                                  0.0                           0   178 (49.0)   160 (50.3)    18 (40.0)   0.256        Chi-squared         0.208
                                                       1.0                               185 (51.0)   158 (49.7)    27 (60.0)
3M Cardiac Anxiety, n (%)                              0.0                           0   311 (85.7)   273 (85.8)    38 (84.4)   0.981        Chi-squared         0.040
                                                       1.0                                52 (14.3)    45 (14.2)     7 (15.6)
3M MOS (Low Support), n (%)                            0.0                           0   281 (77.4)   239 (75.2)    42 (93.3)   0.011        Chi-squared         0.515
                                                       1.0                                82 (22.6)    79 (24.8)      3 (6.7)

6 Months, Outcome = 6M HADS-A

                                                           Grouped by 6M HADS-A
                                                                        Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                        363          277           86
Age, mean (SD)                                                                0  67.7 (12.5)  68.7 (12.4)  64.6 (12.5)   0.009  Two Sample T-test        -0.326
Race, n (%)                                            0                      0   337 (92.8)   257 (92.8)    80 (93.0)   1.000        Chi-squared         0.009
                                                       1                            26 (7.2)     20 (7.2)      6 (7.0)
Indigenous, n (%)                                      0                      0   352 (97.0)   269 (97.1)    83 (96.5)   0.726     Fisher's exact         0.034
                                                       1                            11 (3.0)      8 (2.9)      3 (3.5)
Gender Identity, n (%)                                 0                      0   362 (99.7)   276 (99.6)   86 (100.0)   1.000     Fisher's exact           nan
                                                       1                             1 (0.3)      1 (0.4)
Highschool Education, n (%)                            0                      0   330 (90.9)   254 (91.7)    76 (88.4)   0.470        Chi-squared         0.111
                                                       1                            33 (9.1)     23 (8.3)    10 (11.6)
Post- Secondary Education, n (%)                       0                      0   221 (60.9)   171 (61.7)    50 (58.1)   0.638        Chi-squared         0.073
                                                       1                          142 (39.1)   106 (38.3)    36 (41.9)
Employment, n (%)                                      0                      0   329 (90.6)   258 (93.1)    71 (82.6)   0.006        Chi-squared         0.328
                                                       1                            34 (9.4)     19 (6.9)    15 (17.4)
Household income before taxes, n (%)                   0.0                    0   203 (55.9)   164 (59.2)    39 (45.3)   0.033        Chi-squared         0.280
                                                       1.0                        160 (44.1)   113 (40.8)    47 (54.7)
Marital status, n (%)                                  0                      0   180 (49.6)   141 (50.9)    39 (45.3)   0.438        Chi-squared         0.111
                                                       1                          183 (50.4)   136 (49.1)    47 (54.7)
Living situation, n (%)                                0                      0   359 (98.9)   275 (99.3)    84 (97.7)   0.239     Fisher's exact         0.131
                                                       1                             4 (1.1)      2 (0.7)      2 (2.3)
Pack years, mean (SD)                                                         0  29.6 (65.4)  24.6 (59.7)  45.5 (79.5)   0.027  Two Sample T-test         0.296
Alcohol use - average number of drinks/week, mean (SD)                        0    1.6 (3.5)    1.7 (3.6)    1.4 (3.2)   0.451  Two Sample T-test        -0.090
Substance Use Disorder, n (%)                          0                      0   361 (99.4)  277 (100.0)    84 (97.7)   0.056     Fisher's exact           nan
                                                       1                             2 (0.6)                   2 (2.3)
Depression, n (%)                                      0                      0   236 (65.0)   201 (72.6)    35 (40.7)  <0.001        Chi-squared         0.679
                                                       1                          127 (35.0)    76 (27.4)    51 (59.3)
Anxiety, n (%)                                         0                      0   253 (69.7)   213 (76.9)    40 (46.5)  <0.001        Chi-squared         0.658
                                                       1                          110 (30.3)    64 (23.1)    46 (53.5)
Health Anxiety, n (%)                                  0                      0   231 (63.6)   195 (70.4)    36 (41.9)  <0.001        Chi-squared         0.600
                                                       1                          132 (36.4)    82 (29.6)    50 (58.1)
Delay to Hospital, n (%)                               0                      0   182 (50.1)   137 (49.5)    45 (52.3)   0.733        Chi-squared         0.057
                                                       1                          181 (49.9)   140 (50.5)    41 (47.7)
Personal Stressors, n (%)                              0                      0   187 (51.5)   162 (58.5)    25 (29.1)  <0.001        Chi-squared         0.621
                                                       1                          176 (48.5)   115 (41.5)    61 (70.9)
Menopause, n (%)                                       0                      0    76 (20.9)    58 (20.9)    18 (20.9)   1.000        Chi-squared        <0.001
                                                       1                          287 (79.1)   219 (79.1)    68 (79.1)
Complicated Pregnancy, n (%)                           0                      0   264 (72.7)   210 (75.8)    54 (62.8)   0.026        Chi-squared         0.285
                                                       1                           99 (27.3)    67 (24.2)    32 (37.2)
Stroke History, n (%)                                  0                      0   325 (89.5)   247 (89.2)    78 (90.7)   0.839        Chi-squared         0.051
                                                       1                           38 (10.5)    30 (10.8)      8 (9.3)
MI History, n (%)                                      0                      0   295 (81.3)   229 (82.7)    66 (76.7)   0.284        Chi-squared         0.148
                                                       1                           68 (18.7)    48 (17.3)    20 (23.3)
CABG/Stent History, n (%)                              0                      0   308 (84.8)   239 (86.3)    69 (80.2)   0.232        Chi-squared         0.163
                                                       1                           55 (15.2)    38 (13.7)    17 (19.8)
High cholesterol, n (%)                                0                      0   149 (41.0)   117 (42.2)    32 (37.2)   0.482        Chi-squared         0.103
                                                       1                          214 (59.0)   160 (57.8)    54 (62.8)
Diabetes, n (%)                                        0                      0   267 (73.6)   202 (72.9)    65 (75.6)   0.728        Chi-squared         0.061
                                                       1                           96 (26.4)    75 (27.1)    21 (24.4)
Hypertension, n (%)                                    0                      0   143 (39.4)   106 (38.3)    37 (43.0)   0.508        Chi-squared         0.097
                                                       1                          220 (60.6)   171 (61.7)    49 (57.0)
BMI, mean (SD)                                                                0   28.8 (6.5)   28.7 (6.5)   29.2 (6.8)   0.524  Two Sample T-test         0.080
HFrEF, n (%)                                           0                      0   210 (57.9)   162 (58.5)    48 (55.8)   0.754        Chi-squared         0.054
                                                       1                          153 (42.1)   115 (41.5)    38 (44.2)
STEMI, n (%)                                           0                      0   208 (57.3)   160 (57.8)    48 (55.8)   0.846        Chi-squared         0.039
                                                       1                          155 (42.7)   117 (42.2)    38 (44.2)
ESSI score, n (%)                                      0                      0   248 (68.3)   204 (73.6)    44 (51.2)  <0.001        Chi-squared         0.477
                                                       1                          115 (31.7)    73 (26.4)    42 (48.8)
HADS-A, n (%)                                          0                      0   246 (67.8)   214 (77.3)    32 (37.2)  <0.001        Chi-squared         0.885
                                                       1                          117 (32.2)    63 (22.7)    54 (62.8)
HADS-D, n (%)                                          0                      0   297 (81.8)   243 (87.7)    54 (62.8)  <0.001        Chi-squared         0.604
                                                       1                           66 (18.2)    34 (12.3)    32 (37.2)
3M New Depression Diagnosis , n (%)                    0.0                    0   332 (91.5)   265 (95.7)    67 (77.9)  <0.001        Chi-squared         0.544
                                                       1.0                          31 (8.5)     12 (4.3)    19 (22.1)
3M New Anxiety Diagnosis , n (%)                       0.0                    0   331 (91.2)   260 (93.9)    71 (82.6)   0.003        Chi-squared         0.356
                                                       1.0                          32 (8.8)     17 (6.1)    15 (17.4)
3M New Substance Use Disorder, n (%)                   0.0                    0   361 (99.4)   276 (99.6)    85 (98.8)   0.418     Fisher's exact         0.092
                                                       1.0                           2 (0.6)      1 (0.4)      1 (1.2)
3M New Stroke, n (%)                                   0.0                    0   356 (98.1)   271 (97.8)    85 (98.8)   1.000     Fisher's exact         0.078
                                                       1.0                           7 (1.9)      6 (2.2)      1 (1.2)
3M New MI, n (%)                                       0.0                    0   353 (97.2)   269 (97.1)    84 (97.7)   1.000     Fisher's exact         0.035
                                                       1.0                          10 (2.8)      8 (2.9)      2 (2.3)
3M New CABG/Stent, n (%)                               0.0                    0   331 (91.2)   252 (91.0)    79 (91.9)   0.972        Chi-squared         0.032
                                                       1.0                          32 (8.8)     25 (9.0)      7 (8.1)
3M Cardiac Rehab, n (%)                                0.0                    0    87 (24.0)    71 (25.6)    16 (18.6)   0.234        Chi-squared         0.170
                                                       1.0                        276 (76.0)   206 (74.4)    70 (81.4)
3M Hospitalized , n (%)                                0.0                    0   314 (86.5)   242 (87.4)    72 (83.7)   0.494        Chi-squared         0.104
                                                       1.0                         49 (13.5)    35 (12.6)    14 (16.3)
3M HADS-A, n (%)                                       0.0                    0   251 (69.1)   228 (82.3)    23 (26.7)  <0.001        Chi-squared         1.345
                                                       1.0                        112 (30.9)    49 (17.7)    63 (73.3)
3M HADS-D, n (%)                                       0.0                    0   300 (82.6)   245 (88.4)    55 (64.0)  <0.001        Chi-squared         0.601
                                                       1.0                         63 (17.4)    32 (11.6)    31 (36.0)
3M SF-12 (Low), n (%)                                  0.0                    0   178 (49.0)   141 (50.9)    37 (43.0)   0.249        Chi-squared         0.158
                                                       1.0                        185 (51.0)   136 (49.1)    49 (57.0)
3M Cardiac Anxiety, n (%)                              0.0                    0   311 (85.7)   243 (87.7)    68 (79.1)   0.068        Chi-squared         0.234
                                                       1.0                         52 (14.3)    34 (12.3)    18 (20.9)
3M MOS (Low Support), n (%)                            0.0                    0   281 (77.4)   227 (81.9)    54 (62.8)  <0.001        Chi-squared         0.439
                                                       1.0                         82 (22.6)    50 (18.1)    32 (37.2)

6 Months, Outcome = 6M HADS-D

                                                           Grouped by 6M HADS-D
                                                                        Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                        363          290           73
Age, mean (SD)                                                                0  67.7 (12.5)  68.1 (12.6)  66.1 (12.0)   0.207  Two Sample T-test        -0.164
Race, n (%)                                            0                      0   337 (92.8)   270 (93.1)    67 (91.8)   0.890        Chi-squared         0.050
                                                       1                            26 (7.2)     20 (6.9)      6 (8.2)
Indigenous, n (%)                                      0                      0   352 (97.0)   282 (97.2)    70 (95.9)   0.468     Fisher's exact         0.074
                                                       1                            11 (3.0)      8 (2.8)      3 (4.1)
Gender Identity, n (%)                                 0                      0   362 (99.7)   289 (99.7)   73 (100.0)   1.000     Fisher's exact           nan
                                                       1                             1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                      0   330 (90.9)   266 (91.7)    64 (87.7)   0.396        Chi-squared         0.134
                                                       1                            33 (9.1)     24 (8.3)     9 (12.3)
Post- Secondary Education, n (%)                       0                      0   221 (60.9)   179 (61.7)    42 (57.5)   0.602        Chi-squared         0.085
                                                       1                          142 (39.1)   111 (38.3)    31 (42.5)
Employment, n (%)                                      0                      0   329 (90.6)   267 (92.1)    62 (84.9)   0.100        Chi-squared         0.225
                                                       1                            34 (9.4)     23 (7.9)    11 (15.1)
Household income before taxes, n (%)                   0.0                    0   203 (55.9)   172 (59.3)    31 (42.5)   0.014        Chi-squared         0.342
                                                       1.0                        160 (44.1)   118 (40.7)    42 (57.5)
Marital status, n (%)                                  0                      0   180 (49.6)   150 (51.7)    30 (41.1)   0.136        Chi-squared         0.214
                                                       1                          183 (50.4)   140 (48.3)    43 (58.9)
Living situation, n (%)                                0                      0   359 (98.9)   288 (99.3)    71 (97.3)   0.182     Fisher's exact         0.158
                                                       1                             4 (1.1)      2 (0.7)      2 (2.7)
Pack years, mean (SD)                                                         0  29.6 (65.4)  28.0 (66.5)  35.8 (61.2)   0.340  Two Sample T-test         0.122
Alcohol use - average number of drinks/week, mean (SD)                        0    1.6 (3.5)    1.8 (3.6)    1.1 (2.6)   0.089  Two Sample T-test        -0.203
Substance Use Disorder, n (%)                          0                      0   361 (99.4)  290 (100.0)    71 (97.3)   0.040     Fisher's exact           nan
                                                       1                             2 (0.6)                   2 (2.7)
Depression, n (%)                                      0                      0   236 (65.0)   210 (72.4)    26 (35.6)  <0.001        Chi-squared         0.794
                                                       1                          127 (35.0)    80 (27.6)    47 (64.4)
Anxiety, n (%)                                         0                      0   253 (69.7)   214 (73.8)    39 (53.4)   0.001        Chi-squared         0.433
                                                       1                          110 (30.3)    76 (26.2)    34 (46.6)
Health Anxiety, n (%)                                  0                      0   231 (63.6)   193 (66.6)    38 (52.1)   0.030        Chi-squared         0.298
                                                       1                          132 (36.4)    97 (33.4)    35 (47.9)
Delay to Hospital, n (%)                               0                      0   182 (50.1)   150 (51.7)    32 (43.8)   0.283        Chi-squared         0.158
                                                       1                          181 (49.9)   140 (48.3)    41 (56.2)
Personal Stressors, n (%)                              0                      0   187 (51.5)   165 (56.9)    22 (30.1)  <0.001        Chi-squared         0.561
                                                       1                          176 (48.5)   125 (43.1)    51 (69.9)
Menopause, n (%)                                       0                      0    76 (20.9)    59 (20.3)    17 (23.3)   0.695        Chi-squared         0.071
                                                       1                          287 (79.1)   231 (79.7)    56 (76.7)
Complicated Pregnancy, n (%)                           0                      0   264 (72.7)   217 (74.8)    47 (64.4)   0.100        Chi-squared         0.229
                                                       1                           99 (27.3)    73 (25.2)    26 (35.6)
Stroke History, n (%)                                  0                      0   325 (89.5)   259 (89.3)    66 (90.4)   0.952        Chi-squared         0.036
                                                       1                           38 (10.5)    31 (10.7)      7 (9.6)
MI History, n (%)                                      0                      0   295 (81.3)   236 (81.4)    59 (80.8)   1.000        Chi-squared         0.014
                                                       1                           68 (18.7)    54 (18.6)    14 (19.2)
CABG/Stent History, n (%)                              0                      0   308 (84.8)   246 (84.8)    62 (84.9)   1.000        Chi-squared         0.003
                                                       1                           55 (15.2)    44 (15.2)    11 (15.1)
High cholesterol, n (%)                                0                      0   149 (41.0)   129 (44.5)    20 (27.4)   0.012        Chi-squared         0.362
                                                       1                          214 (59.0)   161 (55.5)    53 (72.6)
Diabetes, n (%)                                        0                      0   267 (73.6)   216 (74.5)    51 (69.9)   0.515        Chi-squared         0.103
                                                       1                           96 (26.4)    74 (25.5)    22 (30.1)
Hypertension, n (%)                                    0                      0   143 (39.4)   111 (38.3)    32 (43.8)   0.462        Chi-squared         0.113
                                                       1                          220 (60.6)   179 (61.7)    41 (56.2)
BMI, mean (SD)                                                                0   28.8 (6.5)   28.4 (6.2)   30.2 (7.5)   0.061  Two Sample T-test         0.262
HFrEF, n (%)                                           0                      0   210 (57.9)   171 (59.0)    39 (53.4)   0.469        Chi-squared         0.112
                                                       1                          153 (42.1)   119 (41.0)    34 (46.6)
STEMI, n (%)                                           0                      0   208 (57.3)   167 (57.6)    41 (56.2)   0.931        Chi-squared         0.029
                                                       1                          155 (42.7)   123 (42.4)    32 (43.8)
ESSI score, n (%)                                      0                      0   248 (68.3)   220 (75.9)    28 (38.4)  <0.001        Chi-squared         0.819
                                                       1                          115 (31.7)    70 (24.1)    45 (61.6)
HADS-A, n (%)                                          0                      0   246 (67.8)   217 (74.8)    29 (39.7)  <0.001        Chi-squared         0.759
                                                       1                          117 (32.2)    73 (25.2)    44 (60.3)
HADS-D, n (%)                                          0                      0   297 (81.8)   261 (90.0)    36 (49.3)  <0.001        Chi-squared         0.987
                                                       1                           66 (18.2)    29 (10.0)    37 (50.7)
3M New Depression Diagnosis , n (%)                    0.0                    0   332 (91.5)   275 (94.8)    57 (78.1)  <0.001        Chi-squared         0.505
                                                       1.0                          31 (8.5)     15 (5.2)    16 (21.9)
3M New Anxiety Diagnosis , n (%)                       0.0                    0   331 (91.2)   271 (93.4)    60 (82.2)   0.005        Chi-squared         0.349
                                                       1.0                          32 (8.8)     19 (6.6)    13 (17.8)
3M New Substance Use Disorder, n (%)                   0.0                    0   361 (99.4)   289 (99.7)    72 (98.6)   0.362     Fisher's exact         0.111
                                                       1.0                           2 (0.6)      1 (0.3)      1 (1.4)
3M New Stroke, n (%)                                   0.0                    0   356 (98.1)   284 (97.9)    72 (98.6)   1.000     Fisher's exact         0.054
                                                       1.0                           7 (1.9)      6 (2.1)      1 (1.4)
3M New MI, n (%)                                       0.0                    0   353 (97.2)   281 (96.9)    72 (98.6)   0.694     Fisher's exact         0.117
                                                       1.0                          10 (2.8)      9 (3.1)      1 (1.4)
3M New CABG/Stent, n (%)                               0.0                    0   331 (91.2)   265 (91.4)    66 (90.4)   0.976        Chi-squared         0.034
                                                       1.0                          32 (8.8)     25 (8.6)      7 (9.6)
3M Cardiac Rehab, n (%)                                0.0                    0    87 (24.0)    74 (25.5)    13 (17.8)   0.220        Chi-squared         0.188
                                                       1.0                        276 (76.0)   216 (74.5)    60 (82.2)
3M Hospitalized , n (%)                                0.0                    0   314 (86.5)   252 (86.9)    62 (84.9)   0.804        Chi-squared         0.057
                                                       1.0                         49 (13.5)    38 (13.1)    11 (15.1)
3M HADS-A, n (%)                                       0.0                    0   251 (69.1)   221 (76.2)    30 (41.1)  <0.001        Chi-squared         0.763
                                                       1.0                        112 (30.9)    69 (23.8)    43 (58.9)
3M HADS-D, n (%)                                       0.0                    0   300 (82.6)   270 (93.1)    30 (41.1)  <0.001        Chi-squared         1.329
                                                       1.0                         63 (17.4)     20 (6.9)    43 (58.9)
3M SF-12 (Low), n (%)                                  0.0                    0   178 (49.0)   155 (53.4)    23 (31.5)   0.001        Chi-squared         0.455
                                                       1.0                        185 (51.0)   135 (46.6)    50 (68.5)
3M Cardiac Anxiety, n (%)                              0.0                    0   311 (85.7)   255 (87.9)    56 (76.7)   0.024        Chi-squared         0.297
                                                       1.0                         52 (14.3)    35 (12.1)    17 (23.3)
3M MOS (Low Support), n (%)                            0.0                    0   281 (77.4)   238 (82.1)    43 (58.9)  <0.001        Chi-squared         0.525
                                                       1.0                         82 (22.6)    52 (17.9)    30 (41.1)

6 Months, Outcome = 6M SF-12 (Low)

                                                           Grouped by 6M SF-12 (Low)
                                                                             Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                             363          180          183
Age, mean (SD)                                                                     0  67.7 (12.5)  68.1 (12.3)  67.3 (12.7)   0.504  Two Sample T-test        -0.070
Race, n (%)                                            0                           0   337 (92.8)   175 (97.2)   162 (88.5)   0.003        Chi-squared         0.343
                                                       1                                 26 (7.2)      5 (2.8)    21 (11.5)
Indigenous, n (%)                                      0                           0   352 (97.0)   176 (97.8)   176 (96.2)   0.559        Chi-squared         0.094
                                                       1                                 11 (3.0)      4 (2.2)      7 (3.8)
Gender Identity, n (%)                                 0                           0   362 (99.7)  180 (100.0)   182 (99.5)   1.000     Fisher's exact           nan
                                                       1                                  1 (0.3)                   1 (0.5)
Highschool Education, n (%)                            0                           0   330 (90.9)   165 (91.7)   165 (90.2)   0.752        Chi-squared         0.052
                                                       1                                 33 (9.1)     15 (8.3)     18 (9.8)
Post- Secondary Education, n (%)                       0                           0   221 (60.9)   107 (59.4)   114 (62.3)   0.654        Chi-squared         0.058
                                                       1                               142 (39.1)    73 (40.6)    69 (37.7)
Employment, n (%)                                      0                           0   329 (90.6)   163 (90.6)   166 (90.7)   1.000        Chi-squared         0.005
                                                       1                                 34 (9.4)     17 (9.4)     17 (9.3)
Household income before taxes, n (%)                   0.0                         0   203 (55.9)   103 (57.2)   100 (54.6)   0.697        Chi-squared         0.052
                                                       1.0                             160 (44.1)    77 (42.8)    83 (45.4)
Marital status, n (%)                                  0                           0   180 (49.6)    98 (54.4)    82 (44.8)   0.083        Chi-squared         0.194
                                                       1                               183 (50.4)    82 (45.6)   101 (55.2)
Living situation, n (%)                                0                           0   359 (98.9)   179 (99.4)   180 (98.4)   0.623     Fisher's exact         0.104
                                                       1                                  4 (1.1)      1 (0.6)      3 (1.6)
Pack years, mean (SD)                                                              0  29.6 (65.4)  44.0 (85.6)  15.4 (30.1)  <0.001  Two Sample T-test        -0.445
Alcohol use - average number of drinks/week, mean (SD)                             0    1.6 (3.5)    1.6 (3.4)    1.6 (3.5)   0.998  Two Sample T-test        -0.000
Substance Use Disorder, n (%)                          0                           0   361 (99.4)   179 (99.4)   182 (99.5)   1.000     Fisher's exact         0.001
                                                       1                                  2 (0.6)      1 (0.6)      1 (0.5)
Depression, n (%)                                      0                           0   236 (65.0)   118 (65.6)   118 (64.5)   0.917        Chi-squared         0.023
                                                       1                               127 (35.0)    62 (34.4)    65 (35.5)
Anxiety, n (%)                                         0                           0   253 (69.7)   128 (71.1)   125 (68.3)   0.640        Chi-squared         0.061
                                                       1                               110 (30.3)    52 (28.9)    58 (31.7)
Health Anxiety, n (%)                                  0                           0   231 (63.6)   119 (66.1)   112 (61.2)   0.388        Chi-squared         0.102
                                                       1                               132 (36.4)    61 (33.9)    71 (38.8)
Delay to Hospital, n (%)                               0                           0   182 (50.1)    86 (47.8)    96 (52.5)   0.431        Chi-squared         0.094
                                                       1                               181 (49.9)    94 (52.2)    87 (47.5)
Personal Stressors, n (%)                              0                           0   187 (51.5)   100 (55.6)    87 (47.5)   0.155        Chi-squared         0.161
                                                       1                               176 (48.5)    80 (44.4)    96 (52.5)
Menopause, n (%)                                       0                           0    76 (20.9)    30 (16.7)    46 (25.1)   0.064        Chi-squared         0.209
                                                       1                               287 (79.1)   150 (83.3)   137 (74.9)
Complicated Pregnancy, n (%)                           0                           0   264 (72.7)   134 (74.4)   130 (71.0)   0.541        Chi-squared         0.077
                                                       1                                99 (27.3)    46 (25.6)    53 (29.0)
Stroke History, n (%)                                  0                           0   325 (89.5)   165 (91.7)   160 (87.4)   0.252        Chi-squared         0.139
                                                       1                                38 (10.5)     15 (8.3)    23 (12.6)
MI History, n (%)                                      0                           0   295 (81.3)   143 (79.4)   152 (83.1)   0.454        Chi-squared         0.093
                                                       1                                68 (18.7)    37 (20.6)    31 (16.9)
CABG/Stent History, n (%)                              0                           0   308 (84.8)   152 (84.4)   156 (85.2)   0.947        Chi-squared         0.022
                                                       1                                55 (15.2)    28 (15.6)    27 (14.8)
High cholesterol, n (%)                                0                           0   149 (41.0)    83 (46.1)    66 (36.1)   0.066        Chi-squared         0.205
                                                       1                               214 (59.0)    97 (53.9)   117 (63.9)
Diabetes, n (%)                                        0                           0   267 (73.6)   135 (75.0)   132 (72.1)   0.617        Chi-squared         0.065
                                                       1                                96 (26.4)    45 (25.0)    51 (27.9)
Hypertension, n (%)                                    0                           0   143 (39.4)    75 (41.7)    68 (37.2)   0.440        Chi-squared         0.092
                                                       1                               220 (60.6)   105 (58.3)   115 (62.8)
BMI, mean (SD)                                                                     0   28.8 (6.5)   28.1 (5.9)   29.5 (7.0)   0.042  Two Sample T-test         0.214
HFrEF, n (%)                                           0                           0   210 (57.9)   111 (61.7)    99 (54.1)   0.176        Chi-squared         0.154
                                                       1                               153 (42.1)    69 (38.3)    84 (45.9)
STEMI, n (%)                                           0                           0   208 (57.3)   112 (62.2)    96 (52.5)   0.076        Chi-squared         0.198
                                                       1                               155 (42.7)    68 (37.8)    87 (47.5)
ESSI score, n (%)                                      0                           0   248 (68.3)   131 (72.8)   117 (63.9)   0.090        Chi-squared         0.191
                                                       1                               115 (31.7)    49 (27.2)    66 (36.1)
HADS-A, n (%)                                          0                           0   246 (67.8)   132 (73.3)   114 (62.3)   0.033        Chi-squared         0.238
                                                       1                               117 (32.2)    48 (26.7)    69 (37.7)
HADS-D, n (%)                                          0                           0   297 (81.8)   156 (86.7)   141 (77.0)   0.025        Chi-squared         0.252
                                                       1                                66 (18.2)    24 (13.3)    42 (23.0)
3M New Depression Diagnosis , n (%)                    0.0                         0   332 (91.5)   166 (92.2)   166 (90.7)   0.743        Chi-squared         0.054
                                                       1.0                               31 (8.5)     14 (7.8)     17 (9.3)
3M New Anxiety Diagnosis , n (%)                       0.0                         0   331 (91.2)   167 (92.8)   164 (89.6)   0.381        Chi-squared         0.112
                                                       1.0                               32 (8.8)     13 (7.2)    19 (10.4)
3M New Substance Use Disorder, n (%)                   0.0                         0   361 (99.4)  180 (100.0)   181 (98.9)   0.499     Fisher's exact           nan
                                                       1.0                                2 (0.6)                   2 (1.1)
3M New Stroke, n (%)                                   0.0                         0   356 (98.1)   177 (98.3)   179 (97.8)   1.000     Fisher's exact         0.038
                                                       1.0                                7 (1.9)      3 (1.7)      4 (2.2)
3M New MI, n (%)                                       0.0                         0   353 (97.2)   176 (97.8)   177 (96.7)   0.751     Fisher's exact         0.065
                                                       1.0                               10 (2.8)      4 (2.2)      6 (3.3)
3M New CABG/Stent, n (%)                               0.0                         0   331 (91.2)   169 (93.9)   162 (88.5)   0.106        Chi-squared         0.190
                                                       1.0                               32 (8.8)     11 (6.1)    21 (11.5)
3M Cardiac Rehab, n (%)                                0.0                         0    87 (24.0)    44 (24.4)    43 (23.5)   0.930        Chi-squared         0.022
                                                       1.0                             276 (76.0)   136 (75.6)   140 (76.5)
3M Hospitalized , n (%)                                0.0                         0   314 (86.5)   162 (90.0)   152 (83.1)   0.075        Chi-squared         0.204
                                                       1.0                              49 (13.5)    18 (10.0)    31 (16.9)
3M HADS-A, n (%)                                       0.0                         0   251 (69.1)   130 (72.2)   121 (66.1)   0.252        Chi-squared         0.132
                                                       1.0                             112 (30.9)    50 (27.8)    62 (33.9)
3M HADS-D, n (%)                                       0.0                         0   300 (82.6)   164 (91.1)   136 (74.3)  <0.001        Chi-squared         0.456
                                                       1.0                              63 (17.4)     16 (8.9)    47 (25.7)
3M SF-12 (Low), n (%)                                  0.0                         0   178 (49.0)   160 (88.9)     18 (9.8)  <0.001        Chi-squared         2.582
                                                       1.0                             185 (51.0)    20 (11.1)   165 (90.2)
3M Cardiac Anxiety, n (%)                              0.0                         0   311 (85.7)   165 (91.7)   146 (79.8)   0.002        Chi-squared         0.345
                                                       1.0                              52 (14.3)     15 (8.3)    37 (20.2)
3M MOS (Low Support), n (%)                            0.0                         0   281 (77.4)   121 (67.2)   160 (87.4)  <0.001        Chi-squared         0.497
                                                       1.0                              82 (22.6)    59 (32.8)    23 (12.6)

6 Months, Outcome = 6M Cardiac Anxiety

                                                           Grouped by 6M Cardiac Anxiety
                                                                                 Missing      Overall          0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                 363          313           50
Age, mean (SD)                                                                         0  67.7 (12.5)  68.6 (12.1)  61.8 (13.1)   0.001  Two Sample T-test        -0.539
Race, n (%)                                            0                               0   337 (92.8)   296 (94.6)    41 (82.0)   0.004     Fisher's exact         0.398
                                                       1                                     26 (7.2)     17 (5.4)     9 (18.0)
Indigenous, n (%)                                      0                               0   352 (97.0)   306 (97.8)    46 (92.0)   0.050     Fisher's exact         0.264
                                                       1                                     11 (3.0)      7 (2.2)      4 (8.0)
Gender Identity, n (%)                                 0                               0   362 (99.7)   312 (99.7)   50 (100.0)   1.000     Fisher's exact           nan
                                                       1                                      1 (0.3)      1 (0.3)
Highschool Education, n (%)                            0                               0   330 (90.9)   281 (89.8)    49 (98.0)   0.065     Fisher's exact         0.348
                                                       1                                     33 (9.1)    32 (10.2)      1 (2.0)
Post- Secondary Education, n (%)                       0                               0   221 (60.9)   187 (59.7)    34 (68.0)   0.340        Chi-squared         0.172
                                                       1                                   142 (39.1)   126 (40.3)    16 (32.0)
Employment, n (%)                                      0                               0   329 (90.6)   285 (91.1)    44 (88.0)   0.442     Fisher's exact         0.100
                                                       1                                     34 (9.4)     28 (8.9)     6 (12.0)
Household income before taxes, n (%)                   0.0                             0   203 (55.9)   175 (55.9)    28 (56.0)   1.000        Chi-squared         0.002
                                                       1.0                                 160 (44.1)   138 (44.1)    22 (44.0)
Marital status, n (%)                                  0                               0   180 (49.6)   156 (49.8)    24 (48.0)   0.929        Chi-squared         0.037
                                                       1                                   183 (50.4)   157 (50.2)    26 (52.0)
Living situation, n (%)                                0                               0   359 (98.9)   309 (98.7)   50 (100.0)   1.000     Fisher's exact           nan
                                                       1                                      4 (1.1)      4 (1.3)
Pack years, mean (SD)                                                                  0  29.6 (65.4)  31.0 (69.0)  20.5 (34.9)   0.096  Two Sample T-test        -0.193
Alcohol use - average number of drinks/week, mean (SD)                                 0    1.6 (3.5)    1.7 (3.6)    1.1 (2.2)   0.143  Two Sample T-test        -0.185
Substance Use Disorder, n (%)                          0                               0   361 (99.4)   312 (99.7)    49 (98.0)   0.257     Fisher's exact         0.157
                                                       1                                      2 (0.6)      1 (0.3)      1 (2.0)
Depression, n (%)                                      0                               0   236 (65.0)   208 (66.5)    28 (56.0)   0.201        Chi-squared         0.216
                                                       1                                   127 (35.0)   105 (33.5)    22 (44.0)
Anxiety, n (%)                                         0                               0   253 (69.7)   220 (70.3)    33 (66.0)   0.655        Chi-squared         0.092
                                                       1                                   110 (30.3)    93 (29.7)    17 (34.0)
Health Anxiety, n (%)                                  0                               0   231 (63.6)   206 (65.8)    25 (50.0)   0.045        Chi-squared         0.325
                                                       1                                   132 (36.4)   107 (34.2)    25 (50.0)
Delay to Hospital, n (%)                               0                               0   182 (50.1)   160 (51.1)    22 (44.0)   0.434        Chi-squared         0.143
                                                       1                                   181 (49.9)   153 (48.9)    28 (56.0)
Personal Stressors, n (%)                              0                               0   187 (51.5)   167 (53.4)    20 (40.0)   0.109        Chi-squared         0.270
                                                       1                                   176 (48.5)   146 (46.6)    30 (60.0)
Menopause, n (%)                                       0                               0    76 (20.9)    63 (20.1)    13 (26.0)   0.447        Chi-squared         0.140
                                                       1                                   287 (79.1)   250 (79.9)    37 (74.0)
Complicated Pregnancy, n (%)                           0                               0   264 (72.7)   229 (73.2)    35 (70.0)   0.768        Chi-squared         0.070
                                                       1                                    99 (27.3)    84 (26.8)    15 (30.0)
Stroke History, n (%)                                  0                               0   325 (89.5)   282 (90.1)    43 (86.0)   0.529        Chi-squared         0.127
                                                       1                                    38 (10.5)     31 (9.9)     7 (14.0)
MI History, n (%)                                      0                               0   295 (81.3)   254 (81.2)    41 (82.0)   1.000        Chi-squared         0.022
                                                       1                                    68 (18.7)    59 (18.8)     9 (18.0)
CABG/Stent History, n (%)                              0                               0   308 (84.8)   269 (85.9)    39 (78.0)   0.214        Chi-squared         0.208
                                                       1                                    55 (15.2)    44 (14.1)    11 (22.0)
High cholesterol, n (%)                                0                               0   149 (41.0)   131 (41.9)    18 (36.0)   0.531        Chi-squared         0.120
                                                       1                                   214 (59.0)   182 (58.1)    32 (64.0)
Diabetes, n (%)                                        0                               0   267 (73.6)   233 (74.4)    34 (68.0)   0.432        Chi-squared         0.143
                                                       1                                    96 (26.4)    80 (25.6)    16 (32.0)
Hypertension, n (%)                                    0                               0   143 (39.4)   123 (39.3)    20 (40.0)   1.000        Chi-squared         0.014
                                                       1                                   220 (60.6)   190 (60.7)    30 (60.0)
BMI, mean (SD)                                                                         0   28.8 (6.5)   28.6 (6.6)   29.9 (6.1)   0.188  Two Sample T-test         0.197
HFrEF, n (%)                                           0                               0   210 (57.9)   181 (57.8)    29 (58.0)   1.000        Chi-squared         0.003
                                                       1                                   153 (42.1)   132 (42.2)    21 (42.0)
STEMI, n (%)                                           0                               0   208 (57.3)   179 (57.2)    29 (58.0)   1.000        Chi-squared         0.016
                                                       1                                   155 (42.7)   134 (42.8)    21 (42.0)
ESSI score, n (%)                                      0                               0   248 (68.3)   213 (68.1)    35 (70.0)   0.911        Chi-squared         0.042
                                                       1                                   115 (31.7)   100 (31.9)    15 (30.0)
HADS-A, n (%)                                          0                               0   246 (67.8)   222 (70.9)    24 (48.0)   0.002        Chi-squared         0.480
                                                       1                                   117 (32.2)    91 (29.1)    26 (52.0)
HADS-D, n (%)                                          0                               0   297 (81.8)   264 (84.3)    33 (66.0)   0.003        Chi-squared         0.435
                                                       1                                    66 (18.2)    49 (15.7)    17 (34.0)
3M New Depression Diagnosis , n (%)                    0.0                             0   332 (91.5)   288 (92.0)    44 (88.0)   0.410     Fisher's exact         0.134
                                                       1.0                                   31 (8.5)     25 (8.0)     6 (12.0)
3M New Anxiety Diagnosis , n (%)                       0.0                             0   331 (91.2)   286 (91.4)    45 (90.0)   0.787     Fisher's exact         0.047
                                                       1.0                                   32 (8.8)     27 (8.6)     5 (10.0)
3M New Substance Use Disorder, n (%)                   0.0                             0   361 (99.4)   311 (99.4)   50 (100.0)   1.000     Fisher's exact           nan
                                                       1.0                                    2 (0.6)      2 (0.6)
3M New Stroke, n (%)                                   0.0                             0   356 (98.1)   307 (98.1)    49 (98.0)   1.000     Fisher's exact         0.006
                                                       1.0                                    7 (1.9)      6 (1.9)      1 (2.0)
3M New MI, n (%)                                       0.0                             0   353 (97.2)   305 (97.4)    48 (96.0)   0.634     Fisher's exact         0.081
                                                       1.0                                   10 (2.8)      8 (2.6)      2 (4.0)
3M New CABG/Stent, n (%)                               0.0                             0   331 (91.2)   285 (91.1)    46 (92.0)   1.000     Fisher's exact         0.034
                                                       1.0                                   32 (8.8)     28 (8.9)      4 (8.0)
3M Cardiac Rehab, n (%)                                0.0                             0    87 (24.0)    74 (23.6)    13 (26.0)   0.854        Chi-squared         0.055
                                                       1.0                                 276 (76.0)   239 (76.4)    37 (74.0)
3M Hospitalized , n (%)                                0.0                             0   314 (86.5)   271 (86.6)    43 (86.0)   1.000        Chi-squared         0.017
                                                       1.0                                  49 (13.5)    42 (13.4)     7 (14.0)
3M HADS-A, n (%)                                       0.0                             0   251 (69.1)   228 (72.8)    23 (46.0)  <0.001        Chi-squared         0.568
                                                       1.0                                 112 (30.9)    85 (27.2)    27 (54.0)
3M HADS-D, n (%)                                       0.0                             0   300 (82.6)   268 (85.6)    32 (64.0)  <0.001        Chi-squared         0.514
                                                       1.0                                  63 (17.4)    45 (14.4)    18 (36.0)
3M SF-12 (Low), n (%)                                  0.0                             0   178 (49.0)   169 (54.0)     9 (18.0)  <0.001        Chi-squared         0.809
                                                       1.0                                 185 (51.0)   144 (46.0)    41 (82.0)
3M Cardiac Anxiety, n (%)                              0.0                             0   311 (85.7)   282 (90.1)    29 (58.0)  <0.001        Chi-squared         0.787
                                                       1.0                                  52 (14.3)     31 (9.9)    21 (42.0)
3M MOS (Low Support), n (%)                            0.0                             0   281 (77.4)   238 (76.0)    43 (86.0)   0.167        Chi-squared         0.256
                                                       1.0                                  82 (22.6)    75 (24.0)     7 (14.0)

6 Months, Outcome = 6M MOS (Low Support)

                                                           Grouped by 6M MOS (Low Support)
                                                                                   Missing      Overall           0.0          1.0 P-Value               Test SMD (0.0,1.0)
n                                                                                                   363            90          273
Age, mean (SD)                                                                           0  67.7 (12.5)   67.6 (11.3)  67.7 (12.9)   0.944  Two Sample T-test         0.008
Race, n (%)                                            0                                 0   337 (92.8)     85 (94.4)   252 (92.3)   0.656        Chi-squared         0.086
                                                       1                                       26 (7.2)       5 (5.6)     21 (7.7)
Indigenous, n (%)                                      0                                 0   352 (97.0)     86 (95.6)   266 (97.4)   0.476     Fisher's exact         0.102
                                                       1                                       11 (3.0)       4 (4.4)      7 (2.6)
Gender Identity, n (%)                                 0                                 0   362 (99.7)    90 (100.0)   272 (99.6)   1.000     Fisher's exact           nan
                                                       1                                        1 (0.3)                    1 (0.4)
Highschool Education, n (%)                            0                                 0   330 (90.9)     85 (94.4)   245 (89.7)   0.257        Chi-squared         0.175
                                                       1                                       33 (9.1)       5 (5.6)    28 (10.3)
Post- Secondary Education, n (%)                       0                                 0   221 (60.9)     50 (55.6)   171 (62.6)   0.285        Chi-squared         0.144
                                                       1                                     142 (39.1)     40 (44.4)   102 (37.4)
Employment, n (%)                                      0                                 0   329 (90.6)     80 (88.9)   249 (91.2)   0.655        Chi-squared         0.078
                                                       1                                       34 (9.4)     10 (11.1)     24 (8.8)
Household income before taxes, n (%)                   0.0                               0   203 (55.9)     39 (43.3)   164 (60.1)   0.008        Chi-squared         0.340
                                                       1.0                                   160 (44.1)     51 (56.7)   109 (39.9)
Marital status, n (%)                                  0                                 0   180 (49.6)     40 (44.4)   140 (51.3)   0.316        Chi-squared         0.137
                                                       1                                     183 (50.4)     50 (55.6)   133 (48.7)
Living situation, n (%)                                0                                 0   359 (98.9)     87 (96.7)   272 (99.6)   0.049     Fisher's exact         0.222
                                                       1                                        4 (1.1)       3 (3.3)      1 (0.4)
Pack years, mean (SD)                                                                    0  29.6 (65.4)  82.5 (112.4)  12.1 (18.3)  <0.001  Two Sample T-test        -0.875
Alcohol use - average number of drinks/week, mean (SD)                                   0    1.6 (3.5)     1.9 (3.8)    1.5 (3.3)   0.419  Two Sample T-test        -0.102
Substance Use Disorder, n (%)                          0                                 0   361 (99.4)    90 (100.0)   271 (99.3)   1.000     Fisher's exact           nan
                                                       1                                        2 (0.6)                    2 (0.7)
Depression, n (%)                                      0                                 0   236 (65.0)     54 (60.0)   182 (66.7)   0.306        Chi-squared         0.139
                                                       1                                     127 (35.0)     36 (40.0)    91 (33.3)
Anxiety, n (%)                                         0                                 0   253 (69.7)     69 (76.7)   184 (67.4)   0.127        Chi-squared         0.208
                                                       1                                     110 (30.3)     21 (23.3)    89 (32.6)
Health Anxiety, n (%)                                  0                                 0   231 (63.6)     51 (56.7)   180 (65.9)   0.145        Chi-squared         0.191
                                                       1                                     132 (36.4)     39 (43.3)    93 (34.1)
Delay to Hospital, n (%)                               0                                 0   182 (50.1)     51 (56.7)   131 (48.0)   0.191        Chi-squared         0.174
                                                       1                                     181 (49.9)     39 (43.3)   142 (52.0)
Personal Stressors, n (%)                              0                                 0   187 (51.5)     38 (42.2)   149 (54.6)   0.056        Chi-squared         0.249
                                                       1                                     176 (48.5)     52 (57.8)   124 (45.4)
Menopause, n (%)                                       0                                 0    76 (20.9)     14 (15.6)    62 (22.7)   0.194        Chi-squared         0.183
                                                       1                                     287 (79.1)     76 (84.4)   211 (77.3)
Complicated Pregnancy, n (%)                           0                                 0   264 (72.7)     57 (63.3)   207 (75.8)   0.030        Chi-squared         0.274
                                                       1                                      99 (27.3)     33 (36.7)    66 (24.2)
Stroke History, n (%)                                  0                                 0   325 (89.5)     83 (92.2)   242 (88.6)   0.446        Chi-squared         0.122
                                                       1                                      38 (10.5)       7 (7.8)    31 (11.4)
MI History, n (%)                                      0                                 0   295 (81.3)     76 (84.4)   219 (80.2)   0.462        Chi-squared         0.111
                                                       1                                      68 (18.7)     14 (15.6)    54 (19.8)
CABG/Stent History, n (%)                              0                                 0   308 (84.8)     79 (87.8)   229 (83.9)   0.469        Chi-squared         0.112
                                                       1                                      55 (15.2)     11 (12.2)    44 (16.1)
High cholesterol, n (%)                                0                                 0   149 (41.0)     30 (33.3)   119 (43.6)   0.111        Chi-squared         0.212
                                                       1                                     214 (59.0)     60 (66.7)   154 (56.4)
Diabetes, n (%)                                        0                                 0   267 (73.6)     67 (74.4)   200 (73.3)   0.934        Chi-squared         0.027
                                                       1                                      96 (26.4)     23 (25.6)    73 (26.7)
Hypertension, n (%)                                    0                                 0   143 (39.4)     32 (35.6)   111 (40.7)   0.462        Chi-squared         0.105
                                                       1                                     220 (60.6)     58 (64.4)   162 (59.3)
BMI, mean (SD)                                                                           0   28.8 (6.5)    28.6 (6.6)   28.9 (6.5)   0.703  Two Sample T-test         0.047
HFrEF, n (%)                                           0                                 0   210 (57.9)     55 (61.1)   155 (56.8)   0.549        Chi-squared         0.088
                                                       1                                     153 (42.1)     35 (38.9)   118 (43.2)
STEMI, n (%)                                           0                                 0   208 (57.3)     45 (50.0)   163 (59.7)   0.136        Chi-squared         0.196
                                                       1                                     155 (42.7)     45 (50.0)   110 (40.3)
ESSI score, n (%)                                      0                                 0   248 (68.3)     36 (40.0)   212 (77.7)  <0.001        Chi-squared         0.828
                                                       1                                     115 (31.7)     54 (60.0)    61 (22.3)
HADS-A, n (%)                                          0                                 0   246 (67.8)     44 (48.9)   202 (74.0)  <0.001        Chi-squared         0.534
                                                       1                                     117 (32.2)     46 (51.1)    71 (26.0)
HADS-D, n (%)                                          0                                 0   297 (81.8)     60 (66.7)   237 (86.8)  <0.001        Chi-squared         0.491
                                                       1                                      66 (18.2)     30 (33.3)    36 (13.2)
3M New Depression Diagnosis , n (%)                    0.0                               0   332 (91.5)     84 (93.3)   248 (90.8)   0.606        Chi-squared         0.092
                                                       1.0                                     31 (8.5)       6 (6.7)     25 (9.2)
3M New Anxiety Diagnosis , n (%)                       0.0                               0   331 (91.2)     84 (93.3)   247 (90.5)   0.539        Chi-squared         0.105
                                                       1.0                                     32 (8.8)       6 (6.7)     26 (9.5)
3M New Substance Use Disorder, n (%)                   0.0                               0   361 (99.4)    90 (100.0)   271 (99.3)   1.000     Fisher's exact           nan
                                                       1.0                                      2 (0.6)                    2 (0.7)
3M New Stroke, n (%)                                   0.0                               0   356 (98.1)     89 (98.9)   267 (97.8)   1.000     Fisher's exact         0.085
                                                       1.0                                      7 (1.9)       1 (1.1)      6 (2.2)
3M New MI, n (%)                                       0.0                               0   353 (97.2)    90 (100.0)   263 (96.3)   0.128     Fisher's exact           nan
                                                       1.0                                     10 (2.8)                   10 (3.7)
3M New CABG/Stent, n (%)                               0.0                               0   331 (91.2)     86 (95.6)   245 (89.7)   0.141        Chi-squared         0.224
                                                       1.0                                     32 (8.8)       4 (4.4)    28 (10.3)
3M Cardiac Rehab, n (%)                                0.0                               0    87 (24.0)     25 (27.8)    62 (22.7)   0.404        Chi-squared         0.117
                                                       1.0                                   276 (76.0)     65 (72.2)   211 (77.3)
3M Hospitalized , n (%)                                0.0                               0   314 (86.5)     82 (91.1)   232 (85.0)   0.194        Chi-squared         0.190
                                                       1.0                                    49 (13.5)       8 (8.9)    41 (15.0)
3M HADS-A, n (%)                                       0.0                               0   251 (69.1)     50 (55.6)   201 (73.6)   0.002        Chi-squared         0.385
                                                       1.0                                   112 (30.9)     40 (44.4)    72 (26.4)
3M HADS-D, n (%)                                       0.0                               0   300 (82.6)     64 (71.1)   236 (86.4)   0.002        Chi-squared         0.382
                                                       1.0                                    63 (17.4)     26 (28.9)    37 (13.6)
3M SF-12 (Low), n (%)                                  0.0                               0   178 (49.0)     57 (63.3)   121 (44.3)   0.003        Chi-squared         0.388
                                                       1.0                                   185 (51.0)     33 (36.7)   152 (55.7)
3M Cardiac Anxiety, n (%)                              0.0                               0   311 (85.7)     80 (88.9)   231 (84.6)   0.406        Chi-squared         0.126
                                                       1.0                                    52 (14.3)     10 (11.1)    42 (15.4)
3M MOS (Low Support), n (%)                            0.0                               0   281 (77.4)     13 (14.4)   268 (98.2)  <0.001        Chi-squared         3.147
                                                       1.0                                    82 (22.6)     77 (85.6)      5 (1.8)

# Computing Odds ratios

In [87]:
def getOddsRatios(data, outcomes):
    
    results  = []
    for o in outcomes:
        for cols in data.columns:
            data_crosstab = pd.crosstab(data[cols],data[o])
            tp = data_crosstab.iloc[1][1]
            tn = data_crosstab.iloc[0][0]
            fp = data_crosstab.iloc[1][0]
            fn = data_crosstab.iloc[0][1]
            if(tp == 0 or tn == 0 or fp == 0 or fn == 0):
                tp = tp + 0.5
                tn = tn + 0.5
                fp = fp + 0.5
                fn = fn + 0.5

            linOR = (tp*tn)/(fp*fn)
            SE = math.sqrt(1/tp + 1/tn + 1/fp + 1/fn)
            z = math.log(linOR)/SE
            #dont take exponential fo rnow
            CILow = math.exp(math.log(linOR) - 1.96*SE)
            CIHigh = math.exp(math.log(linOR) + 1.96*SE)
            p=stats.norm.sf(abs(z))*2

            results.append([o, cols, linOR, CILow, CIHigh, p])

    resultsDF = pd.DataFrame(results, columns = ['outcome', 'variable', 'OR',
                                                 'CILow','CIHigh','p'])
    return resultsDF

In [93]:
print('Baseline')
ORBL = getOddsRatios(dataBL, colsOutcomesBL)
display(ORBL)

print('3 Months')
OR3m = getOddsRatios(data3m, colsOutcomes3m)
display(OR3m)

print('6 Months')
OR6m = getOddsRatios(data6m, colsOutcomes6m)
display(OR6m)

ORBL.to_csv('ORBL.csv', index=False)  
OR3m.to_csv('OR3m.csv', index=False)  
OR6m.to_csv('OR6m.csv', index=False)

Baseline

,outcome,variable,OR,CILow,CIHigh,p
0,HADS-A,Age,0.555556,0.012590,2.451519e+01,7.609690e-01
1,HADS-A,Race,1.332555,0.807276,2.199621e+00,2.615406e-01
2,HADS-A,Indigenous,0.877096,0.372956,2.062707e+00,7.637455e-01
3,HADS-A,Gender Identity,0.622177,0.025249,1.533163e+01,7.716274e-01
4,HADS-A,Highschool Education,0.765201,0.461971,1.267464e+00,2.986081e-01
5,HADS-A,Post- Secondary Education,1.139949,0.833412,1.559234e+00,4.124074e-01
6,HADS-A,Employment,1.377664,0.871115,2.178770e+00,1.706903e-01
7,HADS-A,Household income before taxes,1.348819,0.987025,1.843231e+00,6.037697e-02
8,HADS-A,Marital status,1.030670,0.754831,1.407309e+00,8.492309e-01
9,HADS-A,Living situation,3.461538,1.146970,1.044687e+01,2.757264e-02
10,HADS-A,Pack years,0.827586,0.385247,1.777818e+00,6.276120e-01
11,HADS-A,Alcohol use - average number of drinks/week,5.754098,0.232996,1.421042e+02,2.847997e-01
12,HADS-A,Substance Use Disorder,1.620253,0.538393,4.876030e+00,3.906114e-01
13,HADS-A,Depression,2.159976,1.555542,2.999273e+00,4.266243e-06
14,HADS-A,Anxiety,2.171520,1.553116,3.036154e+00,5.771129e-06
15,HADS-A,Health Anxiety,3.026316,2.189239,4.183457e+00,2.040981e-11
16,HADS-A,Delay to Hospital,1.045444,0.765592,1.427594e+00,7.797904e-01
17,HADS-A,Personal Stressors,2.984054,2.159966,4.122555e+00,3.351056e-11
18,HADS-A,Menopause,0.857883,0.589270,1.248941e+00,4.237459e-01
19,HADS-A,Complicated Pregnancy,1.279279,0.901856,1.814653e+00,1.673249e-01
20,HADS-A,Stroke History,0.652984,0.366323,1.163968e+00,1.484128e-01
21,HADS-A,MI History,1.005761,0.671037,1.507449e+00,9.778054e-01
22,HADS-A,CABG/Stent History,1.210069,0.793734,1.844783e+00,3.754697e-01
23,HADS-A,High cholesterol,0.944749,0.690075,1.293411e+00,7.228598e-01
24,HADS-A,Diabetes,0.922829,0.650541,1.309084e+00,6.525607e-01
25,HADS-A,Hypertension,1.250391,0.904118,1.729285e+00,1.767838e-01
26,HADS-A,BMI,1.000000,0.010819,9.242764e+01,1.000000e+00
27,HADS-A,HFrEF,1.094361,0.799658,1.497671e+00,5.732232e-01
28,HADS-A,STEMI,0.942597,0.689022,1.289495e+00,7.115682e-01
29,HADS-A,ESSI score,1.952490,1.401585,2.719935e+00,7.619136e-05
30,HADS-A,HADS-A,443657.000000,8775.510072,2.242964e+07,8.232602e-11
31,HADS-A,HADS-D,6.455108,4.232753,9.844284e+00,4.672447e-18
32,HADS-D,Age,0.555556,0.012590,2.451519e+01,7.609690e-01
33,HADS-D,Race,1.105263,0.595251,2.052256e+00,7.512606e-01
34,HADS-D,Indigenous,0.843318,0.284423,2.500449e+00,7.586099e-01
35,HADS-D,Gender Identity,1.477302,0.059835,3.647412e+01,8.114683e-01
36,HADS-D,Highschool Education,1.013677,0.558212,1.840770e+00,9.644046e-01
37,HADS-D,Post- Secondary Education,1.153846,0.785398,1.695141e+00,4.659115e-01
38,HADS-D,Employment,1.988725,1.193771,3.313055e+00,8.286145e-03
39,HADS-D,Household income before taxes,1.073593,0.731458,1.575760e+00,7.168214e-01
40,HADS-D,Marital status,1.490842,1.012037,2.196177e+00,4.332769e-02
41,HADS-D,Living situation,1.806452,0.557445,5.853969e+00,3.242251e-01
42,HADS-D,Pack years,0.625850,0.211368,1.853109e+00,3.974490e-01
43,HADS-D,Alcohol use - average number of drinks/week,12.257143,0.495056,3.034756e+02,1.258696e-01
44,HADS-D,Substance Use Disorder,2.855691,0.918545,8.878144e+00,6.980355e-02
45,HADS-D,Depression,2.727823,1.843476,4.036406e+00,5.182556e-07
46,HADS-D,Anxiety,1.773356,1.189821,2.643080e+00,4.898797e-03
47,HADS-D,Health Anxiety,2.358447,1.598437,3.479820e+00,1.536740e-05
48,HADS-D,Delay to Hospital,1.365060,0.927399,2.009262e+00,1.145999e-01
49,HADS-D,Personal Stressors,2.682394,1.796294,4.005600e+00,1.414051e-06
50,HADS-D,Menopause,0.664286,0.428024,1.030961e+00,6.814735e-02
51,HADS-D,Complicated Pregnancy,0.841837,0.537246,1.319114e+00,4.524447e-01
52,HADS-D,Stroke History,1.150384,0.605624,2.185157e+00,6.686673e-01
53,HADS-D,MI History,1.348571,0.841024,2.162418e+00,2.144860e-01
54,HADS-D,CABG/Stent History,0.929664,0.543513,1.590163e+00,7.899996e-01
55,HADS-D,High cholesterol,1.385268,0.932732,2.057362e+00,1.063276e-01
56,HADS-D,Diabetes,1.173251,0.771517,1.784171e+00,4.550028e-01
57,HADS-D,Hypertension,0.983743,0.663030,1.459586e+00,9.351029e-01
58,HADS-D,BMI,1.000000,0.010819,9.242764e+01,1.000000e+00
59,HADS-D,HFrEF,1.332692,0.907418,1.957277e+00,1.430365e-01
60,HADS-D,STEMI,1.330082,0.905938,1.952803e+00,1.454417e-01
61,HADS-D,ESSI score,3.261224,2.197826,4.839138e+00,4.330039e-09
62,HADS-D,HADS-A,6.455108,4.232753,9.844284e+00,4.672447e-18
63,HADS-D,HADS-D,293237.000000,5791.039513,1.484845e+07,3.239105e-10

3 Months

,outcome,variable,OR,CILow,CIHigh,p
0,3M New Depression Diagnosis,Age,1.666667,0.020222,1.373648e+02,8.204702e-01
1,3M New Depression Diagnosis,Race,0.680519,0.156690,2.955559e+00,6.074671e-01
2,3M New Depression Diagnosis,Indigenous,1.019608,0.128689,8.078370e+00,9.853291e-01
3,3M New Depression Diagnosis,Gender Identity,4.014085,0.160556,1.003569e+02,3.974111e-01
4,3M New Depression Diagnosis,Highschool Education,2.323153,0.903323,5.974653e+00,8.028616e-02
...,...,...,...,...,...,...
580,3M MOS (Low Support),3M HADS-A,3.032667,1.942047,4.735763e+00,1.067024e-06
581,3M MOS (Low Support),3M HADS-D,2.714562,1.623584,4.538630e+00,1.400681e-04
582,3M MOS (Low Support),3M SF-12 (Low),0.366826,0.233587,5.760653e-01,1.329783e-05
583,3M MOS (Low Support),3M Cardiac Anxiety,0.926759,0.498878,1.721629e+00,8.097790e-01
584,3M MOS (Low Support),3M MOS (Low Support),155271.000000,3062.768459,7.871664e+06,2.408369e-09

6 Months

,outcome,variable,OR,CILow,CIHigh,p
0,6M New Depression Diagnosis,Age,0.333333,0.006614,1.680015e+01,5.827954e-01
1,6M New Depression Diagnosis,Race,1.497585,0.422342,5.310293e+00,5.317471e-01
2,6M New Depression Diagnosis,Indigenous,2.571429,0.529600,1.248536e+01,2.413818e-01
3,6M New Depression Diagnosis,Gender Identity,3.633880,0.144891,9.113820e+01,4.325154e-01
4,6M New Depression Diagnosis,Highschool Education,2.178571,0.773679,6.134553e+00,1.404277e-01
...,...,...,...,...,...,...
749,6M MOS (Low Support),6M HADS-A,0.271954,0.161347,4.583839e-01,1.016096e-06
750,6M MOS (Low Support),6M HADS-D,0.296528,0.172048,5.110706e-01,1.204166e-05
751,6M MOS (Low Support),6M SF-12 (Low),2.390829,1.455863,3.926237e+00,5.729669e-04
752,6M MOS (Low Support),6M Cardiac Anxiety,1.863636,0.839935,4.135011e+00,1.257657e-01
753,6M MOS (Low Support),6M MOS (Low Support),99007.000000,1950.315610,5.026051e+06,9.415839e-09

# Logistic Regression

## CAVEATS FOR INTERPRETATION:

Remember to do e^{coefficient} to get logreg odds ratios

Variables with high stderror likely have low variances or not enough samples for different categories)

In [99]:
def fitLogReg(data, outcomes):
    dataTemp = data

    for o in outcomes:
        data = dataTemp
        print('\n Outcome: ' + o + '\n')
        maxParams = math.floor(len(data)/10)
        #dropping outcomes
        outcomeCol = data[o]
        
        #check variance of outcome 
        #dropping outcomes columns
        data = data.drop(columns = outcomes)
        data[o] = outcomeCol

        try:
            #first logit fit
            y = data[o]
            X = data.drop(columns = [o])
            logit_model=sm.Logit(y,X)
            result=logit_model.fit()
            print(result.summary2())

            #refitting with feature selection of top N features
            print('Refitting after feature selection \n')
            toDrop = len(X.columns) - maxParams
            LRresult = (result.summary2().tables[1])
            resultDropped = LRresult.drop(LRresult['P>|z|'].nlargest(toDrop).index)
            cols = resultDropped.index

            XFiltered = data[cols]
            logit_model=sm.Logit(y,XFiltered)
            result=logit_model.fit()
            print(result.summary2())
            LRresult = (result.summary2().tables[1])
        except:
            print('Unable to converge \n')

In [100]:
print('Baseline')
fitLogReg(dataBL, colsOutcomesBL)

Baseline

 Outcome: HADS-A

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.550125
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                          Logit                        Method:                       MLE
Dependent Variable:             HADS-A                       Pseudo R-squared:             0.149
Date:                           2026-03-25 21:22             AIC:                          827.9747
No. Observations:               698                          BIC:                          964.4213
Df Model:                       29                           Log-Likelihood:               -383.99
Df Residuals:                   668                          LL-Null:                      -451.11
Converged:                      0.0000                       LLR p-value:                  1.7565e-15
No. Iterations:                 35.0000                      Scale:                        1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0332     0.0062 -5.3833 0.0000     -0.0453    -0.0211
Race                                          0.5576     0.3500  1.5934 0.1111     -0.1283     1.2436
Indigenous                                   -1.0296     0.5645 -1.8237 0.0682     -2.1361     0.0769
Gender Identity                             -21.0643 36947.8456 -0.0006 0.9995 -72437.5111 72395.3824
Highschool Education                         -0.4294     0.3242 -1.3244 0.1854     -1.0650     0.2061
Post- Secondary Education                     0.3744     0.2048  1.8278 0.0676     -0.0271     0.7758
Employment                                   -0.5895     0.2977 -1.9804 0.0477     -1.1729    -0.0061
Household income before taxes                 0.2558     0.2011  1.2720 0.2034     -0.1383     0.6498
Marital status                               -0.0198     0.1904 -0.1040 0.9172     -0.3930     0.3534
Living situation                              0.7865     0.6282  1.2519 0.2106     -0.4448     2.0177
Pack years                                    0.0036     0.0015  2.3992 0.0164      0.0007     0.0065
Alcohol use - average number of drinks/week   0.0015     0.0253  0.0600 0.9522     -0.0482     0.0512
Substance Use Disorder                       -0.3955     0.6089 -0.6495 0.5160     -1.5888     0.7979
Depression                                    0.2631     0.2189  1.2017 0.2295     -0.1660     0.6922
Anxiety                                       0.4623     0.2164  2.1364 0.0326      0.0382     0.8864
Health Anxiety                                0.8713     0.1817  4.7941 0.0000      0.5151     1.2275
Delay to Hospital                             0.0806     0.1824  0.4418 0.6586     -0.2769     0.4380
Personal Stressors                            0.7040     0.1900  3.7053 0.0002      0.3316     1.0764
Menopause                                     0.1748     0.2428  0.7201 0.4715     -0.3010     0.6507
Complicated Pregnancy                         0.0137     0.2057  0.0665 0.9470     -0.3894     0.4167
Stroke History                               -0.3206     0.3359 -0.9544 0.3399     -0.9790     0.3378
MI History                                   -0.3299     0.3180 -1.0375 0.2995     -0.9531     0.2933
CABG/Stent History                            0.3718     0.3286  1.1312 0.2580     -0.2724     1.0159
High cholesterol                             -0.0790     0.1912 -0.4131 0.6795     -0.4538     0.2958
Diabetes                                     -0.2310     0.2177 -1.0614 0.2885     -0.6576     0.1956
Hypertension                                  0.2082     0.1992  1.0449 0.2961     -0.1823     0.5986
BMI                                           0.0008     0.0112  0.0674 0.9462     -0.0211     0.0226
HFrEF                                         0.2291     0.1882  1.2177 0.2233     -0.1397     0.5980
STEMI                                        -0.3181     0.1884 -1.6888 0.0913     -0.6873     0.0511
ESSI score                                    0.5521     0.1992  2.7715 0.0056      0.1617     0.9425
=====================================================================================================

Refitting after feature selection

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.550125
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                          Logit                        Method:                       MLE
Dependent Variable:             HADS-A                       Pseudo R-squared:             0.149
Date:                           2026-03-25 21:22             AIC:                          827.9747
No. Observations:               698                          BIC:                          964.4213
Df Model:                       29                           Log-Likelihood:               -383.99
Df Residuals:                   668                          LL-Null:                      -451.11
Converged:                      0.0000                       LLR p-value:                  1.7565e-15
No. Iterations:                 35.0000                      Scale:                        1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0332     0.0062 -5.3833 0.0000     -0.0453    -0.0211
Race                                          0.5576     0.3500  1.5934 0.1111     -0.1283     1.2436
Indigenous                                   -1.0296     0.5645 -1.8237 0.0682     -2.1361     0.0769
Gender Identity                             -21.0643 36947.8456 -0.0006 0.9995 -72437.5111 72395.3824
Highschool Education                         -0.4294     0.3242 -1.3244 0.1854     -1.0650     0.2061
Post- Secondary Education                     0.3744     0.2048  1.8278 0.0676     -0.0271     0.7758
Employment                                   -0.5895     0.2977 -1.9804 0.0477     -1.1729    -0.0061
Household income before taxes                 0.2558     0.2011  1.2720 0.2034     -0.1383     0.6498
Marital status                               -0.0198     0.1904 -0.1040 0.9172     -0.3930     0.3534
Living situation                              0.7865     0.6282  1.2519 0.2106     -0.4448     2.0177
Pack years                                    0.0036     0.0015  2.3992 0.0164      0.0007     0.0065
Alcohol use - average number of drinks/week   0.0015     0.0253  0.0600 0.9522     -0.0482     0.0512
Substance Use Disorder                       -0.3955     0.6089 -0.6495 0.5160     -1.5888     0.7979
Depression                                    0.2631     0.2189  1.2017 0.2295     -0.1660     0.6922
Anxiety                                       0.4623     0.2164  2.1364 0.0326      0.0382     0.8864
Health Anxiety                                0.8713     0.1817  4.7941 0.0000      0.5151     1.2275
Delay to Hospital                             0.0806     0.1824  0.4418 0.6586     -0.2769     0.4380
Personal Stressors                            0.7040     0.1900  3.7053 0.0002      0.3316     1.0764
Menopause                                     0.1748     0.2428  0.7201 0.4715     -0.3010     0.6507
Complicated Pregnancy                         0.0137     0.2057  0.0665 0.9470     -0.3894     0.4167
Stroke History                               -0.3206     0.3359 -0.9544 0.3399     -0.9790     0.3378
MI History                                   -0.3299     0.3180 -1.0375 0.2995     -0.9531     0.2933
CABG/Stent History                            0.3718     0.3286  1.1312 0.2580     -0.2724     1.0159
High cholesterol                             -0.0790     0.1912 -0.4131 0.6795     -0.4538     0.2958
Diabetes                                     -0.2310     0.2177 -1.0614 0.2885     -0.6576     0.1956
Hypertension                                  0.2082     0.1992  1.0449 0.2961     -0.1823     0.5986
BMI                                           0.0008     0.0112  0.0674 0.9462     -0.0211     0.0226
HFrEF                                         0.2291     0.1882  1.2177 0.2233     -0.1397     0.5980
STEMI                                        -0.3181     0.1884 -1.6888 0.0913     -0.6873     0.0511
ESSI score                                    0.5521     0.1992  2.7715 0.0056      0.1617     0.9425
=====================================================================================================


 Outcome: HADS-D

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.411599
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                          Logit                        Method:                       MLE
Dependent Variable:             HADS-D                       Pseudo R-squared:             0.136
Date:                           2026-03-25 21:22             AIC:                          634.5922
No. Observations:               698                          BIC:                          771.0388
Df Model:                       29                           Log-Likelihood:               -287.30
Df Residuals:                   668                          LL-Null:                      -332.58
Converged:                      0.0000                       LLR p-value:                  2.9669e-08
No. Iterations:                 35.0000                      Scale:                        1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0228     0.0071 -3.2208 0.0013     -0.0367    -0.0089
Race                                         -0.1145     0.4283 -0.2674 0.7892     -0.9539     0.7249
Indigenous                                   -0.6872     0.7135 -0.9632 0.3354     -2.0856     0.7112
Gender Identity                             -20.0384 36944.7434 -0.0005 0.9996 -72430.4048 72390.3281
Highschool Education                         -0.1446     0.3908 -0.3700 0.7114     -0.9105     0.6213
Post- Secondary Education                     0.3158     0.2454  1.2868 0.1982     -0.1652     0.7967
Employment                                    0.1973     0.3362  0.5868 0.5573     -0.4617     0.8563
Household income before taxes                -0.3950     0.2476 -1.5956 0.1106     -0.8803     0.0902
Marital status                                0.2449     0.2328  1.0521 0.2927     -0.2113     0.7011
Living situation                              0.2881     0.6873  0.4192 0.6751     -1.0590     1.6352
Pack years                                   -0.0003     0.0018 -0.1501 0.8807     -0.0037     0.0032
Alcohol use - average number of drinks/week  -0.0073     0.0311 -0.2345 0.8146     -0.0682     0.0536
Substance Use Disorder                        0.3130     0.6299  0.4968 0.6193     -0.9217     1.5476
Depression                                    0.7164     0.2528  2.8333 0.0046      0.2208     1.2119
Anxiety                                      -0.0700     0.2550 -0.2744 0.7838     -0.5698     0.4299
Health Anxiety                                0.6734     0.2226  3.0255 0.0025      0.2372     1.1096
Delay to Hospital                             0.3335     0.2189  1.5236 0.1276     -0.0955     0.7626
Personal Stressors                            0.5015     0.2339  2.1443 0.0320      0.0431     0.9598
Menopause                                    -0.2860     0.2744 -1.0423 0.2973     -0.8238     0.2518
Complicated Pregnancy                        -0.3760     0.2626 -1.4319 0.1522     -0.8907     0.1387
Stroke History                                0.1370     0.3717  0.3685 0.7125     -0.5915     0.8654
MI History                                    0.8306     0.3694  2.2486 0.0245      0.1066     1.5545
CABG/Stent History                           -0.7903     0.4184 -1.8888 0.0589     -1.6104     0.0298
High cholesterol                              0.2987     0.2322  1.2862 0.1984     -0.1565     0.7538
Diabetes                                      0.1039     0.2578  0.4031 0.6869     -0.4014     0.6093
Hypertension                                 -0.1837     0.2384 -0.7707 0.4409     -0.6509     0.2835
BMI                                          -0.0480     0.0138 -3.4842 0.0005     -0.0750    -0.0210
HFrEF                                         0.1863     0.2237  0.8328 0.4050     -0.2521     0.6247
STEMI                                         0.0720     0.2221  0.3241 0.7459     -0.3633     0.5073
ESSI score                                    1.0547     0.2281  4.6230 0.0000      0.6076     1.5019
=====================================================================================================

Refitting after feature selection

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.411599
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                          Logit                        Method:                       MLE
Dependent Variable:             HADS-D                       Pseudo R-squared:             0.136
Date:                           2026-03-25 21:22             AIC:                          634.5922
No. Observations:               698                          BIC:                          771.0388
Df Model:                       29                           Log-Likelihood:               -287.30
Df Residuals:                   668                          LL-Null:                      -332.58
Converged:                      0.0000                       LLR p-value:                  2.9669e-08
No. Iterations:                 35.0000                      Scale:                        1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0228     0.0071 -3.2208 0.0013     -0.0367    -0.0089
Race                                         -0.1145     0.4283 -0.2674 0.7892     -0.9539     0.7249
Indigenous                                   -0.6872     0.7135 -0.9632 0.3354     -2.0856     0.7112
Gender Identity                             -20.0384 36944.7434 -0.0005 0.9996 -72430.4048 72390.3281
Highschool Education                         -0.1446     0.3908 -0.3700 0.7114     -0.9105     0.6213
Post- Secondary Education                     0.3158     0.2454  1.2868 0.1982     -0.1652     0.7967
Employment                                    0.1973     0.3362  0.5868 0.5573     -0.4617     0.8563
Household income before taxes                -0.3950     0.2476 -1.5956 0.1106     -0.8803     0.0902
Marital status                                0.2449     0.2328  1.0521 0.2927     -0.2113     0.7011
Living situation                              0.2881     0.6873  0.4192 0.6751     -1.0590     1.6352
Pack years                                   -0.0003     0.0018 -0.1501 0.8807     -0.0037     0.0032
Alcohol use - average number of drinks/week  -0.0073     0.0311 -0.2345 0.8146     -0.0682     0.0536
Substance Use Disorder                        0.3130     0.6299  0.4968 0.6193     -0.9217     1.5476
Depression                                    0.7164     0.2528  2.8333 0.0046      0.2208     1.2119
Anxiety                                      -0.0700     0.2550 -0.2744 0.7838     -0.5698     0.4299
Health Anxiety                                0.6734     0.2226  3.0255 0.0025      0.2372     1.1096
Delay to Hospital                             0.3335     0.2189  1.5236 0.1276     -0.0955     0.7626
Personal Stressors                            0.5015     0.2339  2.1443 0.0320      0.0431     0.9598
Menopause                                    -0.2860     0.2744 -1.0423 0.2973     -0.8238     0.2518
Complicated Pregnancy                        -0.3760     0.2626 -1.4319 0.1522     -0.8907     0.1387
Stroke History                                0.1370     0.3717  0.3685 0.7125     -0.5915     0.8654
MI History                                    0.8306     0.3694  2.2486 0.0245      0.1066     1.5545
CABG/Stent History                           -0.7903     0.4184 -1.8888 0.0589     -1.6104     0.0298
High cholesterol                              0.2987     0.2322  1.2862 0.1984     -0.1565     0.7538
Diabetes                                      0.1039     0.2578  0.4031 0.6869     -0.4014     0.6093
Hypertension                                 -0.1837     0.2384 -0.7707 0.4409     -0.6509     0.2835
BMI                                          -0.0480     0.0138 -3.4842 0.0005     -0.0750    -0.0210
HFrEF                                         0.1863     0.2237  0.8328 0.4050     -0.2521     0.6247
STEMI                                         0.0720     0.2221  0.3241 0.7459     -0.3633     0.5073
ESSI score                                    1.0547     0.2281  4.6230 0.0000      0.6076     1.5019
=====================================================================================================

In [101]:
print('3 Months')
fitLogReg(data3m, colsOutcomes3m)

3 Months

 Outcome: 3M New Depression Diagnosis

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.187169
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                       Logit                               Method:                   MLE
Dependent Variable:          3M New Depression Diagnosis         Pseudo R-squared:         0.301
Date:                        2026-03-25 21:23                    AIC:                      237.3189
No. Observations:            463                                 BIC:                      369.7262
Df Model:                    31                                  Log-Likelihood:           -86.659
Df Residuals:                431                                 LL-Null:                  -124.03
Converged:                   0.0000                              LLR p-value:              1.7820e-05
No. Iterations:              35.0000                             Scale:                    1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0570     0.0169 -3.3704 0.0008     -0.0901    -0.0239
Race                                         -0.9580     1.3711 -0.6987 0.4847     -3.6454     1.7294
Indigenous                                   -0.4155     1.8973 -0.2190 0.8266     -4.1341     3.3031
Gender Identity                             -12.6077 17309.6921 -0.0007 0.9994 -33938.9808 33913.7654
Highschool Education                          1.3856     0.8107  1.7092 0.0874     -0.2033     2.9745
Post- Secondary Education                     0.0376     0.5166  0.0727 0.9420     -0.9750     1.0501
Employment                                   -0.5080     0.6392 -0.7948 0.4267     -1.7607     0.7447
Household income before taxes                 0.5875     0.4786  1.2274 0.2197     -0.3506     1.5256
Marital status                               -0.3103     0.4938 -0.6284 0.5298     -1.2780     0.6575
Living situation                              1.0922     1.4111  0.7740 0.4389     -1.6735     3.8579
Pack years                                   -0.0122     0.0082 -1.4888 0.1365     -0.0282     0.0039
Alcohol use - average number of drinks/week  -0.1550     0.0873 -1.7761 0.0757     -0.3261     0.0160
Substance Use Disorder                       -0.8220     1.2320 -0.6672 0.5046     -3.2367     1.5926
Depression                                    2.3231     0.5556  4.1810 0.0000      1.2341     3.4122
Anxiety                                       1.0410     0.4768  2.1831 0.0290      0.1064     1.9756
Health Anxiety                                0.5992     0.4546  1.3181 0.1875     -0.2917     1.4901
Delay to Hospital                             0.0244     0.4292  0.0567 0.9548     -0.8170     0.8657
Personal Stressors                            0.1099     0.4570  0.2404 0.8100     -0.7859     1.0057
Menopause                                     0.9965     0.6216  1.6032 0.1089     -0.2218     2.2147
Complicated Pregnancy                         0.4407     0.4634  0.9510 0.3416     -0.4675     1.3489
Stroke History                               -0.1457     0.7833 -0.1860 0.8524     -1.6809     1.3895
MI History                                   -0.3601     0.9673 -0.3723 0.7097     -2.2561     1.5358
CABG/Stent History                           -0.0193     1.0035 -0.0192 0.9846     -1.9862     1.9476
High cholesterol                              0.1650     0.4600  0.3588 0.7197     -0.7366     1.0666
Diabetes                                     -1.1372     0.5909 -1.9244 0.0543     -2.2954     0.0210
Hypertension                                 -0.0470     0.4620 -0.1017 0.9190     -0.9526     0.8586
BMI                                          -0.0651     0.0260 -2.5029 0.0123     -0.1161    -0.0141
HFrEF                                         0.3115     0.4348  0.7165 0.4737     -0.5406     1.1636
STEMI                                        -0.5235     0.4410 -1.1872 0.2352     -1.3878     0.3408
ESSI score                                    0.7106     0.4746  1.4973 0.1343     -0.2196     1.6407
HADS-A                                       -0.0438     0.4921 -0.0891 0.9290     -1.0084     0.9207
HADS-D                                        0.8684     0.5389  1.6114 0.1071     -0.1878     1.9247
=====================================================================================================

Refitting after feature selection

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.187169
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                       Logit                               Method:                   MLE
Dependent Variable:          3M New Depression Diagnosis         Pseudo R-squared:         0.301
Date:                        2026-03-25 21:23                    AIC:                      237.3189
No. Observations:            463                                 BIC:                      369.7262
Df Model:                    31                                  Log-Likelihood:           -86.659
Df Residuals:                431                                 LL-Null:                  -124.03
Converged:                   0.0000                              LLR p-value:              1.7820e-05
No. Iterations:              35.0000                             Scale:                    1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0570     0.0169 -3.3704 0.0008     -0.0901    -0.0239
Race                                         -0.9580     1.3711 -0.6987 0.4847     -3.6454     1.7294
Indigenous                                   -0.4155     1.8973 -0.2190 0.8266     -4.1341     3.3031
Gender Identity                             -12.6077 17309.6921 -0.0007 0.9994 -33938.9808 33913.7654
Highschool Education                          1.3856     0.8107  1.7092 0.0874     -0.2033     2.9745
Post- Secondary Education                     0.0376     0.5166  0.0727 0.9420     -0.9750     1.0501
Employment                                   -0.5080     0.6392 -0.7948 0.4267     -1.7607     0.7447
Household income before taxes                 0.5875     0.4786  1.2274 0.2197     -0.3506     1.5256
Marital status                               -0.3103     0.4938 -0.6284 0.5298     -1.2780     0.6575
Living situation                              1.0922     1.4111  0.7740 0.4389     -1.6735     3.8579
Pack years                                   -0.0122     0.0082 -1.4888 0.1365     -0.0282     0.0039
Alcohol use - average number of drinks/week  -0.1550     0.0873 -1.7761 0.0757     -0.3261     0.0160
Substance Use Disorder                       -0.8220     1.2320 -0.6672 0.5046     -3.2367     1.5926
Depression                                    2.3231     0.5556  4.1810 0.0000      1.2341     3.4122
Anxiety                                       1.0410     0.4768  2.1831 0.0290      0.1064     1.9756
Health Anxiety                                0.5992     0.4546  1.3181 0.1875     -0.2917     1.4901
Delay to Hospital                             0.0244     0.4292  0.0567 0.9548     -0.8170     0.8657
Personal Stressors                            0.1099     0.4570  0.2404 0.8100     -0.7859     1.0057
Menopause                                     0.9965     0.6216  1.6032 0.1089     -0.2218     2.2147
Complicated Pregnancy                         0.4407     0.4634  0.9510 0.3416     -0.4675     1.3489
Stroke History                               -0.1457     0.7833 -0.1860 0.8524     -1.6809     1.3895
MI History                                   -0.3601     0.9673 -0.3723 0.7097     -2.2561     1.5358
CABG/Stent History                           -0.0193     1.0035 -0.0192 0.9846     -1.9862     1.9476
High cholesterol                              0.1650     0.4600  0.3588 0.7197     -0.7366     1.0666
Diabetes                                     -1.1372     0.5909 -1.9244 0.0543     -2.2954     0.0210
Hypertension                                 -0.0470     0.4620 -0.1017 0.9190     -0.9526     0.8586
BMI                                          -0.0651     0.0260 -2.5029 0.0123     -0.1161    -0.0141
HFrEF                                         0.3115     0.4348  0.7165 0.4737     -0.5406     1.1636
STEMI                                        -0.5235     0.4410 -1.1872 0.2352     -1.3878     0.3408
ESSI score                                    0.7106     0.4746  1.4973 0.1343     -0.2196     1.6407
HADS-A                                       -0.0438     0.4921 -0.0891 0.9290     -1.0084     0.9207
HADS-D                                        0.8684     0.5389  1.6114 0.1071     -0.1878     1.9247
=====================================================================================================


 Outcome: 3M New Anxiety Diagnosis

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.245490
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                        Logit                              Method:                     MLE
Dependent Variable:           3M New Anxiety Diagnosis           Pseudo R-squared:           0.135
Date:                         2026-03-25 21:23                   AIC:                        291.3233
No. Observations:             463                                BIC:                        423.7306
Df Model:                     31                                 Log-Likelihood:             -113.66
Df Residuals:                 431                                LL-Null:                    -131.40
Converged:                    0.0000                             LLR p-value:                0.26519
No. Iterations:               35.0000                            Scale:                      1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0300     0.0134 -2.2412 0.0250     -0.0563    -0.0038
Race                                         -0.6092     1.0533 -0.5784 0.5630     -2.6736     1.4552
Indigenous                                    1.1490     1.3220  0.8691 0.3848     -1.4421     3.7402
Gender Identity                             -15.5572 17312.5158 -0.0009 0.9993 -33947.4647 33916.3503
Highschool Education                          0.4489     0.7916  0.5671 0.5706     -1.1025     2.0004
Post- Secondary Education                    -0.3978     0.4465 -0.8911 0.3729     -1.2729     0.4772
Employment                                    0.0873     0.5724  0.1525 0.8788     -1.0346     1.2092
Household income before taxes                 0.2500     0.4099  0.6098 0.5420     -0.5534     1.0533
Marital status                               -0.0664     0.4091 -0.1623 0.8711     -0.8682     0.7354
Living situation                              1.2474     1.2681  0.9837 0.3253     -1.2380     3.7329
Pack years                                   -0.0001     0.0028 -0.0504 0.9598     -0.0056     0.0053
Alcohol use - average number of drinks/week  -0.0543     0.0649 -0.8372 0.4025     -0.1814     0.0728
Substance Use Disorder                        0.0099     1.2693  0.0078 0.9938     -2.4779     2.4976
Depression                                    0.6318     0.4259  1.4835 0.1379     -0.2029     1.4665
Anxiety                                       0.9331     0.4078  2.2879 0.0221      0.1338     1.7324
Health Anxiety                               -0.3150     0.4128 -0.7630 0.4454     -1.1240     0.4941
Delay to Hospital                             0.1696     0.3739  0.4537 0.6500     -0.5632     0.9024
Personal Stressors                            0.3545     0.3971  0.8928 0.3720     -0.4238     1.1328
Menopause                                     0.6236     0.5545  1.1246 0.2608     -0.4632     1.7105
Complicated Pregnancy                         0.1815     0.4018  0.4516 0.6515     -0.6060     0.9689
Stroke History                                0.0001     0.6076  0.0002 0.9999     -1.1908     1.1910
MI History                                   -0.5313     0.8165 -0.6507 0.5152     -2.1315     1.0690
CABG/Stent History                           -0.6614     0.9178 -0.7206 0.4712     -2.4603     1.1376
High cholesterol                              0.3227     0.3976  0.8116 0.4170     -0.4566     1.1019
Diabetes                                     -0.8989     0.5497 -1.6350 0.1020     -1.9763     0.1786
Hypertension                                  0.1262     0.3967  0.3181 0.7504     -0.6513     0.9037
BMI                                          -0.0573     0.0253 -2.2644 0.0235     -0.1068    -0.0077
HFrEF                                        -0.1062     0.3796 -0.2798 0.7797     -0.8502     0.6378
STEMI                                        -0.4138     0.3857 -1.0730 0.2833     -1.1697     0.3421
ESSI score                                    0.6100     0.4055  1.5041 0.1326     -0.1849     1.4048
HADS-A                                       -0.5069     0.4444 -1.1406 0.2540     -1.3779     0.3641
HADS-D                                        0.4314     0.4881  0.8837 0.3768     -0.5253     1.3881
=====================================================================================================

Refitting after feature selection

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.245490
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                        Logit                              Method:                     MLE
Dependent Variable:           3M New Anxiety Diagnosis           Pseudo R-squared:           0.135
Date:                         2026-03-25 21:23                   AIC:                        291.3233
No. Observations:             463                                BIC:                        423.7306
Df Model:                     31                                 Log-Likelihood:             -113.66
Df Residuals:                 431                                LL-Null:                    -131.40
Converged:                    0.0000                             LLR p-value:                0.26519
No. Iterations:               35.0000                            Scale:                      1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0300     0.0134 -2.2412 0.0250     -0.0563    -0.0038
Race                                         -0.6092     1.0533 -0.5784 0.5630     -2.6736     1.4552
Indigenous                                    1.1490     1.3220  0.8691 0.3848     -1.4421     3.7402
Gender Identity                             -15.5572 17312.5158 -0.0009 0.9993 -33947.4647 33916.3503
Highschool Education                          0.4489     0.7916  0.5671 0.5706     -1.1025     2.0004
Post- Secondary Education                    -0.3978     0.4465 -0.8911 0.3729     -1.2729     0.4772
Employment                                    0.0873     0.5724  0.1525 0.8788     -1.0346     1.2092
Household income before taxes                 0.2500     0.4099  0.6098 0.5420     -0.5534     1.0533
Marital status                               -0.0664     0.4091 -0.1623 0.8711     -0.8682     0.7354
Living situation                              1.2474     1.2681  0.9837 0.3253     -1.2380     3.7329
Pack years                                   -0.0001     0.0028 -0.0504 0.9598     -0.0056     0.0053
Alcohol use - average number of drinks/week  -0.0543     0.0649 -0.8372 0.4025     -0.1814     0.0728
Substance Use Disorder                        0.0099     1.2693  0.0078 0.9938     -2.4779     2.4976
Depression                                    0.6318     0.4259  1.4835 0.1379     -0.2029     1.4665
Anxiety                                       0.9331     0.4078  2.2879 0.0221      0.1338     1.7324
Health Anxiety                               -0.3150     0.4128 -0.7630 0.4454     -1.1240     0.4941
Delay to Hospital                             0.1696     0.3739  0.4537 0.6500     -0.5632     0.9024
Personal Stressors                            0.3545     0.3971  0.8928 0.3720     -0.4238     1.1328
Menopause                                     0.6236     0.5545  1.1246 0.2608     -0.4632     1.7105
Complicated Pregnancy                         0.1815     0.4018  0.4516 0.6515     -0.6060     0.9689
Stroke History                                0.0001     0.6076  0.0002 0.9999     -1.1908     1.1910
MI History                                   -0.5313     0.8165 -0.6507 0.5152     -2.1315     1.0690
CABG/Stent History                           -0.6614     0.9178 -0.7206 0.4712     -2.4603     1.1376
High cholesterol                              0.3227     0.3976  0.8116 0.4170     -0.4566     1.1019
Diabetes                                     -0.8989     0.5497 -1.6350 0.1020     -1.9763     0.1786
Hypertension                                  0.1262     0.3967  0.3181 0.7504     -0.6513     0.9037
BMI                                          -0.0573     0.0253 -2.2644 0.0235     -0.1068    -0.0077
HFrEF                                        -0.1062     0.3796 -0.2798 0.7797     -0.8502     0.6378
STEMI                                        -0.4138     0.3857 -1.0730 0.2833     -1.1697     0.3421
ESSI score                                    0.6100     0.4055  1.5041 0.1326     -0.1849     1.4048
HADS-A                                       -0.5069     0.4444 -1.1406 0.2540     -1.3779     0.3641
HADS-D                                        0.4314     0.4881  0.8837 0.3768     -0.5253     1.3881
=====================================================================================================


 Outcome: 3M New Substance Use Disorder

Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Unable to converge


 Outcome: 3M New Stroke

Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Unable to converge


 Outcome: 3M New MI

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.081606
         Iterations: 35
                                              Results: Logit
===========================================================================================================
Model:                              Logit                          Method:                         MLE

In [102]:
print('6 Months')
fitLogReg(data6m, colsOutcomes6m)

6 Months

 Outcome: 6M New Depression Diagnosis

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.119086
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                       Logit                               Method:                   MLE
Dependent Variable:          6M New Depression Diagnosis         Pseudo R-squared:         0.582
Date:                        2026-03-25 21:23                    AIC:                      176.4563
No. Observations:            363                                 BIC:                      351.7045
Df Model:                    44                                  Log-Likelihood:           -43.228
Df Residuals:                318                                 LL-Null:                  -103.52
Converged:                   0.0000                              LLR p-value:              4.7089e-09
No. Iterations:              35.0000                             Scale:                    1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0264     0.0274 -0.9646 0.3348     -0.0801     0.0273
Race                                         -4.6084     2.2116 -2.0837 0.0372     -8.9431    -0.2737
Indigenous                                    5.8612     2.2392  2.6176 0.0089      1.4726    10.2499
Gender Identity                             -14.1831  6284.2099 -0.0023 0.9982 -12331.0082 12302.6419
Highschool Education                          0.7435     1.2600  0.5901 0.5551     -1.7260     3.2131
Post- Secondary Education                     0.6245     0.8630  0.7236 0.4693     -1.0669     2.3158
Employment                                    1.3084     1.3388  0.9773 0.3284     -1.3155     3.9323
Household income before taxes                -1.0342     0.8077 -1.2804 0.2004     -2.6173     0.5488
Marital status                                1.0880     0.8310  1.3092 0.1905     -0.5408     2.7168
Living situation                              2.3249     4.4010  0.5283 0.5973     -6.3008    10.9507
Pack years                                   -0.0469     0.0245 -1.9142 0.0556     -0.0950     0.0011
Alcohol use - average number of drinks/week   0.0773     0.1213  0.6371 0.5241     -0.1605     0.3151
Substance Use Disorder                      -25.3273 41483.6947 -0.0006 0.9995 -81331.8749 81281.2203
Depression                                    1.5359     0.9954  1.5430 0.1228     -0.4150     3.4869
Anxiety                                      -0.0478     0.8465 -0.0565 0.9549     -1.7069     1.6112
Health Anxiety                                0.1836     0.8694  0.2111 0.8328     -1.5205     1.8876
Delay to Hospital                             0.4263     0.8056  0.5292 0.5967     -1.1526     2.0052
Personal Stressors                           -1.0305     0.7922 -1.3007 0.1933     -2.5833     0.5223
Menopause                                    -0.8744     0.9624 -0.9085 0.3636     -2.7607     1.0119
Complicated Pregnancy                        -1.4637     0.9374 -1.5615 0.1184     -3.3010     0.3736
Stroke History                                2.7836     1.0023  2.7772 0.0055      0.8191     4.7482
MI History                                    1.4728     1.1616  1.2679 0.2048     -0.8038     3.7494
CABG/Stent History                           -1.3688     1.2324 -1.1106 0.2667     -3.7842     1.0467
High cholesterol                             -0.1875     0.8590 -0.2182 0.8272     -1.8711     1.4962
Diabetes                                      1.1081     0.8252  1.3428 0.1794     -0.5093     2.7255
Hypertension                                 -0.5414     0.8679 -0.6238 0.5328     -2.2425     1.1597
BMI                                          -0.0648     0.0423 -1.5302 0.1260     -0.1478     0.0182
HFrEF                                        -2.0699     0.8606 -2.4053 0.0162     -3.7566    -0.3833
STEMI                                        -0.1589     0.7434 -0.2137 0.8308     -1.6160     1.2982
ESSI score                                   -0.0947     0.8484 -0.1116 0.9111     -1.7576     1.5681
HADS-A                                        1.6491     0.9579  1.7216 0.0851     -0.2283     3.5266
HADS-D                                        1.0083     1.0204  0.9882 0.3231     -0.9916     3.0083
3M New Depression Diagnosis                   4.2138     1.0083  4.1792 0.0000      2.2376     6.1901
3M New Anxiety Diagnosis                      3.7713     1.2070  3.1246 0.0018      1.4056     6.1369
3M New Substance Use Disorder                -2.7728     2.3460 -1.1819 0.2372     -7.3708     1.8252
3M New Stroke                               -19.0394  9276.2060 -0.0021 0.9984 -18200.0691 18161.9904
3M New MI                                     1.9086     2.0782  0.9184 0.3584     -2.1645     5.9818
3M New CABG/Stent                            -0.3181     1.4238 -0.2234 0.8232     -3.1086     2.4725
3M Cardiac Rehab                             -0.9956     0.8971 -1.1098 0.2671     -2.7539     0.7627
3M Hospitalized                              -0.0319     0.9966 -0.0320 0.9745     -1.9852     1.9214
3M HADS-A                                     0.3286     0.8084  0.4064 0.6844     -1.2560     1.9131
3M HADS-D                                     0.5304     0.9909  0.5353 0.5925     -1.4117     2.4725
3M SF-12 (Low)                               -1.4139     0.8538 -1.6560 0.0977     -3.0874     0.2595
3M Cardiac Anxiety                            2.3843     0.9795  2.4342 0.0149      0.4645     4.3040
3M MOS (Low Support)                         -0.1617     1.0333 -0.1565 0.8756     -2.1870     1.8636
=====================================================================================================

Refitting after feature selection

Optimization terminated successfully.
         Current function value: 0.132577
         Iterations 10
                                      Results: Logit
===========================================================================================
Model:                   Logit                            Method:                MLE
Dependent Variable:      6M New Depression Diagnosis      Pseudo R-squared:      0.535
Date:                    2026-03-25 21:23                 AIC:                   168.2507
No. Observations:        363                              BIC:                   308.4492
Df Model:                35                               Log-Likelihood:        -48.125
Df Residuals:            327                              LL-Null:               -103.52
Converged:               1.0000                           LLR p-value:           8.4311e-10
No. Iterations:          10.0000                          Scale:                 1.0000
-------------------------------------------------------------------------------------------
                                             Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
-------------------------------------------------------------------------------------------
Age                                         -0.0350   0.0233 -1.5049 0.1323 -0.0807  0.0106
Race                                        -3.4068   1.8700 -1.8218 0.0685 -7.0719  0.2583
Indigenous                                   4.8664   1.8768  2.5930 0.0095  1.1880  8.5447
Highschool Education                         0.7832   1.1611  0.6745 0.5000 -1.4925  3.0588
Post- Secondary Education                    0.5263   0.7703  0.6832 0.4945 -0.9835  2.0360
Employment                                   0.4312   1.2236  0.3524 0.7245 -1.9671  2.8295
Household income before taxes               -0.7749   0.7261 -1.0671 0.2859 -2.1981  0.6483
Marital status                               0.5822   0.7138  0.8156 0.4147 -0.8169  1.9814
Living situation                             1.8110   3.3991  0.5328 0.5942 -4.8510  8.4731
Pack years                                  -0.0366   0.0219 -1.6668 0.0956 -0.0796  0.0064
Alcohol use - average number of drinks/week  0.0922   0.0973  0.9480 0.3431 -0.0984  0.2828
Depression                                   1.0784   0.7784  1.3855 0.1659 -0.4472  2.6040
Delay to Hospital                            0.4978   0.6809  0.7311 0.4647 -0.8368  1.8325
Personal Stressors                          -0.9610   0.7032 -1.3667 0.1717 -2.3391  0.4172
Menopause                                   -0.3516   0.8450 -0.4161 0.6773 -2.0077  1.3045
Complicated Pregnancy                       -1.0695   0.8041 -1.3300 0.1835 -2.6454  0.5065
Stroke History                               2.4113   0.9097  2.6507 0.0080  0.6283  4.1942
MI History                                   1.1243   1.0047  1.1191 0.2631 -0.8448  3.0935
CABG/Stent History                          -0.6568   1.0915 -0.6017 0.5474 -2.7962  1.4826
High cholesterol                             0.0466   0.7141  0.0653 0.9480 -1.3529  1.4461
Diabetes                                     1.2595   0.7570  1.6638 0.0962 -0.2242  2.7433
Hypertension                                -0.6349   0.7544 -0.8416 0.4000 -2.1135  0.8437
BMI                                         -0.0710   0.0407 -1.7432 0.0813 -0.1508  0.0088
HFrEF                                       -1.4821   0.7233 -2.0491 0.0404 -2.8997 -0.0645
HADS-A                                       1.4508   0.7996  1.8145 0.0696 -0.1163  3.0179
HADS-D                                       0.6689   0.8988  0.7442 0.4568 -1.0928  2.4306
3M New Depression Diagnosis                  3.8662   0.8852  4.3677 0.0000  2.1312  5.6011
3M New Anxiety Diagnosis                     2.8264   0.9730  2.9047 0.0037  0.9192  4.7335
3M New Substance Use Disorder               -1.8399   2.1944 -0.8384 0.4018 -6.1409  2.4611
3M New MI                                    1.3780   1.8747  0.7351 0.4623 -2.2964  5.0525
3M New CABG/Stent                           -0.2874   1.2993 -0.2212 0.8249 -2.8340  2.2592
3M Cardiac Rehab                            -0.2055   0.8110 -0.2534 0.7999 -1.7950  1.3839
3M HADS-A                                    0.0870   0.6750  0.1289 0.8975 -1.2359  1.4099
3M HADS-D                                    0.6175   0.8792  0.7024 0.4825 -1.1056  2.3406
3M SF-12 (Low)                              -1.2890   0.7679 -1.6785 0.0932 -2.7941  0.2161
3M Cardiac Anxiety                           2.1588   0.8455  2.5535 0.0107  0.5018  3.8159
===========================================================================================


 Outcome: 6M New Anxiety Diagnosis

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.160489
         Iterations: 35
                                           Results: Logit
=====================================================================================================
Model:                        Logit                             Method:                    MLE
Dependent Variable:           6M New Anxiety Diagnosis          Pseudo R-squared:          0.484
Date:                         2026-03-25 21:23                  AIC:                       206.5153
No. Observations:             363                               BIC:                       381.7634
Df Model:                     44                                Log-Likelihood:            -58.258
Df Residuals:                 318                               LL-Null:                   -112.87
Converged:                    0.0000                            LLR p-value:               1.8224e-07
No. Iterations:               35.0000                           Scale:                     1.0000
-----------------------------------------------------------------------------------------------------
                                             Coef.    Std.Err.     z    P>|z|     [0.025     0.975]
-----------------------------------------------------------------------------------------------------
Age                                          -0.0348     0.0191 -1.8249 0.0680     -0.0723     0.0026
Race                                         -1.8683     1.3752 -1.3585 0.1743     -4.5636     0.8271
Indigenous                                    3.8718     1.5407  2.5130 0.0120      0.8521     6.8914
Gender Identity                             -12.9424  9254.8989 -0.0014 0.9989 -18152.2109 18126.3262
Highschool Education                         -0.9567     1.4447 -0.6622 0.5078     -3.7883     1.8749
Post- Secondary Education                    -0.2086     0.7108 -0.2934 0.7692     -1.6017     1.1845
Employment                                   -0.1391     0.9812 -0.1417 0.8873     -2.0622     1.7840
Household income before taxes                -0.2689     0.6723 -0.4000 0.6892     -1.5866     1.0488
Marital status                                0.8980     0.6436  1.3952 0.1630     -0.3635     2.1595
Living situation                              3.4194     2.0304  1.6841 0.0922     -0.5601     7.3989
Pack years                                   -0.0051     0.0068 -0.7518 0.4522     -0.0185     0.0082
Alcohol use - average number of drinks/week  -0.1529     0.1065 -1.4355 0.1512     -0.3616     0.0559
Substance Use Disorder                      -17.9452  1075.4131 -0.0167 0.9867  -2125.7161  2089.8257
Depression                                    0.5066     0.7333  0.6909 0.4896     -0.9306     1.9439
Anxiety                                      -0.1907     0.6689 -0.2852 0.7755     -1.5017     1.1202
Health Anxiety                                0.1595     0.6294  0.2534 0.8000     -1.0741     1.3931
Delay to Hospital                             0.3973     0.6239  0.6368 0.5243     -0.8255     1.6201
Personal Stressors                            1.6587     0.6809  2.4361 0.0148      0.3242     2.9931
Menopause                                    -1.2351     0.7178 -1.7207 0.0853     -2.6420     0.1717
Complicated Pregnancy                        -1.4633     0.7786 -1.8793 0.0602     -2.9894     0.0628
Stroke History                                0.6253     0.9036  0.6921 0.4889     -1.1457     2.3963
MI History                                    0.5090     1.0776  0.4723 0.6367     -1.6032     2.6211
CABG/Stent History                           -0.3836     1.1801 -0.3251 0.7451     -2.6966     1.9293
High cholesterol                              0.2196     0.6526  0.3365 0.7365     -1.0595     1.4986
Diabetes                                     -0.5177     0.7748 -0.6682 0.5040     -2.0362     1.0008
Hypertension                                 -1.0753     0.6950 -1.5472 0.1218     -2.4375     0.2869
BMI                                          -0.0148     0.0345 -0.4294 0.6676     -0.0824     0.0528
HFrEF                                        -0.5534     0.6313 -0.8766 0.3807     -1.7908     0.6840
STEMI                                        -0.4843     0.6102 -0.7936 0.4274     -1.6802     0.7117
ESSI score                                    0.1310     0.7394  0.1772 0.8594     -1.3182     1.5802
HADS-A                                        1.2274     0.6795  1.8063 0.0709     -0.1044     2.5592
HADS-D                                       -0.4558     0.8100 -0.5627 0.5736     -2.0434     1.1318
3M New Depression Diagnosis                   0.7893     0.8392  0.9406 0.3469     -0.8555     2.4341
3M New Anxiety Diagnosis                      4.9861     0.9324  5.3477 0.0000      3.1587     6.8135
3M New Substance Use Disorder                -0.5592     2.1974 -0.2545 0.7991     -4.8661     3.7477
3M New Stroke                               -22.6022 46993.4148 -0.0005 0.9996 -92128.0028 92082.7984
3M New MI                                     1.6828     1.4774  1.1391 0.2547     -1.2128     4.5785
3M New CABG/Stent                            -0.0171     1.3326 -0.0129 0.9897     -2.6289     2.5947
3M Cardiac Rehab                             -0.4123     0.6691 -0.6162 0.5377     -1.7238     0.8991
3M Hospitalized                               0.9157     0.8940  1.0243 0.3057     -0.8365     2.6680
3M HADS-A                                     1.0153     0.6971  1.4564 0.1453     -0.3511     2.3816
3M HADS-D                                    -0.8694     0.9024 -0.9634 0.3353     -2.6382     0.8993
3M SF-12 (Low)                               -1.9857     0.6934 -2.8636 0.0042     -3.3448    -0.6266
3M Cardiac Anxiety                            1.3362     0.7660  1.7444 0.0811     -0.1651     2.8374
3M MOS (Low Support)                         -0.3777     0.8903 -0.4242 0.6714     -2.1226     1.3673
=====================================================================================================

Refitting after feature selection

Optimization terminated successfully.
         Current function value: 0.175385
         Iterations 9
                                      Results: Logit
===========================================================================================
Model:                    Logit                          Method:                 MLE
Dependent Variable:       6M New Anxiety Diagnosis       Pseudo R-squared:       0.436
Date:                     2026-03-25 21:23               AIC:                    199.3296
No. Observations:         363                            BIC:                    339.5281
Df Model:                 35                             Log-Likelihood:         -63.665
Df Residuals:             327                            LL-Null:                -112.87
Converged:                1.0000                         LLR p-value:            6.1314e-08
No. Iterations:           9.0000                         Scale:                  1.0000
-------------------------------------------------------------------------------------------
                                             Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
-------------------------------------------------------------------------------------------
Age                                         -0.0349   0.0166 -2.1049 0.0353 -0.0673 -0.0024
Race                                        -1.1252   1.1451 -0.9827 0.3258 -3.3695  1.1191
Indigenous                                   3.1472   1.3609  2.3126 0.0207  0.4799  5.8145
Highschool Education                        -0.5486   1.2531 -0.4378 0.6615 -3.0046  1.9073
Post- Secondary Education                   -0.4322   0.6652 -0.6497 0.5159 -1.7360  0.8716
Household income before taxes               -0.1935   0.6097 -0.3173 0.7510 -1.3885  1.0016
Marital status                               0.5648   0.5824  0.9698 0.3322 -0.5767  1.7063
Living situation                             2.8004   1.8660  1.5007 0.1334 -0.8570  6.4578
Pack years                                  -0.0037   0.0061 -0.6119 0.5406 -0.0156  0.0082
Alcohol use - average number of drinks/week -0.1246   0.1058 -1.1777 0.2389 -0.3320  0.0828
Depression                                   0.1470   0.6166  0.2385 0.8115 -1.0614  1.3555
Delay to Hospital                            0.2270   0.5415  0.4192 0.6751 -0.8344  1.2884
Personal Stressors                           1.3807   0.5997  2.3022 0.0213  0.2052  2.5561
Menopause                                   -1.1761   0.6605 -1.7806 0.0750 -2.4706  0.1185
Complicated Pregnancy                       -1.0861   0.6964 -1.5596 0.1189 -2.4510  0.2788
Stroke History                               0.4273   0.8276  0.5163 0.6057 -1.1948  2.0493
MI History                                  -0.0050   0.9659 -0.0052 0.9959 -1.8981  1.8881
CABG/Stent History                           0.1517   1.0467  0.1449 0.8848 -1.8999  2.2033
High cholesterol                             0.3814   0.6012  0.6344 0.5258 -0.7969  1.5597